src/main/java/hudson/plugins/git/GitSCM.java, src/test/java/hudson/plugins/git/GitSCMTest.java
Incorrect behavior is detected when the job has excluded paths and is aimed to track multiple branches. Consider the following:
<pre>
master: 1+ ---- 3+ -- 4
branch1:   \-2+ --------- 5
</pre>
Commits suffixed with "+" are commits with some paths that are not excluded, so the build should trigger for them only. Number of commit shows the time it is committed.
In this situation commit 5 causes project build, while 5 is to be ignored.
The cause of the error is that Git plugin uses last build information to get all the new commits to analyze. After commit 5 is pushed, Git plugin checks for the latest build (it is for commit 3) and try to get all the new commits as git log 3..5, which includes commit 2, which is already built.
Suggested pull request fixes the issue by getting last build …
=> Fixed multibranch polling with exclusions

src/main/java/hudson/plugins/git/GitStatus.java, src/test/java/hudson/plugins/git/GitSCMTest.java
[JENKINS-26582](https://issues.jenkins-ci.org/browse/JENKINS-26582)
@reviewbybees
=> [JENKINS-26582] notifyCommit should ignore projects without SCMTrigger

src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java, src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java, src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy, src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/help-reference.html
Addresses https://issues.jenkins-ci.org/browse/JENKINS-18666
=> [FIXED JENKINS-18666] Submodule reference

src/main/java/hudson/plugins/git/GitStatus.java, src/main/java/jenkins/plugins/git/GitSCMSource.java
[JENKINS-31884](https://issues.jenkins-ci.org/browse/JENKINS-31884)
Amends #315. Verified by https://github.com/jenkinsci/workflow-plugin/pull/262.
@reviewbybees
=> [JENKINS-31884] Deliver webhooks to all listeners

src/main/java/hudson/plugins/git/GitSCM.java, src/test/java/hudson/plugins/git/browser/GithubWebTest.java
[JENKINS-33409](https://issues.jenkins-ci.org/browse/JENKINS-33409)
Could potentially affect other projects too, just noticed it in this context: breaks GitHub web links for multibranch projects.
@reviewbybees
=> [JENKINS-33409] Incorrect repository browser detection for github-branch-source

Jenkinsfile
This is a basic jenkinsfile that calls maven.
=> Add Jenkinsfile 

pom.xml, src/main/java/hudson/plugins/git/GitSCM.java, src/main/java/jenkins/plugins/git/GitStep.java, src/main/resources/jenkins/plugins/git/GitStep/config.jelly, src/main/resources/jenkins/plugins/git/GitStep/help.html, src/main/resources/jenkins/plugins/git/Messages.properties, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java, src/test/java/jenkins/plugins/git/GitStepTest.java
[JENKINS-35247](https://issues.jenkins-ci.org/browse/JENKINS-35247)
Note that although this adds a new dependency, the transitive dependencies (intentionally) include no GUI extensions, so it should have no effect on non-Pipeline users.
@reviewbybees
=> [JENKINS-35247] Moved GitStep to git-plugin

Jenkinsfile, pom.xml
Speed up build by executing in parallel on multiple nodes.
=> Add parallel test execution

pom.xml, src/main/java/hudson/plugins/git/UserRemoteConfig.java, src/main/java/jenkins/plugins/git/GitSCMSource.java
=> [FIXED JENKINS-35525] Upgrade to Credentials 2.1.0+ API for populating credentials drop-down

pom.xml, src/main/java/hudson/plugins/git/UserRemoteConfig.java, src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/12.
@reviewbybees
=> [JENKINS-31155] Ability to retrieve a single revision

src/main/java/hudson/plugins/git/GitSCM.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/git-plugin/444)
=> Null is allowed, remove annotation

pom.xml, src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/main/java/jenkins/plugins/git/GitSCMFile.java, src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java, src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java, src/test/java/jenkins/plugins/git/GitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
See [JENKINS-39355](https://issues.jenkins-ci.org/browse/JENKINS-39355) [JENKINS-40382](https://issues.jenkins-ci.org/browse/JENKINS-40382)
@reviewbybees (this will also need merging for the 3.x branch)
=> 2.6.x branch [JENKINS-39355 follow up][JENKINS-40382] Pick up SCM API 2.x

pom.xml, src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/main/java/jenkins/plugins/git/GitSCMFile.java, src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java, src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java, src/test/java/jenkins/plugins/git/GitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
https://github.com/jenkinsci/git-plugin/pull/454 but for master
See [JENKINS-39355](https://issues.jenkins-ci.org/browse/JENKINS-39355) [JENKINS-40382](https://issues.jenkins-ci.org/browse/JENKINS-40382)
@reviewbybees (this will also need merging for the 3.x branch)
=> master branch [JENKINS-39355 follow up][JENKINS-40382] Pick up SCM API 2.x

pom.xml, src/main/java/hudson/plugins/git/GitStatus.java, src/main/java/jenkins/plugins/git/GitSCMSource.java
See [JENKINS-41812](https://issues.jenkins-ci.org/browse/JENKINS-41812)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/27
@reviewbybees
=> [FIXED JENKINS-41812] Expose event origin to listeners

src/main/java/jenkins/plugins/git/GitSCMSource.java
See [JENKINS-42236](https://issues.jenkins-ci.org/browse/JENKINS-42236)
@reviewbybees
=> [FIXED JENKINS-42236] Replicate the isMatch guard in heads

pom.xml, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/32.
@reviewbybees
=> Using official version of AbstractSampleDVCSRepoRule

src/main/resources/jenkins/plugins/git/GitSCMSource/help-credentialsId.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-excludes.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-gitTool.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-ignoreOnPushNotifications.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-includes.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-rawRefSpecs.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-remote.html, src/main/resources/jenkins/plugins/git/GitSCMSource/help-remoteName.html
See [JENKINS-36327](https://issues.jenkins-ci.org/browse/JENKINS-36327)
@reviewbybees
=> [FIXED JENKINS-36327] Add help files for GitSCMSource

src/main/resources/hudson/plugins/git/GitSCM/global.jelly
Hi, I found a grammatical error. I think fixing it makes the sentence easier to read.
=> Fix a typo

src/main/java/hudson/plugins/git/GitBranchSpecifierColumn.java, src/main/resources/hudson/plugins/git/GitBranchSpecifierColumn/column.jelly
My first implemtation, any comments, reviews and changes to wordings would be appreciated.
=> Implemented JENKINS-37331 - Add branches to build list view column

src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
See [JENKINS-44751](https://issues.jenkins-ci.org/browse/JENKINS-44751)
@reviewbybees
=> [JENKINS-44751] Use ls-remote to determine live list of remote branches

src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
Complements https://github.com/jenkinsci/workflow-multibranch-plugin/pull/67.
@reviewbybees
=> [JENKINS-42817] GitSCMFileSystem was needlessly rejecting slashy branches

src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
Not needed as of a4febc0
@reviewbybees
=> Remove git 1.7.1 special case from test

src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
May eventually rework the test to not depend on those tags, but
it is simple enough to pull the tags into the current repository
if they are not found.
=> Adapt GitSCMFileSystemTest to always have git-2.6.0 and git-2.6.1 tags

pom.xml
No need to redefine code coverage technique in this plugin
@reviewbybees
=> Use parent pom enable-jacoco profile for coverage

pom.xml
Use latest parent pom for consistency, best developer experience.
@reviewbybees
=> Update parent pom to 2.33

src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/main/java/jenkins/plugins/git/GitTagSCMHead.java, src/main/java/jenkins/plugins/git/GitTagSCMRevision.java, src/main/java/jenkins/plugins/git/traits/TagDiscoveryTrait.java, src/main/resources/jenkins/plugins/git/traits/Messages.properties, src/main/resources/jenkins/plugins/git/traits/TagDiscoveryTrait/config.jelly, src/main/resources/jenkins/plugins/git/traits/TagDiscoveryTrait/help.html, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- I suspect there are additional changes required before can merge for git
- I suspect there are additional changes required to branch-api before safe to merge for users
See [JENKINS-46207](https://issues.jenkins-ci.org/browse/JENKINS-46207)
@reviewbybees
=> [JENKINS-46207] Enable tag discovery

pom.xml
Prepare for git plugin 3.6.0 to release with support for tag discovery trait
=> Update parent pom and version

src/test/java/hudson/plugins/git/RevisionParameterActionTest.java, src/test/java/hudson/plugins/git/SubmoduleConfigTest.java
Remove tests which do not add significant value, especially if they slow execution.
Parameter combining is a fundamental Jenkins core behavior, not something that needs specific testing in the git plugin.
=> Remove duplicate and unhelpful tests

src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
=> Refactor out the common SCMProbe implementation

pom.xml
Branch source, branch API, and scm API typically.
[Fix JENKINS-49160] update maintainer information
=> Add Stephen Connolly as a maintainer

Jenkinsfile, essentials.yml
See the comments on JENKINS-50540,  this is going to be augmented via the Custom War Packager and JEP-305 in follow up PRs
This PR can not be merged until [pipeline-library#48](https://github.com/jenkins-infra/pipeline-library/pull/48) is merged
*Note that as I am not a trusted source the PR Builder is not going to use the changes in the Jenkinsfile, I hope for some maintainer to be able to do a Replay to test it, I have tested it successfully on my development environment*
=> [JENKINS-50621] Essentials Flow - Part 1

src/test/java/hudson/plugins/git/GitBranchSpecifierColumnTest.java
Low-cost test of some easy to test code
=> Add GitBranchSpecifierColumnTest

CONTRIBUTING.md, Jenkinsfile, README.md, essentials.yml, pom.xml, src/main/java/hudson/plugins/git/GitChangeSet.java, src/main/java/hudson/plugins/git/GitSCM.java, src/main/java/hudson/plugins/git/GitStatus.java, src/main/java/hudson/plugins/git/GitTagAction.java, src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java, src/main/java/hudson/plugins/git/util/BuildChooserDescriptor.java, src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java, src/main/java/hudson/plugins/git/util/GitUtils.java, src/main/java/hudson/plugins/git/util/InverseBuildChooser.java, src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/main/java/jenkins/plugins/git/GitSCMFile.java, src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/main/java/jenkins/plugins/git/traits/GitBrowserSCMSourceTrait.java, src/test/java/hudson/plugins/git/GitChangeSetEmptyTest.java, src/test/java/hudson/plugins/git/GitChangeSetListTest.java, src/test/java/hudson/plugins/git/GitChangeSetSimpleTest.java, src/test/java/hudson/plugins/git/GitPublisherTest.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/SCMTriggerTest.java, src/test/java/hudson/plugins/git/UserRemoteConfigTest.java, src/test/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowserTest.java, src/test/java/hudson/plugins/git/extensions/impl/PathRestrictionTest.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
Git plugin 4.0.0.  Key items for the checklist:
=> Use Jenkins 2.60.1, JDK 8, and git client 3.0.0

pom.xml
Don't delay updates to parent pom
=> Use parent pom 3.12

Jenkinsfile
=> Test with Jenkins 2.121.1

pom.xml
=> Use parent pom 3.17

src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
https://issues.jenkins-ci.org/browse/JENKINS-43894
On contrary to Freestyle projects' `getEnvironment`, `WorkflowRun.getEnvironment` doesn't provide node-specific environment variables as it can have multiple `node` blocks in parallel (see https://issues.jenkins-ci.org/browse/JENKINS-36267). So I suggest to pick up envvars just in place. @MarkEWaite @jglick 
=> [JENKINS-43894] Resolve environment variables in CloneOption reference path

pom.xml, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/GitStatusCrumbExclusionTest.java, src/test/java/hudson/plugins/git/extensions/impl/SubmoduleOptionTest.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java, src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
It provides more features and is implemented in a cleaner way.
See https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2.
Test tooling update
=> Upgrade to Mocktio 2

.mvn/extensions.xml
=> Use git-changelist-maven-extension 1.0-beta-6

.mvn/extensions.xml, pom.xml, src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
Subsumes #621; trying to fix test failures encountered there. Downstream of https://github.com/jenkinsci/plugin-pom/pull/125.
=> Parent update

src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
Windows file system last modified times seem to vary wildly.  The
variation is sometimes as much as 9 seconds.  Rather than set a very
large size, skip the last modified test on Windows.
Test change only
=> Skip last modified smoke test on Windows

pom.xml
=> Fixing dependencies to remove extraneous JARs from WEB-INF/lib

pom.xml, src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
=> Declare GitSampleRepoRule variable nearer its use

pom.xml
Prepare the release candidate for git plugin 4.0.0.
=> Use git client 3.0.0-rc

Jenkinsfile, pom.xml
Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.
=> Enable testing with Java 11 on recommended configuration

pom.xml
Test with the latest versions of the script-security, junit, & equalsverifier plugins.
=> Update test components (script-security, junit, & equalsverifier)

pom.xml
Test with latest script security plugin. Does not create dependency for users, checks latest script-security plugin.
=> Test script security 1.55

pom.xml
Use latest equals verifier 3.1.8
=> Test equalsverifier 3.1.8

pom.xml
Use latest script-security for tests so that we can detect incompatibilities sooner.
=> Test with script-security 1.58

pom.xml, src/main/java/hudson/plugins/git/UserMergeOptions.java, src/test/java/hudson/plugins/git/UserMergeOptionsTest.java
Downstream of https://github.com/jenkinsci/structs-plugin/pull/43, continuing #698.
=> [JENKINS-51638] UserMergeOptions patch via CustomDescribableModel

pom.xml
=> Use checkstyle 8.20

src/test/java/hudson/plugins/git/GitSCMTest.java
Additional test coverage of included and excluded regions, in an attempt to troubleshoot [JENKINS-23606](https://issues.jenkins-ci.org/browse/JENKINS-23606).
In attempting to recreate, and possibly fix, [JENKINS-23606](https://issues.jenkins-ci.org/browse/JENKINS-23606), I first created eight new automated tests in `GitSCMTest`. One I had the tests written, I tried recreating the original issue. My suspicion is that the bug reports stem from difficulty that users may have in defining their included and excluded regions. At least one comment in the bug report describes the use of leading `/` characters in these regions, which I suspect is the cause of that particular user's issue.
The tests were already written, though, and it felt wasteful to cast them aside.
=> Add tests related to included and excluded regions (see JENKINS-23606)

pom.xml
Test with more recent releases of several components which are only used in tests.  Better to test with the newer releases because it is more likely to detect problems due to changes in newer releases.
=> Test with more recent components

pom.xml
Test the latest release of the configuration as code plugin.  Use the latest checkstyle release for static analysis.
=> Test with latest JCasC and with latest checkstyle

.dependabot/config.yml, pom.xml
=> Update pom to latest parent and latest checkstyle

pom.xml
Update from JCasC 1.24 to 1.25 in test dependencies.
=> Test with JCasC 1.25

pom.xml
see https://github.com/jenkinsci/plugin-pom/blob/plugin-3.49/pom.xml#L63-L64
=> Replace deprecated concurrency property

src/main/java/hudson/plugins/git/GitChangeSet.java, src/main/java/hudson/plugins/git/GitRevisionBuildParameters.java, src/main/java/hudson/plugins/git/GitSCM.java, src/main/java/hudson/plugins/git/GitStatus.java, src/main/java/hudson/plugins/git/GitTagAction.java, src/main/java/hudson/plugins/git/UserRemoteConfig.java, src/main/java/hudson/plugins/git/browser/FisheyeGitRepositoryBrowser.java, src/main/java/hudson/plugins/git/extensions/GitSCMExtensionDescriptor.java, src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPath.java, src/main/java/hudson/plugins/git/util/BuildChooser.java, src/main/java/hudson/plugins/git/util/BuildChooserDescriptor.java, src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/main/java/jenkins/plugins/git/traits/GitBrowserSCMSourceTrait.java
=> Cleanup - Remove obsolete SuppressFBWarnings and unused Loggers

README.md
Describe the additional behaviors available in Freestyle and Matrix jobs. Many of the behaviors are also available in Pipeline jobs.
=> Document additional checkout behaviours

src/main/java/hudson/plugins/git/extensions/impl/CheckoutOption.java, src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java, src/main/java/hudson/plugins/git/extensions/impl/LocalBranch.java, src/main/java/hudson/plugins/git/extensions/impl/RelativeTargetDirectory.java, src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/main/java/jenkins/plugins/git/traits/CloneOptionTrait.java, src/main/resources/hudson/plugins/git/Messages.properties, src/main/resources/hudson/plugins/git/extensions/impl/Messages.properties, src/main/resources/jenkins/plugins/git/Messages.properties, src/main/resources/jenkins/plugins/git/traits/Messages.properties
=> Add localization support

pom.xml, src/test/java/jenkins/plugins/git/GitToolJCasCCompatibilityTest.java
Use the most recent git client 3.0.0 beta release.
=> Use git client 3.0.0-beta12

pom.xml
Prepare for release 4.0.0 of git plugin.
=> Use git client plugin 3.0.0

src/main/resources/hudson/plugins/git/BranchSpec/help-name.html, src/main/resources/hudson/plugins/git/UserMergeOptions/help-fastForwardMode.html
see https://developer.mozilla.org/docs/Web/HTML/Element/br
=> Fix invalid HTML line break elements

CONTRIBUTING.adoc, Priorities.adoc, README.adoc
Encourage help from others by listing current development priorities and processes.
CC: @batmat, @oleg-nenashev
=> List development priorities and processes

src/main/java/hudson/plugins/git/GitChangeSet.java, src/main/java/hudson/plugins/git/GitSCM.java, src/main/java/hudson/plugins/git/GitTagAction.java, src/main/java/hudson/plugins/git/SubmoduleCombinator.java, src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java, src/main/java/hudson/plugins/git/extensions/impl/PruneStaleBranch.java, src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/main/java/jenkins/plugins/git/GitSCMSource.java, src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java, src/test/java/hudson/plugins/git/GitChangeSetBadArgsTest.java, src/test/java/hudson/plugins/git/MultipleSCMTest.java, src/test/java/hudson/plugins/git/SCMTriggerTest.java, src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java, src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionWorkflowTest.java, src/test/java/hudson/plugins/git/extensions/impl/MessageExclusionTest.java, src/test/java/hudson/plugins/git/extensions/impl/PathRestrictionTest.java, src/test/java/hudson/plugins/git/extensions/impl/PreBuildMergeTest.java, src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitSCMSourceTest.java, src/test/java/jenkins/plugins/git/GitStepTest.java
Making more progress on code cleanups but keeping PRs not too large. Will comment on parts that may have functional changes
=> Cleanup some deprecated code and TODOs

README.adoc
Minor addition to the documentation.
=> Add info about the Repository Browser to the doc

src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java, src/test/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnlyTest.java, src/test/java/hudson/plugins/git/extensions/impl/LogHandler.java, src/test/java/hudson/plugins/git/extensions/impl/SparseCheckoutPathsTest.java
Add tests to support dead code removal from SparseCheckoutPaths.
=> Add tests for SparseCheckoutPaths, remove dead code

src/main/resources/hudson/plugins/git/UserRemoteConfig/help-url.html
Include the "path" phrase specifically since the Jenkins tutorials use that technique and others may use the technique when they are not using agents to perform builds.
Using a path is a mistake when agents are performing the build, since Git is already well equipped to transmit changes efficiently over the network.  Using a path to access a remote file system is likely to be much less efficient than using the remote communications protocols that are already part of git.
=> [JENKINS-64019] Rephrase repository help

README.adoc
Reader wants the script to work and does not care about the history of the script.
=> Better describe the BuildData workaround

pom.xml
- Remove unnecessary hamcrest-core exclusion
- Remove unnecessary commons-lang3 exclusion
- Remove unnecessary git-tag-message exclusion of git
- Remove unnecessary jsoup exclusion
- Remove unnecessary commons-net exclusion
- Add comments on exclusions
- Update parameterized trigger 2.36 as opt. dep
=> Reduce exclusions in pom file

src/main/java/hudson/plugins/git/util/Build.java, src/test/java/hudson/plugins/git/AbstractGitProject.java, src/test/java/hudson/plugins/git/AbstractGitTestCase.java, src/test/java/hudson/plugins/git/GitChangeSetPluginHistoryTest.java, src/test/java/hudson/plugins/git/GitChangeSetSimpleTest.java, src/test/java/hudson/plugins/git/GitChangeSetTest.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/GitTagActionTest.java, src/test/java/hudson/plugins/git/util/BuildTest.java
- Remove test code for Jenkins before 2.222.1
- Fix imports in a few test files
- Add Override annotation to a test class
- Remove unread fields from test
- Remove dead GitTagActionTest code
- Add tests for the Build object
=> Improve tests

src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/util/AncestryBuildChooserTest.java
Replacing some unnecessary usages of Guava with their native Java Platform equivalents.
=> Reduce usages of Guava

src/main/java/hudson/plugins/git/GitSCM.java, src/main/java/hudson/plugins/git/SubmoduleCombinator.java, src/main/java/hudson/plugins/git/util/BuildData.java, src/main/java/hudson/plugins/git/util/CommitTimeComparator.java, src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java, src/main/java/hudson/plugins/git/util/InverseBuildChooser.java, src/main/java/jenkins/plugins/git/GitSCMFileSystem.java, src/main/java/jenkins/plugins/git/GitUsernamePasswordBinding.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/util/AncestryBuildChooserTest.java, src/test/java/hudson/plugins/git/util/CommitTimeComparatorTest.java
Minor refactoring and removed unused imports
=> Minor refactoring and removed unused imports

pom.xml
=> Use parent pom 4.30

.github/labeler.yml, .github/workflows/labeler.yml
Automate the labeling of pull requests based on changes to certain files.
=> Automate some pull request labeling

src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java, src/test/java/hudson/plugins/git/GitPublisherTest.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/browser/GitLabWorkflowTest.java, src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionWorkflowTest.java, src/test/java/hudson/plugins/git/extensions/impl/CloneOptionHonorRefSpecTest.java, src/test/java/jenkins/plugins/git/GitStepTest.java, src/test/java/jenkins/plugins/git/GitToolChooserTest.java
https://github.com/jenkinsci/jenkins/pull/6060 inspired this PR
=> Simplify test harness assertions

src/main/resources/hudson/plugins/git/GitPublisher/config.jelly, src/main/resources/hudson/plugins/git/UserRemoteConfig/config.groovy, src/main/resources/hudson/plugins/git/extensions/impl/SparseCheckoutPath/config.jelly
See https://github.com/jenkinsci/jenkins/pull/5923#issuecomment-1008165794
Fully compatible I assume it predates the core tag but haven't looked into it
=> More forward compatiblity with form modernisation

README.adoc, pom.xml
Add more examples of checkout scm to the plugin documentation.
=> Add checkout scm examples

src/main/java/hudson/plugins/git/GitStatus.java, src/test/java/hudson/plugins/git/GitStatusTest.java
Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.
Just an idea to improve discoverability of the documentation, as it seems that several persons were reporting the correction as a bug: e.g. https://issues.jenkins.io/browse/JENKINS-69208 or https://issues.jenkins.io/browse/JENKINS-69231.
Feel free to not merge it if you do not like it.
=> Add link for the access token requirement

pom.xml, src/test/java/hudson/plugins/git/CheckoutStepSnippetizerTest.java, src/test/java/hudson/plugins/git/GitStepSnippetizerTest.java, src/test/java/hudson/plugins/git/browser/GitRepositoryBrowserTest.java
- Add git step snippet tests
- Use round trip assertion in git step test
- Remove unused import
- Sort pom entries
- Test workflow snippet generation for checkout step
=> add snippetizer tests

Jenkinsfile
Coverage reported by first build and only Linux
=> Use JDK 11 for coverage reporting

src/main/java/hudson/plugins/git/GitChangeLogParser.java, src/main/java/hudson/plugins/git/RemoteConfigConverter.java, src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java, src/main/java/hudson/plugins/git/browser/ViewGitWeb.java, src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java, src/test/java/hudson/plugins/git/AbstractGitRepository.java, src/test/java/hudson/plugins/git/GitChangeSetTest.java, src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java, src/test/java/hudson/plugins/git/GitHooksTest.java, src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/SCMTriggerTest.java, src/test/java/hudson/plugins/git/browser/GitBlitRepositoryBrowserTest.java, src/test/java/jenkins/plugins/git/CliGitCommand.java
See self-review for description of changes.
=> Miscellaneous low-risk code cleanup

src/main/java/hudson/plugins/git/GitChangeLogParser.java
Sorry for the multiple PRs, but caught these mistakes in #1399 that I didn't want to let slide. Explanation in self-review.
=> Fixups to #1399

src/main/java/hudson/plugins/git/GitStatus.java
Using https://github.com/jenkinsci/jenkins/pull/2866.
=> Ignore `notifyCommit` requests to disabled Pipeline jobs

src/test/java/hudson/plugins/git/GitSCMTest.java, src/test/java/hudson/plugins/git/SubmoduleConfigTest.java
Update assertion in the tests
Add content to the repository so that the test has something to checkout.
Update submodule test to match with implementation.
=> Enable missing tests

src/test/java/hudson/plugins/git/Security2478Test.java
The test condition does not require an agent so there is no benefit to declaring the name of a specific agent.  Any agent is sufficient for this test.
=> Accept test run on any agent

pom.xml, src/test/java/hudson/plugins/git/FIPSModeUrlCheckTest.java, src/test/java/jenkins/plugins/git/FIPSModeSCMSourceTest.java
- **Use RealJenkinsRule**
- **Rewrite tests using RealJenkinsRule**
=> [JENKINS-73568] rewrite the tests using RealJenkinsRule so test doesn't need to be skipped depending on Jenkins core version"

pom.xml
Inactive for more than 3 years
Confirmed plugin compiles with changes to pom file.
=> Remove mramonleon as a plugin maintainer

pom.xml
Plugin BOM now includes the necessary versions.  Rely on plugin BOM versions instead of maintaining them separately in this pom file.
Confirmed versions match with `mvn help:effective-pom` before and after this change.
Confirmed that automated tests pass.
=> Remove unnecessary version declarations

README.adoc
Detailed documentation of the strengths and weaknesses of git hooks is already included in the documentation.  The example configuration was missing.  Example configuration shows the default values.
Confirmed that my controller successfully uses configuration as code as described.
=> Add gitHooks to configuration as code example

src/main/resources/jenkins/plugins/git/GitStep/help.html
- Link to the documentation of the checkout step so that users of the `git` step can click the link for more information
- Better introduction sentence
- Use more modern branch name in example
Confirmed that added hyperlinks are valid.  Confirmed that the links work as expected and the page renders as expected.
=> Improve git step documentation

README.adoc, images/scarf.js
Second attempt at a tracking pixel to see documentation usage.
None.  Rely on interactive test.
=> Add a tracking pixel with JavaScript
