- src/main/resources/hudson/plugins/git/GitChangeSetList/digest.jelly
- src/main/resources/hudson/plugins/git/GitChangeSetList/index.jelly
- src/main/resources/hudson/plugins/git/GitSCM/project-changes.jelly
This var should not be escaped either UI markup will be broken with enabled github-plugin.
> Fix f297338702395e53f2f4db8d9070de15bc770890

- src/main/resources/hudson/plugins/git/BranchSpec/help-name.html
This is a follow up to https://issues.jenkins-ci.org/browse/JENKINS-27115
It is undocumented that jenkins will trim anything found before a slash plus the slash otherwise.
> Add help text about trimming branch names before slashes

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitTagAction.java
- src/main/java/hudson/plugins/git/extensions/impl/PruneStaleBranch.java
- src/main/java/hudson/plugins/git/util/BuildData.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
For team using a topic-branch workflow, BuildData is an always growing Map of (legacy) branches, copied from build to build. This enhancement to `PruneStaleBranch` removes obsolete entries from current BuildData object based on existing branches on remote repositori(es)
@reviewbybees
> [JENKINS-19022] purge deleted branches from BuildData

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
When polling with a parametrized branchpec, use the default value of the param, instead of the value from the last build
> [JENKINS-27349] Fix polling for parametrized branchspec

- src/main/java/hudson/plugins/git/GitStatus.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
Allows to pass additional parameters to the jobs triggered via the notifyCommit URL, see https://issues.jenkins-ci.org/browse/JENKINS-27902 for more details
> [JENKINS-27902] Allow to pass additional request parameter for notifyCommit

- src/main/java/hudson/plugins/git/GitSCM.java
As remote polling relies all remote(s) HEADs returned by `git ls-remote` and on BranchSpec#matches we can poll without workspace even when multiple branches are setup, including when wildcards are set.
> Can poll without workspace

- src/main/java/hudson/plugins/git/GitChangeSet.java
parent may be null when shallow clone is used
> [FIX JENKINS-28290] prevent ArrayIndexOutOfBoundException

- pom.xml
I noticed that the current combination of core and matrix plugin in
pom.xml causes errors like the one I'm attaching below. This prevents
"mvn hpi:run" from working correctly --- you get errors when you try to
configure a freestyle job.
I forgot the intricate details of matrix-plugin security fix that
resulted in botched 1.4.1, but, I believe matrix-plugin 1.4.1 only works
correctly with a specific version of the core.
This combination works, though it is not the only combination that
works. I hope this is still OK enough for Mark, as 1.580 is still old
enough LTS release.
Stack trace:
```
May 21, 2015 4:23:36 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=hudson.plugins.git.GitPublisher$NoteToPush$DescriptorImpl, …
```
> Using the version that makes "mvn hpi:run" work.

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/BuildChooser.java
introduce `prepareWorkingTree` for BuildChooser to run some specific working copy setup
in preference for some hack inside `getCandidateRevisions` (that we expect to be idempotent)
Main difference is `prepareWorkingTree` will be ran on matrix axes builds, while `getCandidateRevisions` is only ran on matrix head build, then same revision used on all axes.
@reviewbybees
> New method for BuildChooser to manipulate working copy before the build

- src/main/java/hudson/plugins/git/extensions/impl/PathRestriction.java
- src/test/java/hudson/plugins/git/extensions/impl/PathRestrictionTest.java
Previously when using a whitelist and no paths matched the logged
message was 'Found only excluded paths: '.  Instead give a specific
log message about the whitelist.
Also adds tests for PathRestriction to verify basic behavior.
> improve logging and tests for include/exclude regions

- src/test/java/hudson/plugins/git/AbstractGitProject.java
- src/test/java/hudson/plugins/git/AbstractGitRepository.java
- src/test/java/hudson/plugins/git/GitChangeLogParserTest.java
- src/test/java/hudson/plugins/git/GitChangeSetBasicTest.java
- src/test/java/hudson/plugins/git/GitChangeSetEmptyTest.java
- src/test/java/hudson/plugins/git/GitChangeSetEuroTest.java
- src/test/java/hudson/plugins/git/GitChangeSetSimpleTest.java
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
- src/test/java/hudson/plugins/git/GitChangeSetUtil.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/MultipleSCMTest.java
- src/test/java/hudson/plugins/git/RevisionParameterActionTest.java
- src/test/java/hudson/plugins/git/SCMTriggerTest.java
- src/test/java/hudson/plugins/git/TestBranchSpec.java
- src/test/java/hudson/plugins/git/browser/BitbucketWebTest.java
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
- src/test/java/hudson/plugins/git/browser/GitListTest.java
- src/test/java/hudson/plugins/git/browser/GitWebTest.java
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
- src/test/java/hudson/plugins/git/browser/GitoriousWebTest.java
- src/test/java/hudson/plugins/git/browser/KilnGitTest.java
- src/test/java/hudson/plugins/git/browser/RedmineWebTest.java
- src/test/java/hudson/plugins/git/browser/RhodeCodeTest.java
- src/test/java/hudson/plugins/git/browser/ViewGitWebTest.java
- src/test/java/hudson/plugins/git/util/AncestryBuildChooserTest.java
- src/test/java/hudson/plugins/git/util/BuildDataTest.java
- src/test/java/hudson/plugins/git/util/CommitTimeComparatorTest.java
- src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java
Switch most of the tests from JUnit 3 to JUnit 4.  For most tests, the conversion is simple and no performance improvement is detected.
Several of the tests were using HudsonTestCase (JUnit 3) or JenkinsRule (JUnit 4) when it was not needed.  That caused those tests to run longer than necessary.  Changing the tests to JUnit 4 allows the use of the WithoutJenkins annotation for those tests which are inside a JenkinsRule based test, but don't actually need a Jenkins instance.
The largest (and longest) tests still need to be converted from JUnit 3 to JUnit 4.  That will take more time, so I wanted to have this set of proposed changes reviewed by @ndeloof or @kohsuke in case I've missed something important while trying to reduce test execution time.
> Reduce test time with @WithoutJenkins and switch to JUnit 4

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
I was able to reproduce JENKINS-29066 using github.com/ndeloof/oki-docki-demo as a repository. JGit does return /ref/pull/1/merge as a candidate revision during polling, which is ignored by BuildChooser when looking for revisions to build, resulting in an infinite build loop.
This commit do ensure polling do only consider the configured refspecs. Probably need to also review the BuildChooser extension point to ensure it uses the same logic to avoid such issues
> [JENKINS-29066] potential fix

- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/help-noTags.html
- src/test/java/hudson/plugins/git/TestGitRepo.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionNoTagsTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionShallowDefaultTagsTest.java
As discussed in [JENKINS-14572](https://issues.jenkins-ci.org/browse/JENKINS-14572), fetching all tags is the git plugin's default behaviour - even when making shallow clones using the appropriate advanced clone behaviour.
I've added a check box "Do not fetch tags" to the advanced clone behaviours. This way a user can explicitly override the default.
> [JENKINS-14572] Add "Do not fetch tags" advanced clone option

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/SCMTriggerTest.java
https://issues.jenkins-ci.org/browse/JENKINS-29796
> [JENKINS-29796] Multiple refspecs should be matched using OR, not AND

- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java
This bug occurs when there are multiple matching tags on the same commit.
The existing logic removed the tipCandidate if the commit was already visited.
If there are two revisions on the same commit, the following happens:
The first run places itself in the tipCandidates and marks the commit as visited.
The second run (via the second revision) then places the same commit with another
revision in the tipCandidates but removes it right after because the commit is
already marked as visited.
This patch skips this misbehavior and just keeps the the first revision of a commit.
> Fix a bug where the tip filtering removes all tipCandidates

- src/main/resources/hudson/plugins/git/extensions/impl/CheckoutOption/help-timeout.html
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/help-timeout.html
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/help-timeout.html
It took us some trial and error to make this work, hopefully it will be much easier with the updated help.
> Improvements to online help regarding default global git operation timeout.

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/Build.java
- src/main/java/hudson/plugins/git/util/BuildData.java
[JENKINS-29326](https://issues.jenkins-ci.org/browse/JENKINS-29326)
Added equals methods to BuildData and Build, and check if we already
have an equivalent BuildData on a build before we add it, the git tag
action and changelog, so that we avoid duplicate records of all these things.
NOTE - this probably still needs some tests, most likely to end up in workflow-multibranch.
cc @reviewbybees
> [JENKINS-29326] Don't add duplicate BuildData

- src/main/java/hudson/plugins/git/GitChangeLogParser.java
- src/test/java/hudson/plugins/git/browser/BitbucketWebTest.java
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
- src/test/java/hudson/plugins/git/browser/GitListTest.java
- src/test/java/hudson/plugins/git/browser/GitWebTest.java
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
- src/test/java/hudson/plugins/git/browser/GitoriousWebTest.java
- src/test/java/hudson/plugins/git/browser/KilnGitTest.java
- src/test/java/hudson/plugins/git/browser/RedmineWebTest.java
- src/test/java/hudson/plugins/git/browser/RhodeCodeTest.java
- src/test/java/hudson/plugins/git/browser/ViewGitWebTest.java
When tests are run in a directory with spaces, they will fail the file lookup because the way URL encodes spaces.  I modified the tests to decode the filename before it tries to open the file.
@reviewbybees
> Fix FileNotFound when running tests in directory with spaces

- pom.xml
- src/main/java/hudson/plugins/git/GitPublisher.java
Previously this operation was forbidden in versions of Git CLI < 1.9.0
(see http://stackoverflow.com/q/6900103 for more details).
Now this operation will succeed using newer client version, but it will
fail when using an old version due to
https://github.com/jenkinsci/git-client-plugin/pull/192
> JENKINS-31108 Allow publishing from shallow clone

- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
In one deployment we found that users are confused about the fact that you have to select Microsoft TFS 2013 ... when in fact some 2015 release is installed.
The format of these versions is the same and as such I think it would be useful to change to the generic terms implemented in this PR.
> Updated display name of TFS browser

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/extensions/impl/LocalBranch.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
Maven SCM support for branches relies on the local branch name being the
same as the remote branch name.  Tools such as the Maven release plugin
will push changes using the same local and remote branch names as
explained at https://maven.apache.org/scm/git.html
Ex. git push pushUrl currentBranch:currentBranch
To facilitate this requirement, LocalBranch values of "**" or null will
result in using the remote branch name.
> LocalBranch "**" checks out to local branch using remote branch name.

- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
This updates the label as discussed in https://github.com/jenkinsci/git-plugin/pull/382
It also fixes the test and removes the trap of using a string twice by introducing a static.
Here is what it looks like:
Functionality in terms of links is not changed. 
I tested this on a local jenkins server just for rendering as well as a large deployment with TFS.
I did NOT test this with VSTS since I dont have an account or repo. @olivierdagenais mentioned that he would test this against VSTS.
@MarkEWaite sorry this did not come in time for the release you just cut. Potentially there are issues with the TFS browser since the two strings are different in the current release.
> TFS repository browser relabel and fix

- src/main/java/hudson/plugins/git/util/BuildData.java
https://github.com/jenkinsci/git-plugin/commit/336c1787c7b967e4220c4d459092397fda29892a by @MarkEWaite purported to merely be reverting https://github.com/jenkinsci/git-plugin/commit/c1872d038cc2f584bafbc375744deb54a1dbe316 but in fact it also deleted an unrelated method introduced in https://github.com/jenkinsci/git-plugin/pull/372. Thus the tested added in https://github.com/jenkinsci/workflow-plugin/pull/271 passes against 2.4.1, starts failing against 2.4.2, and is fixed by this patch.
@reviewbybees esp. @abayer
> [JENKINS-29326] Restore lost BuildData.equals override

- src/test/java/hudson/plugins/git/util/BuildDataTest.java
`remoteUrls` is a `Set`, which unless guaranteed by the specific implementation (which is not the case here) does not provide a specific iteration order, so the test cannot depend on it.
@reviewbybees
> Fix `BuildDataTest#testAddRemoteUrl`

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
[Tip](http://stackoverflow.com/a/2848147/12916)
#227 was translating `feature/*/private` to `\Qfeature/\E\Q/private\E` rather than `\Qfeature/\E.*\Q/private\E` as you would expect.
@reviewbybees esp. @Vlatombe
> AbstractGitSCMSource.getPattern bug

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
File.mkdirs() returns false when it fails to create the directories and even when they already exist.
> fix logging "Failed mkdirs of /var/jenkins_home/caches" when the directory already exists

- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/main/java/hudson/plugins/git/browser/GitList.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GithubWeb.java
- src/main/java/hudson/plugins/git/browser/GogsGit.java
- src/main/java/hudson/plugins/git/browser/KilnGit.java
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
- src/test/java/hudson/plugins/git/browser/GogsGitTest.java
Hello,
these commits add support for gogs (https://gogs.io), also they fix the diff links for current Gitlab versions. I assume 8.0 introduced the change, but I only verified this with 8.0... the change might actually have happened earlier.
Also, shouldnt the default version be increased to a supported version? I already modified the Tests so this change could be done easily
> Support for browsing  gogs and gitlab >= 8.0

- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
The previous default 7.11 is not even available anymore.
Should the version field be missing, a recent installation
is a more sensible default.
Additionally disable some broken tests
(double for a version number is not a good idea)
I am not aware of any singificant drawbacks,
and using a gitlab browser without a version happens
easily from pipeline scripts.
> Set default Gitlab Version to current release

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
Useful for `SCMRevision` implementations to override `toString` for logging purposes.
@reviewbybees
> Added SCMRevisionImpl.toString

- src/main/resources/hudson/plugins/git/ChangelogToBranchOptions/config.jelly
- src/main/resources/hudson/plugins/git/GitPublisher/config.jelly
- src/main/resources/hudson/plugins/git/GitSCM/config.jelly
- src/main/resources/hudson/plugins/git/UserMergeOptions/config.jelly
As demonstrated in https://github.com/jenkinsci/workflow-cps-plugin/pull/7, newer versions of HtmlUnit (which the 2.x plugin POM will pick up; cf. #390) will go berserk if they encounter a `<script>` directly inside `<table>` (i.e., between `<tr>`s). Always keep script inside `<td>` if you need it. This patch allows some `configRoundtrip` calls to succeed when using `GitSCM`.
In this case, the `encodeAllInputs` function seems to have not been used since 2.0: 61bd032828366df80589dd2f2aa22f0709c8915a and 2d37646c7fbac1687779ad62ffd4f1a8b0aae304 deleted some usages but not the function itself. Anyway modern form binding does not require plugins to write JavaScript hacks like this. Just use `field` attributes, `FormValidation` with `@QueryParameter` and `@RelativePath`.
@reviewbybees
> Deleting obsolete encodeAllInputs function

- src/main/java/hudson/plugins/git/GitChangeSet.java
If the user email was set improperly (in this case it was sent as just '@'), string split returns a null or 0 length array, which we then index improperly.
> Fix case of invalid user email

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
Steps to reproduce:
1. create a job and add git scm, with two remotes:
/source/repo1.git
/source/repo2.git
2. set branch to commit SHA1 from one of the two repos
3. build
Expected: Successful build
Actual: Failed build with error: 
`ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.`
> Fix for error when job is configured with multiple remotes and branch spec is set to commit SHA1

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/java/jenkins/plugins/git/GitStep.java
use `project.getEnvironment()` to ensure all environment contributors get involved and can populate environment for polling or checking git URL
> Dont rely on System.getEnv()

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/resources/jenkins/plugins/git/GitSCMSource/config-detail.jelly
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTrivialTest.java
This can be useful for some jobs for multi-branch projects (such as literate plugin and multi-branch project plugin).
> Add ability to configure git tool, repository browser, and additional behaviours for literate/multi-branch projects.

- src/main/resources/hudson/plugins/git/BranchSpec/help-name.html
- src/test/java/hudson/plugins/git/BranchSpecTest.java
Additional help when 'Branch Specifier' question mark button
clicked in jenkins job configuration ([JENKINS-36141](https://issues.jenkins-ci.org/browse/JENKINS-36141)).
- Renamed `TestBranchSpec.java` test file to
`BranchSpecTest.java` to conform to junit test naming
conventions and also to be enable intellij to recognize and run
this file as a junit test file.
- Added additional branch specifier test that shows how to
exclude multiple branches from build
> [JENKINS-36141] Add regex branch specifier help

- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
https://github.com/jenkinsci/git-plugin/pull/170 introduced a call to a deprecated method, which https://github.com/jenkinsci/git-plugin/commit/3d67ef2019cb8d1bb639575744a94ccea949a55c copied. Breaks encapsulation: the extension should be using its own configuration, not going back to the owning SCM to look itself up.
@reviewbybees
> Pointless to call the deprecated GitSCM.getUserMergeOptions when we have the options field

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitChangeSetList/digest.jelly
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
Buglet noticed while testing https://github.com/jenkinsci/jenkins/pull/2371.
@reviewbybees
> guessBrowser fix to recognize more GitHub URLs

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTrivialTest.java
Fixes binary compatibility issue introduced in https://github.com/jenkinsci/git-plugin/pull/350
https://issues.jenkins-ci.org/browse/JENKINS-36419
@MarkEWaite @reviewbybees @aheritier
> [FIXED JENKINS-36419] - Resolve Binary compatibility issue in 2.5.1

- src/main/java/hudson/plugins/git/extensions/impl/CheckoutOption.java
- src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionWorkflowTest.java
Previously implemented a deprecated version of decorateCheckoutCommand
in CheckoutOption but called the non-deprecated version.  That caused
the job's checkout timeout setting to be ignored.
> [JENKINS-22547] Honor checkout timeout setting

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/java/jenkins/plugins/git/GitStep.java
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/help-honorRefspec.html
- src/test/java/hudson/plugins/git/GitSCMTest.java
The decision if the refspec should be honored during clone is now
part of the CloneOption additional behaviour.  The user can control
the setting per job, and the default setting remains compatible with
the git plugin 2.5.0 (and prior) cloning of all references initially,
then later honoring the refspec in other operations.
Prior to git plugin 2.5.1, JENKINS-31393 caused the user provided
refspec to be ignored during the initial clone. It was honored in
later fetch operations, but not in the first clone. That meant the
initial clone had to fetch all the branches and their references from
the remote repository, even if those branches were later ignored due
to the refspec.
The fix for JENKINS-31393 exposed JENKINS-36507 which indicates that
the Gerrit Plugin assumes all references are …
> [JENKINS-36507] Move refspec control of initial clone into CloneOption

- pom.xml
- src/main/resources/hudson/plugins/git/browser/GogsGit/config.jelly
The gogs browser pull request was missing the required config.jelly file.  This adds that file
> [Fix JENKINS-37066] gogs config edit fails after save

- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
Needed for https://github.com/jenkinsci/workflow-cps-plugin/pull/12 to work well with multibranch, where the branch project is view-only but you may still want to work with configuration forms. The symptom is that _Credentials_ pulldowns are empty even when there are valid credentials available for the branch project.
> Check EXTENDED_READ, not CONFIGURE, on a context

- pom.xml
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java
Fix for [JENKINS-33983](https://issues.jenkins-ci.org/browse/JENKINS-33983).
A correct  git client (for either selected git tool installation or global default installation) is now created when fetching git heads instead of always using jGit.
> [JENKINS-33983] Using correct git installation when fetching heads

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
[JENKINS-37482](https://issues.jenkins-ci.org/browse/JENKINS-37482)
@reviewbybees
> [JENKINS-37482] Make the cache directory, not just its parent

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
Fixes a mistake in #350: if you are configuring some extensions, like clean before checkout for example, you still want to ensure that
```groovy
node {
checkout scm
}
```
in a multibranch Pipeline project checks out the same revision as `Jenkinsfile` itself.
@reviewbybees
> Fixed mixture of nonempty extensions with SpecificRevisionBuildChooser

- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
A NPE is not checked into PreBuildMerge.decorateRevisionToBuild
@reviewbybees
> [JENKINS-34369] protect against a NPE form GitSCM.getBuildData

- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/test/java/hudson/plugins/git/UserRemoteConfigTest.java
[JENKINS-38048](https://issues.jenkins-ci.org/browse/JENKINS-38048)
> [JENKINS-38048] Permit credentialsId dropdowns to be used from a global configuration screen

- src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java
- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/help-parentCredentials.html
Extend the advanced submodules behavior plugin to support additional
change of enabling "submodulesUseParentCreds" feature. This is a new
feature that enables the simple method of allowing submodules to use
their parent repository credentials instead of having to provide
individual credentials per each submodule URL.
This request depends on the feature being available in the git-client plugin, but I'm not quite sure how to indicate that in the maven file here.
> git-plugin: support use of parent credentials in submodules

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/test/java/hudson/plugins/git/GitChangeSetBasicTest.java
- src/test/java/hudson/plugins/git/GitChangeSetUtil.java
Mostly needed to avoid https://issues.jenkins-ci.org/browse/JENKINS-39694
> API to get author or committer email without having to call getAuthor()

- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-excludedRegions.html
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-includedRegions.html
Found user that didn't found how to make regexp. Updating help to reference real docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/git-plugin/451)
> reference real pattern docs in help file

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
Fixes a critical bug in #455 encountered during integration testing.
Might need a backport to a different branch, I do not follow that stuff.
> [JENKINS-40382] GitSCMFileSystem mistakes

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Build will fail with an exit code of 128.
This code fails on a machine where those values aren't set.
For instance, in CI. Especially in Docker containers who will always be starting fresh where this hasn't been set IN the image itself.
Thanks @jglick @stephenc looking at recent Git history apparently, and @MarkEWaite obviously :)
How to reproduce/understand:
```
docker run -it debian bash
root@66e2fc4d8ab5:/# apt-get update > /dev/null && apt-get install -y git > /dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@66e2fc4d8ab5:/# git init
Initialized empty Git repository in /.git/
root@66e2fc4d8ab5:/# touch file
root@66e2fc4d8ab5:/# git add file
root@66e2fc4d8ab5:/# git commit --message=init
*** Please tell me who you are.
Run
git config --global …
```
> Sets a user.name & user.email on the new repo

- pom.xml
- src/main/java/hudson/plugins/git/GitStatus.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
See [JENKINS-41812](https://issues.jenkins-ci.org/browse/JENKINS-41812)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/27
@reviewbybees
> [FIXED JENKINS-41812] Expose event origin to listeners

- src/main/java/hudson/plugins/git/GitSCM.java
[JENKINS-19022](https://issues.jenkins-ci.org/browse/JENKINS-19022)
Not a fix for the problem—that would probably involve deprecating `BuildData` in favor of using `SCMRevisionState` properly, which has been proposed but seen as too scary to take on—but at least a way for users to _discover_ which problem they are suffering from (and offer a workaround), rather than simply seeing Jenkins get progressively slower with no explanation.
A somewhat better workaround would use something like [`POSTHyperlinkNote`](https://github.com/jenkinsci/workflow-support-plugin/blob/eb031e04d6e314d1cae8b73ff8b15da9a9370c0d/src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/POSTHyperlinkNote.java) to offer to actually correct the problem, at least for this `Run`. (AFAICT it suffices to clean up …
> [JENKINS-19022] Print a warning to the build log when the job seems to be in trouble due to buildsByBranchName bloat

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/resources/jenkins/plugins/git/GitSCMSource/config-detail.jelly
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
Allow to set custom remote name and refspec in the advanced options of a
git source
> [JENKINS-40908] GitSCMSource: support custom remote and refspec

- pom.xml
- src/test/java/hudson/plugins/git/GitSCMTest.java
Include test dependencies to fix PCT for Jenkins 2.32.2 (running tests with jenkins.version=2.32.2).
Also specify the project will use a parameter.
@reviewbybees @MarkEWaite
> Fix PCT for 2.32.2

- src/main/java/hudson/plugins/git/extensions/impl/GitLFSPull.java
- src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionTest.java
This is a refactoring of @matthauck's changes from jenkinsci/git-plugin#414.  This PR depends on jenkinsci/git-client-plugin#232, which explains the changes in more detail.
> [JENKINS-35687] Add simple git lfs support

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
Noticed in `workflow-aggregator-plugin/demo` that `build` was printing a bunch of messages during initial branch indexing, which do not belong in the master log.
In the longer term, I think `SCMFileSystem.Builder` methods need to accept `TaskListener`.
> Reduce chattiness

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/BuildData.java
- src/main/resources/hudson/plugins/git/util/BuildData/index.jelly
- Also fix side-panel on BuildData
- Also make it possible to access the multiple BuildData actions
See [JENKINS-35475](https://issues.jenkins-ci.org/browse/JENKINS-35475)
@reviewbybees
> [FIXED JENKINS-35475] Relax build data present check to allow for different remote names

- src/main/java/hudson/plugins/git/util/BuildData.java
- src/test/java/hudson/plugins/git/util/BuildDataTest.java
BuildData sometimes is unnecessarily duplicated due to trivial differences within the BuildData structure.  This provides tests to show some of those differences, and uses URI.normalize() to attempt to reduce those differences.
@stephenc, since you wrote the earlier code, I'd like your review before I merge.
> Normalize BuildData URL comparisons to reduce duplication

- pom.xml
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitRemoteHeadRefAction.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
See [JENKINS-40834](https://issues.jenkins-ci.org/browse/JENKINS-40834)
Downstream of https://github.com/jenkinsci/git-client-plugin/pull/236
Uses a hack for JGit to get the primary branch information prior to JGit implementing [bug 514052](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514052)
When the remote server is Git 1.8.4 or earlier, will use the strategy for identification of the primary branch that Git 1.8.4 and earlier used (i.e. match by hash and prefer `master` if there are multiple matches)
@reviewbybees
> [JENKINS-40834] Report the primary branch

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/hudson/plugins/git/AbstractGitTestCase.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/TestGitRepo.java
These were easy cases because CredentialsProvider.track() arguments were available in the method where credentials were added.
There are still cases where credentials are not tracked correctly by the plugin.  Credential checks from the job definition page are not currently tracked.  Other contexts (like pipeline) may also not be tracked by these changes.
I've resolved the issue shown in the attached output (circled in red) in 588d8984.  The earlier code was using the project that was available in the GitSCM object.  I changed it to use project.lastBuild() instead.  The tests in the credentials plugin were a great guide to understand and resolve my mistake.
> [JENKINS-38827] Track credentials use

- src/main/java/hudson/plugins/git/GitSCM.java
Git parameters plugin etected a null pointer exception when it was used before the first run of a job.
[JENKINS-44087](https://issues.jenkins-ci.org/browse/JENKINS-44087) describes the testing that has been performed.  I've checked it interactively, Boguslaw has checked it interactively.
@reviewbybees
> [JENKINS-44087] Only track project credentials if last build exists

- src/main/java/hudson/plugins/git/UserRemoteConfig.java
Credential tracking is intended to track relevant and valuable use of
the credential, not something as simple as using that credential in a
form validation.
Form validation is valuable for the user experience of the
administrator, but it is not valuable enough to track the credential
use in validating the form.
Requesting @reviewbybees and by @stephenc to confirm that I've 
correctly understood the vision for credential tracking.
> JENKINS-44640 - Fix NPE checking legacy git SCM URL

- src/main/java/hudson/plugins/git/GitChangeSet.java
See [this thread dump](https://gist.githubusercontent.com/rtyler/b4cfc39b3f4c1a04a5eccfed33919c43/raw/8dbeee9bc3e8fb16c6f7962c319dc95384a84f2c/20170531-170749.236.txt) for example.
Picks up https://github.com/jenkinsci/jenkins/commit/49d10a9034b280b5e59535519c3f0d12d96c9f2d where available, bypassing `User.FullNameIdResolver` and thus `getAll`.
@reviewbybees
> Call User.getById when available

- pom.xml
Arguably we should bump to a newer version, but proposing just the minimal change to pick up https://github.com/jenkinsci/parameterized-trigger-plugin/commit/440065d3c5e86fff9955338ef3a22abf0bfba0ea
@reviewbybees
> It is 6 years since the version range dependency was removed from parameterized trigger

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
Reverts #498 and demonstrates what I suppose is the expected behavior in a test, which otherwise fails (when given `-Djenkins.version=1.651.3` to active the reflective code). I have a hard time following exactly what the existing `testFindOrCreateUser` demonstrated, but it seemed to be testing `createAccountBasedOnEmail` mode, which is not on by default.
@reviewbybees
> Reverting #498 as it broke association of users to commits by fullName

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitSCM/buildEnv.groovy
- src/main/resources/hudson/plugins/git/GitSCM/buildEnv.properties
Supplies data to https://github.com/jenkinsci/workflow-scm-step-plugin/pull/18 or, indeed, to `env-vars.html/` displayed for freestyle projects when you configure a shell step. How could this have been forgotten for so many years, when the Subversion plugin has it?
@reviewbybees
> [JENKINS-26100] Supply GitSCM/buildEnv

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/BuildChooser.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
I was investigating the NPE stacktrace reported back in 2014, and it seems it is not possible anymore. Though I have added some API annotations to make the case explicitly verifyable in FindBugs. This change does not close [JENKINS-22593](https://issues.jenkins-ci.org/browse/JENKINS-22593).
Original stacktrace:
```
[poll] Last Built Revision: Revision 3026d9d56bccb4c335f8ceb97f93d093fffec68f (origin/ticket.8.sort-challenge-descriptions)
Fetching changes from the remote Git repositories
Fetching upstream changes from https://github.com/jpschewe/fll-sw.git
Polling for changes in
ERROR: Failed to record SCM polling
java.lang.NullPointerException
at hudson.plugins.git.util.InverseBuildChooser.getCandidateRevisions(InverseBuildChooser.java:45)
at …
```
> [JENKINS-22593] - Annotate BuildChooser#getCandidateRevisions() and the related code

- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
The given_filesystem_when_askingChangesSinceNewRevision_then_changesArePopulatedButEmpty
test had a confusing mix of xxx261 and xxx260 variables that were
referring to tags which sometimes did not match the name of the variable.
Makes the names consistent rather than risk confusing the reader of the
test.
Other tests referred to a GitSCMFileSystem instance as "instance" when
it was then used as a file system reference to a specific commit.
Changed the name to be clearer where it was referring.
Preparing to remove the requirement that tests require all tags and
all history in the working directory.  Optimizations in git plugin
3.4.0 remove that assumption (and its resulting waste of time and
disc space).
> Fix typos in GitSCMFileSystemTest naming

- pom.xml
- src/main/java/hudson/plugins/git/GitChangeSet.java
<exclude>org.apache.ant:ant</exclude>
<exclude>org.jenkins-ci:annotation-indexer</exclude>
<exclude>org.objenesis:objenesis</exclude>
> Use parent pom 2.32, with a few exclusions

- pom.xml
- src/main/java/jenkins/plugins/git/MergeWithGitSCMExtension.java
See [JENKINS-45771](https://issues.jenkins-ci.org/browse/JENKINS-45771)
Downstream of https://github.com/jenkinsci/git-client-plugin/pull/255
With the update to git-client we can now fix the shallow clone issue on merge with
Will require downstream PRs in GitHub Branch Source, Bitbucket Branch Source and Gitea to switch to this implementation of MergeWithGitSCMExtension
@reviewbybees
> [FIXED JENKINS-45771] Consolidate the MergeWithGitSCMExtension into git plugin

- src/main/java/jenkins/plugins/git/GitSCMSource.java
The method GitSCMSource.DescriptorImpl#doFillCredentialsIdItems
expects the parameter 'context' to be an SCMSourceOwner which breaks
the ability to add a global library at the level of a folder with the
modern SCM implementation. Changing the parameter type from
SCMSourceOwner to Item solves the issue.
> [JENKINS-44271] doFillcredentialsId to look for Item not SCMSourceOwner.

- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
By adding the required PreBuildMerge overrides, it will enable the to extend the class for use as a Trait.
Please see MR https://github.com/jenkinsci/git-plugin/pull/513 for further information.
@stephenc
> Added required overrides to PreBuildMerge extension

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
Minor change to allow downstream plugins to access repository cache in a synchronous manner with appropriate locks.
This is necessary for enabling efficient and hopefully Jenkins-accurate git read/write in blueocean
> Expose `invoke` method & required interface for downstream plugins

- pom.xml
* Removes one of the upper bound exclusions by updating to structs 1.10
* Depends on the recommended credentials plugin version
* Use latest bridge method annotation
@reviewbybees 
Does not remove the powermock / mockito exclusion.
> Use latest dependencies

- src/main/java/hudson/plugins/git/GitStatus.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
[JENKINS-46929](https://issues.jenkins-ci.org/browse/JENKINS-46929)
I changed `GitStatus#doNotifyCommit` to only add up to 10 "Triggered" headers (which contain URLs to downstream projects for which polling or builds have been scheduled by this commit) to its response. This should prevent `java.io.IOException: Response header too large` exceptions when a repository is used in a large number of projects.
@reviewbybees
> [JENKINS-46929] Limit number of projects added to response headers

- src/main/java/hudson/plugins/git/GitSCM.java
The SHA1 being logged may not yet exist in the repository until after the checkout
> [JENKINS-45729] - Move print commit message after checkout

- README.md
- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
- src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java
- src/test/java/hudson/plugins/git/extensions/impl/PreBuildMergeTest.java
This fixes a buggy behavior where BuildData from the previous Run is
used instead, which corrupts build history.
> [Fixed JENKINS-44037] Add a new `BuildData` action if PreBuildMerge fails

- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
Some Windows file systems only track time on 2 second intervals.
Test failures on Windows machines have shown a 1 second offset between
the allowed value and the actual value.
Rather than have a flaky test, increase the offset to cover that
interesting tracking of file system time stamps on Windows.
> Allow up to 4 second time offset in Windows file system

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/traits/TagDiscoveryTrait.java
The previous code worked, but was a hack and not the way I had intended this to be implemented.
Of course I forgot to pay attention to my own design!
@reviewbybees
> Fix tag category enablement

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
> These two operations do not actually need the local repository cache

- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
If you pass the merge parameter as following:
Merge Before Build:
Name of repository : refs/remotes/origin
Branch to merge to : ${BRANCH_NAME}
Merge Strategy: default
Fast-forward mode: --ff
Here BRANCH_NAME is a String Parameter.
Then the output printed in console is something like:
Merging Revision 54f103b61f0b3504503f4990204f8dec8ea612ea (refs/remotes/origin/sample) to refs/remotes/origin/master, UserMergeOptions{mergeRemote='refs/remotes/origin', mergeTarget=**'${BRANCH_NAME}'**, mergeStrategy='default', fastForwardMode='--ff'}
With this Pull Request , the output is correct as the object is resolved correctly:
Merging Revision 54f103b61f0b3504503f4990204f8dec8ea612ea (refs/remotes/origin/sample) to refs/remotes/origin/master, UserMergeOptions{mergeRemote='refs/remotes/origin', …
> Resolving UserMergeOptions Object

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMTelescope.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
Note: I have tested this against a prototype implementation for https://git-wip-us.apache.org/repos/asf
@reviewbybees
> [JENKINS-47526] Provide an API to allow an AbstractGitSCMSource to work at a distance from the repository rather than requiring a local checkout

- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/help-noTags.html
See [JENKINS-45822](https://issues.jenkins-ci.org/browse/JENKINS-45822)
With this change, Advanced Clone Behaviours UI now looks like this:
Which should make it clear that this will fetch tags. This is a UI change as
> 'Do not fetch tags [ ]' == 'Fetch tags [x]'
The configuration on disk remains the same, the constructor remains the same, the default configuration remains the same... we just change how the boolean option is described and displayed.
@reviewbybees
> [FIXED JENKINS-45822] Swap semantics of 'Do not fetch tags' to 'Fetch tags'

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
The revision argument to TelescopingSCMProbe is annotated as @NonNull,
so the method that passes it to TelescopingSCMProbe should also be
annotated @NonNull.
To see the findbugs warning before this change:
mvn clean -Dtest=KilnGitTest install
@stephenc please review
> Annotate Probe.create(head, @NonNull revision)

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
See [JENKINS-47629](https://issues.jenkins-ci.org/browse/JENKINS-47629)
A noddy fix IIUC
> [FIXED JENKINS-47629] Forgot to apply the credentials in the short-cut

- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
- src/test/java/hudson/plugins/git/extensions/impl/SubmoduleOptionTest.java
Since these commands can fail due to the same reason as git checkout,
(too many concurrent accesses to the git server, for example), we need
to throw an exception caught by the retry loop. Based on inspection, it
appears that the best choice to catch is GitException, since that's what
is thrown by the launchCommand flow that calls the git submodule
command.
> git: throw IOException around submodule update failures

- pom.xml
- src/main/java/hudson/plugins/git/SubmoduleCombinator.java
- src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java
Includes a minor code cleanup as well.
> Update parent pom

- pom.xml
Not supported to use parent pom 3.0 with old Jenkins versions like 1.625.
Since git plugin will be moving to Jenkins 2.60 in the near future, there is no reason to use an unsupported configuration prior to the move to Jenkin 2.60.
This reverts commit a924bb3be0016e7974fb92aa27575eb9333631b5.
> Revert "Use parent pom 3.0 - latest update"

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
See [JENKINS-48061](https://issues.jenkins-ci.org/browse/JENKINS-48061) 
Supercedes #557
This is only a partial fix, the two additional ignored test cases are required for the full fix
> [JENKINS-48061] Partial fix for the easy case of non-head revision in history of branch

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMBrowserTest.java
The plugin has a repository browser guesser if a repository browser is not selected.  Previously, that guesser was limited to a subset of github URLs.
This pull request broadens the types of github URLs which will be recognized and adds bitbucket.org and gitlab.com as possible guesses.
Repository browser guessing is only useful for those repository hosting services which have a well-known host name, like github.com, bitbucket.org, and gitlab.com.  Internally hosted GitHub enterprise, or Bitbucket, or GitLab will still need to specify the repository browser, as will other browser types.
I intentionally chose the simpler implementation rather than implementing this using an abstract GitRepositoryBrowserDescriptor.  Since the number of public git repository browsers supported by the plugin …
> Allow repository guessing for bitbucket and gitlab

- pom.xml
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionTest.java
- src/test/java/hudson/plugins/git/util/GitUtilsTest.java
[JENKINS-45477](https://issues.jenkins-ci.org/browse/JENKINS-45447) reports that checkout of a freestyle  job with a wildcard in the branch name is dramatically slower than earlier releases.  Many other cases which use the advanced branch selection mechanism show the same performance problem.
[31fedce9c](https://github.com/jenkinsci/git-plugin/commit/31fedce9c41c9006c886835e03c9fe825d49aba6) commit added tag checks to the evaluation loop for branch names.  Unfortunately, tag evaluation needs both the tag name and the SHA1 of the commit identified by the tag.  The implementation used revParse() to compute that SHA1.  With many tags in the repository (bug report example was 60,000 tags), the checkout time was significant.
I found that even the number of tags in the git plugin repository …
> [JENKINS-45477] improve checkout & poll perf with many tags

- src/test/java/hudson/plugins/git/GitPublisherTest.java
Most non-Windows execution environments define the LOGNAME environment
variable.  When running the Jenkins Dockerfile-slim, it does not appear
to define that environment variable on the master.  Rather than create
complicated searching for another environment variable whose value is
valid as a branch name, we will skip this test if LOGNAME is not set.
LOGNAME is set in enough contexts (like ci.jenkins.io and developer
desktop machines and other test environments) that it is not a good use of
time to embed additional logic into the test for a relatively rare case.
Skip the test if the environment won't support the test.
> Skip LOGNAME dependent test if LOGNAME not defined

- src/main/java/hudson/plugins/git/GitSCM.java
Recommended by Jenkins javadoc since 1.583.
No reason to serialize MasterComputer through remoting when we're already allowing FilePath through remoting and FilePath.localChannel is the recommended replacement for MasterComputer.localChannel.
@reviewbybees
> Use FilePath.localChannel instead of MasterComputer

- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
Tests running in a continuous integration job from a private forked repo may fail because the job itself does not have access to the private fork during its execution.  The checkout step of the job uses the credentials for the private forked repo, but (correctly) does not allow the job
access to those credentials.
Found this issue while fixing SECURITY-723 - Unauthenticated user information disclosure.
The fetch is only performed if the required tags are not already found in the repository.
What types of changes does your code introduce? _Put an `x` in the …
> Fetch tags from public repo for GitSCMFileSystemTest

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
Useful in conjunction with https://github.com/jenkinsci/scm-api-plugin/pull/52.
> [JENKINS-50777] Exporting AbstractGitSCMSource.SCMRevisionImpl.hash

- src/main/java/hudson/plugins/git/UserMergeOptions.java
- src/main/resources/hudson/plugins/git/UserMergeOptions/config.jelly
Broke **Pipeline Syntax** for **Merge before build**. Replaces #392 by @martinda more simply and I guess compatibly—there is no change to the behavior of the existing constructor, nor any change to settings format.
> [JENKINS-34070] Fixing UserMergeOptions.mergeStrategy databinding

- src/main/resources/hudson/plugins/git/GitSCM/config.jelly
Since someone said 'multibranch pipeline projects seem unaffected', I checked multibranch pipeline and found [the code](https://github.com/ikikko/git-plugin/blob/git-3.8.0/src/main/resources/jenkins/plugins/git/traits/GitBrowserSCMSourceTrait/config.jelly#L28). Checking the code above and [listScmBrowsers tag](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/lib/hudson/listScmBrowsers.jelly#L35), I fixed and it worked fine.
Since this is a very small and UI fix, I haven't added tests / documentation.
> [JENKINS-36451] Set scm instance for showing current browser

- essentials.yml
- pom.xml
* Pick up https://github.com/jenkinsci/jenkins/pull/3428 in ATH builds to avoid timeouts.
* Avoid entropy-based timeouts in functional tests. (ported from #582)
> Stabilizing tests

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitStatus.java
- src/main/java/hudson/plugins/git/GitTagAction.java
- src/main/java/hudson/plugins/git/util/BuildChooserDescriptor.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/java/jenkins/plugins/git/traits/GitBrowserSCMSourceTrait.java
There are tests which call methods that rely on a valid Jenkins instance, but the test is being called outside a JenkinsRule.  Thus there is not a valid Jenkins instance.  Rather than alter behavior of those tests, suppress the findbugs warning for the Jenkins.getInstance() reference.
Problem is visible with:
mvn clean -Djenkins.version=2.60.1 -Dtest=StashTest test findbugs:findbugs
> Suppress findbugs warnings from Jenkins 2.60 builds

- src/main/java/hudson/plugins/git/BranchSpec.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitStatus.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
Rebased and simplified version of #436 which was a rebase of #369
> Notify commit branches with slashes

- essentials.yml
Cherry picks a change from the master branch for use on the stable-3.9 branch
> Use Jenkins 2.122 for acceptance tests

- Jenkinsfile
- pom.xml
* Use git client plugin 3.0.0-beta3
* Update test dependencies which don't introduce upper bounds dependency conflicts
> Update git client and test dependencies

- src/main/resources/hudson/plugins/git/extensions/impl/AuthorInChangelog/help.html
- src/main/resources/hudson/plugins/git/extensions/impl/ChangelogToBranch/help.html
Git plugin 3.9.0 removed the requirement that the "Author in Changelog" extension and the "Changelog to Branch" extension must use a workspace for polling.  The online help was not updated with that change.  This fixes the online help.
See 04152e98a19da6c43658a22c3f3340a26ac2fb49 for "Author in Changelog".
See 9331e03cd06577f824103d170fbd2131b0395bd6 for "Changelog to Branch".
> Remove 'requires workspace' from two help messages

- README.md
Submit a README improvement as a low-cost technique to launch a build on ci.jenkins.io.
> Add coverage reporting instructions to README

- src/main/java/jenkins/plugins/git/traits/BranchDiscoveryTrait.java
- src/main/java/jenkins/plugins/git/traits/TagDiscoveryTrait.java
When configuring multibranch pipelines without blueocean installed, the Git SCM source for branch discovery and tag discovery works fine.  However, when installing blue ocean it includes dependencies which cause a conflict in the DSL.  The conflicting plugins are:
- cloudbees-bitbucket-branch-source
- github-branch-source
The exception experienced when using Job DSL to call on the branch discovery trait or tag discovery trait is the following.
```
ERROR: Found multiple extensions which provide method branchDiscoveryTrait with arguments []: [[com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait, jenkins.plugins.git.traits.BranchDiscoveryTrait, org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait]]
```
See also:
- [JENKINS-45504][JENKINS-45504] Add `@Symbol` annotations …
> [JENKINS-45504] Add discovery symbol to branch and tag trait

- README.md
Describe the stable-x.y branch naming in the README and trigger a build on ci.jenkins.io.
The CI job has been unstable.  This pull request is a stability check.
> Add stable-x.y branch description to README

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
> [JENKINS-52754] - GitBranchSource should consult with GitTools node-specific tool installers

- Jenkinsfile
Tests are not running reliably in local or remote environments currently.  Rather than distract with failures to investigate, return to not running those tests.
Hope to restore them later and make them regular contributors to the plugin tests.
> Disable acceptance test harness and plugin compatibility tests

- src/test/java/hudson/plugins/git/AbstractGitProject.java
- src/test/java/hudson/plugins/git/AbstractGitTestCase.java
- src/test/java/hudson/plugins/git/GitChangeLogParserTest.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/browser/BitbucketWebTest.java
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
- src/test/java/hudson/plugins/git/browser/GitListTest.java
- src/test/java/hudson/plugins/git/browser/GitWebTest.java
- src/test/java/hudson/plugins/git/browser/GithubWebTest.java
- src/test/java/hudson/plugins/git/browser/GitoriousWebTest.java
- src/test/java/hudson/plugins/git/browser/GogsGitTest.java
- src/test/java/hudson/plugins/git/browser/KilnGitTest.java
- src/test/java/hudson/plugins/git/browser/RedmineWebTest.java
- src/test/java/hudson/plugins/git/browser/RhodeCodeTest.java
- src/test/java/hudson/plugins/git/browser/ViewGitWebTest.java
- src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java
- src/test/java/hudson/plugins/git/util/CandidateRevisionsTest.java
- src/test/java/hudson/plugins/git/util/CommitTimeComparatorTest.java
- src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java
- src/test/java/jenkins/plugins/git/CliGitCommand.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Now `mvn javadoc:test-javadoc` runs without any errors.
Changes
* remove Javadocs that don't provide useful information
* add missing descriptions to make Javadoc valid
* convert Javadoc to normal comment where possible
Points that don't apply
> Fix Javadoc for tests

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Amends e6476c472492e5aebc5fa959e3c4345bacd4f256, which broke one of the features of `GitSampleRepoRule`: that if CLI `git` (which the rule requires) is not installed, the test is marked skipped rather than failed. Noticed a test failure in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/78 of the form
```
[ERROR] slashyBranches(io.jenkins.plugins.artifact_manager_jclouds.s3.JCloudsArtifactManagerTest)  Time elapsed: 1.187 s  <<< ERROR!
java.io.IOException: Cannot run program "git" (in directory "."): error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at hudson.Proc$LocalProc.<init>(Proc.java:249)
at hudson.Proc$LocalProc.<init>(Proc.java:218)
at hudson.Launcher$LocalLauncher.launch(Launcher.java:929)
at …
```
> Probe git-version before attempting checkGlobalConfig

- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
When in the ui forms of "Advanced clone behaviours" and "Advanced sub-modules behaviours" the "Shallow clone depth" field is left empty, it is now persisted and shown correctly as absent value and not as 0.
This pull request depends on pull request #610.
> [JENKINS-53050] Fix empty "depth" parameter handling for shallow cloning

- src/main/java/hudson/plugins/git/GitSCM.java
This exception can occur if the repository JGit sees does, for whatever reason, not correspond to the repository Git sees.
For instance, JGit does not support git-worktree, so it will report that it could not find the object Jenkins was looking for.
This change allows git-plugin to work with git-worktree again.
Fixes JENKINS-53725
- I don't see a good way to reproduce this issue in a unit test. Also, the catch clause for `InterruptedException` is also not covered by a unit test, so I followed that example
- There was an unrelated warning, probably due to me …
> Catch and print MissingObjectException

- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/main/resources/hudson/plugins/git/browser/GitLab/help-repoUrl.html
- src/main/resources/hudson/plugins/git/browser/GitLab/help-url.html
- src/main/resources/hudson/plugins/git/browser/GitLab/help-version.html
- src/test/java/hudson/plugins/git/browser/GitLabTest.java
- src/test/java/hudson/plugins/git/browser/GitLabWorkflowTest.java
I was a bit annoyed to always specify the GitLab version whenever setting up a GitLab browser, where the GitLab URL format hasn't changed since GitLab 8.0 (which was released September 2015).
Another minor nitpick: Since the types for the version were inconsistent between constructor and getter, the Pipeline snippet generator created non-working snippets, this is also fixed now.
The change of return type of "getVersion" might be considered a breaking change, but was necessary …
> Make GitLab version optional

- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
Command line git in the git plugin has been configured to truncate on the last word boundary preceding character 73.  That truncation was first implemented in git client plugin 2.0 many years ago.
JGit does not truncate.
This test is intended to confirm that the existing behavior is retained.  New optional behavior is being prepared for git plugin 4.0 based on a global switch that will disable truncation of long commit summaries.
This is a test with no changes to production code.
> Confirm commit summary truncates with CLI git

- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
- src/test/java/jenkins/plugins/git/CliGitCommand.java
Automated tests were failing on newly installed agents because the git user.name and user.email were not configured.  However, the setConfigIfEmpty() function is not smart enough to detect all the cases where values are configured.
Since the most crucial test failure case is when running inside a Jenkins agent, this change leaves the values unmodified unless JENKINS_URL and BUILD_NUMBER environment variables are defined.
Unit tests of the git plugin fail if the user.name and user.email values are not defined.  This code attempts to set values for those configuration items if they are not set.  Unfortunately, the "is not set" test does not detect cases like the one reported in [JENKINS-53732](https://issues.jenkins-ci.org/browse/JENKINS-53732).
Rather than attempt to detect all the cases, …
> [JENKINS-53732] Don't alter git config outside Jenkins

- .gitignore
- pom.xml
- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
- src/main/resources/hudson/plugins/git/GitSCM/global.jelly
- src/test/java/hudson/plugins/git/GitChangeSetBasicTest.java
- src/test/java/hudson/plugins/git/GitChangeSetEuroTest.java
- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
- src/test/java/hudson/plugins/git/GitChangeSetUtil.java
The command line git implementation inside git client plugin 2.0 and later will silently truncate the commit summary at the last word break prior to 73 characters.
The JGit implementation does not truncate the commit summary.
This change adds a global option which will retain the full commit summary in both the command line git implementation and the JGit implementation.
The command line git implementation continues to truncate by default so that behavioral compatibility is retained for existing users of the command line git implementation.
The JGit implementation continues to not truncate by default in the user interface so that behavioral compatibility is retained for existing users of the JGit implementation.
Consumers of the git plugin API that use the previous two argument …
> JENKINS-29977 add option to retain full changelog summary

- src/main/java/hudson/plugins/git/GitSCM.java
The SECURITY-595 security fix for Jenkins core prevents access to the URL /job/<Job Name here>/scm/. That prevents access to …/scm/bySHA1/…. That change breaks this undocumented feature.
Since Git plugin 4.0 is a major release, let's use the major release to remove this unusable API.
If we find a critical need to provide this REST API, it can be reinstated on the Descriptor.  Descriptors are already involved in URL handling and will work out of the box.
> Remove getBySHA1 REST API obsoleted by SECURITY-595

- src/main/java/hudson/plugins/git/GitPublisher.java
The Git Publisher does not depend on the completion of preceding builds so it should not need to monitor BUILD.
> [JENKINS-33238] Do not block builds in Git Publisher

- pom.xml
Rely on the beta6 release of the git client plugin.
> Use git client 3.0.0-beta6

- Jenkinsfile
- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java
This is a simple change that only show a message about the Credential use, basically show if it's used and if so, if it can be found within the Storage. It does not stop the build if the credential is not found.
> JENKINS-30515 Adding messages for credentials use: empty, found and not found

- pom.xml
Command line git 2.20 fixed a long-standing bug in tag fetching.  Previously, a tag which existed locally and remotely would be updated by fetch if the remote changed the tag.  The git team fixed that bug in command line git 2.20 so that the `--force` argument is required to modify a local tag that already exists.
The change has been made in git client plugin 2.7.6 and will be made in git client plugin 3.0.0-beta7.  Until git client plugin 3.0.0-beta7 is released, this relies on the incrementals build to resolve the issue.
This also updates from requiring Jenkins 2.60.3 to now require Jenkins 2.107.3.  That is the new required Jenkins version for git client plugin 3.0.0-beta7 and is a good choice as the minimum Jenkins version for the git plugin as well.  Users running versions older than …
> Fix git scm test on git 2.20 with latest git client

- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
- src/test/java/jenkins/plugins/git/GitSCMSourceTraitsTest.java
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/pimpped_out.xml
This change exposes the `threads` property of the `SubmoduleUpdateCommand` (added in https://github.com/jenkinsci/git-client-plugin/pull/348), which allows for git submodules to be updated in parallel. This can greatly improve cloning/checkout times for repositories which have many submodules.
Do I need to also add support for this property in `GitSCMBackwardCompatibility`? I'm not entirely sure as to the purpose of this class, but as far as I can see, it's for older properties which have been deprecated/moved elsewhere. My understanding is that a new property shouldn't need to touch this file, is that correct?
> [JENKINS-44720] Update submodules in parallel

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitSCM/global.jelly
- src/main/resources/hudson/plugins/git/GitSCM/help-useExistingAccountWithSameEmail.html
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
This option is added in order to try to reduce unnecessary user
creation when user ids in jenkins are not based on email addresses.
It will allow optional search for users based on their mail address
property, assuming a single mail address should match only one user.
This is sort of a common sense implementation allowing to wait for
the implementation of JENKINS-14849, as the actual target, requiring
SecurityRealm plugins to expose the logic to match SCM ids to the
users belonging to the realm.
> [JENKINS-9016] Added an option to search for users based on email attribute

- pom.xml
- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java
- src/test/java/hudson/plugins/git/GitChangeSetTimestampTest.java
- src/test/java/hudson/plugins/git/util/AncestryBuildChooserTest.java
Joda-time was the defacto time implementation for Java 6 and Java 7 due to limitations in the Java date and time classes.  Java 8 provides the java.time package which is based on the design and concepts of Joda-time.  The maintainer of Joda-time recommends that Java 8 users [switch from Joda-time to java.time](https://www.joda.org/joda-time/).  The maintainer says:
> Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.
I would like to have @reviewbybees or by @darxriggs just in case I've missed something in the changes.
> Replace joda time

- pom.xml
Use improvements in parent pom 3.36 to get latest mockito and powermock.
> Update parent pom & use mockito/powermock versions from parent

- src/main/java/hudson/plugins/git/GitTagAction.java
- src/test/java/hudson/plugins/git/GitTagActionTest.java
Tests are imperfect but better than no tests.  The tests are able to run a Freestyle project and create two different tags in the workspace of the project.
The tests are not able to create the tags from the doSubmit method and thus are still unable to assert several important cases.
Fixes for the original security issue (no CSRF protection on Git Tag Action) are included in git plugin 3.9.2.
> Extend GitTagActionTest for more cases

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceRetrieveHeadsTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
Revert "[JENKINS-52754] - GitBranchSource should consult with GitTools node-specific tool installers"
This reverts commit 77967dbb349c8d1df02e4a21e0ff9d9e107e94ee.
This is an intentionally short term fix that reverts the fix for [JENKINS-52754](https://issues.jenkins-ci.org/browse/JENKINS-52754) (GitBranchSource should consult with GitTools node-specific tool installers) in order to resolve the more serious problem of [JENKINS-55827](https://issues.jenkins-ci.org/browse/JENKINS-55827) (local tool definition ignored on agent).
> Fix [JENKINS-55827] - local tool definition ignored on agent

- src/test/java/hudson/plugins/git/GitTagActionTest.java
@romenrg noted that the assertion checks for the last tag namne and if they
are created out of order, then the last tag name may be wrong.
> Assert specific tag creation in sequence

- src/test/java/hudson/plugins/git/GitSCMTest.java
Git client plugin 2.7.6 and later include a fix for the new tag handling behavior of command line git 2.20.  However, we don't want to force users to upgrade to that git client version, so the git plugin depends on an older version.
The older version does not include the CLI git 2.20 tag handling change so it will fail this test.  Rather than fail the test, we exit the test early if it is running with CLI git 2.20 or newer.
> Early exit from tag dependent test if CLI git 2.20+

- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
Only reference build data if not null.
No test written.  I haven't been able to deduce a way to duplicate the bug interactively or programatically.
@jacob-keller, could you review and comment?
> Prevent submodule NPE on null BuildData

- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
Message truncation requires arguments to the 'git whatchanged' command that are only available in command line git 1.8.3 and newer.  Don't run truncation tests with command line git on old command line git versions where the required 'git whatchanged' format argument is not available.
Tests were not running regularly on a "stock" CentOS 6 machine.  That mistake is now fixed. This fixes the test on CentOS 6 by not running tests which are nonsensical on that version of command line git.
> Don't test message truncation with ancient CLI git

- pom.xml
Git client plugin 3.0.0-beta6 releases relied upon a command line git parameter that is not available with git 1.7.1 as included with CentOS 6.  Use git client plugin 3.0.0-beta7 which includes a fix.
Command line git 1.7.1 is not officially supported by the plugin but there is no reason to unnecessarily drop support for the working use cases with git 1.7.1.
Also test with newer version of plugins which are only used in tests.
Also test with latest version of equalsverifier.
> Use git client 3.0.0 beta7

- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
Do not attempt to test truncation on command line git versions older than git 1.8.3 like CentOS 6.
> Skip truncation test on ancient git versions

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/git/util/InverseBuildChooser.java
New commit for https://github.com/jenkinsci/git-plugin/pull/685 which I cannot push directly to.
cc @oleg-nenashev 
Build failure when using JDK 11.0.2:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project git: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/tiste/dev/github/jenkinsci/git-plugin/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
[ERROR]  * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
[ERROR]            ^
[ERROR] /home/tiste/dev/github/jenkinsci/git-plugin/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in …
```
> Replace <tt> by <code> to fix javadoc failure on Java 11

- pom.xml
And address associated errors with `RequireUpperBoundDeps` rule.
Also update parent pom to latest in the go.
This aims at allowing the `git-plugin` to be enabled on Java 11 soon.
With this fix, I get substantially less failures locally (Linux).
On JDK 11.0.2, I get `[ERROR] Tests run: 3885, Failures: 1, Errors: 2, Skipped: 2, Flakes: 1`.
The left issue seems to be around Powermock, which I'm sure I've seen discussed in the past already.
If this is a relatively large or complex …
> Update to workflow-support:3.x for Java 11 compat

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSourceContext.java
- src/main/java/jenkins/plugins/git/traits/PruneStaleBranchTrait.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
When using this [retrieve](https://github.com/jenkinsci/git-plugin/blob/6cdc97e0081276470bb96535e65bd0b4cb195ec9/src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java#L768) entrypoint and attempting to find a Tag with the TagDiscoveryTrait enabled or attempting to find something without the appropriate DiscoveryTrait enabled, a doRetrieve call is processed. These two calls do not prune even if the PruneStaleBranchTrait is present. This code makes these two calls aware of said trait and therefore avoid any tag ref lock exception
This fix is brought about by a heavy use of the Pipeline global library plugin, and while adding the PruneStaleBranchTrait avoids most of the issues caused by:
branch x …
> Make GitSCMSource aware of PruneStaleBranchTrait

- src/test/java/hudson/plugins/git/UserMergeOptionsTest.java
Documents a regression from #580: [JENKINS-51638](https://issues.jenkins-ci.org/browse/JENKINS-51638). Safe to merge as is; if and when I come up with a satisfactory fix, I would amend this PR if is still open, else file a follow-up.
> [JENKINS-51638] Documenting current behaior in a unit test

- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
Git 1.7.0 added the `--delete` flag to push as a way to delete a remote branch.  The `-d` alias for `--delete` was not added until git 2.8.  Use the old argument format since that works with git versions as old as CentOS 6 provides.
If an even older syntax were desired, we could use:
```
git push origin :remote-branch-name-to-delete
```
> Fix AbstractGitSCMSourceTest for git 2.7 and earlier

- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
Users running on CentOS 7 and Red Hat Enterprise Linux 7 will either
need to not enable the prune trait for Pipelines or they will need to
update to a newer version of command line git.
Command line git prune behavior before git 1.9.0 does not handle these
two prune test cases correctly.  Rather than be distracted by failing
tests, acknowledge that the tests are known to fail in that environment.
> Skip 2 prune tests on old CLI git versions

- src/test/java/hudson/plugins/git/GitSCMTest.java
Two tests fail intermittently on stable-3.10 but pass consistently on master branch and on stable-3.9 branch.  Unclear why they are intermittent on stable-3.10 and needs more investigation when time allows.
> Ignore two GitSCMTest cases on stable-3.10

- pom.xml
- src/main/java/hudson/plugins/git/UserMergeOptions.java
- src/test/java/hudson/plugins/git/UserMergeOptionsTest.java
Some users upgrading from prior git plugin versions to git plugin 3.9.x received error messages that their merge strategy value was not recognized.  They had used 'default' as the value instead of 'DEFAULT' and the new code only accepted 'default'.  This code now accepts all case variants of 'default'.
Relies on structs 1.18 for an API enhancement.  Requires Jenkins 2.121.1 or newer.  Backport of #699
> Fix JENKINS-51638 - allow lower case 'default' UserMergeStrategy

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
See evaluation in [JENKINS-54186](https://issues.jenkins-ci.org/browse/JENKINS-54186): this extension has no `@DataBoundConstructor` as it is not intended for static configuration by a user (it is added programmatically by various other features), so it does not need a `BuildChooserDescriptor` either as that would just make it appear in the list of things you could configure when really you cannot. `GitSCMSourceDefaults` and `MergeWithGitSCMExtension` are in the same boat (in that case they are `GitSCMExtension`s rather than `BuildChooser`s) and correctly lack descriptors.
> SpecificRevisionBuildChooser.DescriptorImpl should not exist

- pom.xml
Changes in JDK 11.0.3 break javadoc creation.  The break has been confirmed on Amazon Corretto JDK 11.0.3 and Debian Buster OpenJDK 11.03.  It is expected to be a problem on Oracle JDK 11.0.3 as well.
This disables Javadoc generation on all builds.  It is more important that we compile and test on JDK 11.0.3 than that we generate javadoc.
> Disable javadoc because JDK 11.0.3 broke it

- pom.xml
Jesse Glick fixed the root of my problem with javadoc generation on JDK 11.0.3 with his fix in parent pom 3.43.  Use the fix.
> Fix JDK 11 javadoc with parent pom 3.43

- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/test/java/hudson/plugins/git/util/GitUtilsJenkinsRuleTest.java
Minor test addition to cover more case in GitUtils.  Uses an agent as beginning of agent based tests.
> Improve GitUtils test coverage

- src/test/java/hudson/plugins/git/extensions/impl/PreBuildMergeTest.java
Fix the failure by safeguarding the rare cases where an assertion
depends on an English language message from command line git.
Automated tests should run correctly and completely in multiple locales.  This specific test depends on a specific error or warning message from command line git.  When command line git is localized (as it is now), then the message will likely be different than the English git command.
> [JENKINS-57493] Unit tests fail in German

- src/main/java/jenkins/plugins/git/traits/PruneStaleBranchTrait.java
- src/test/java/jenkins/plugins/git/traits/PruneStaleBranchTraitTest.java
PruneStaleBranchTrait implementation did not handle SCMSource which was not a GitSCMSource.
Added a failing test, then fixed the failing test.
> [JENKINS-57683] Fix class cast exception scanning multibranch pipeline

- src/test/java/hudson/plugins/git/GitSCMTest.java
Minor increase to code coverage in tests, checking a case that has been reported in bug reports as a known behavior.
This specific test addition does not actually perform the build, it only asks the question and confirms the expected result is received.
> Confirm that revision comparison with no predecessor forces a build

- pom.xml
Use the latest parent pom, 3.45.  Also update a few test dependencies to test with their latest releases.
> Use parent pom 3.45

- pom.xml
- src/main/java/hudson/plugins/git/SubmoduleConfig.java
- src/test/java/jenkins/plugins/git/GitJCasCCompatibilityTest.java
- src/test/resources/jenkins/plugins/git/configuration-as-code.yaml
Submodules configuration could not be applied by CasC. Resumes some work done by @fcojfernandez
> [JENKINS-57603] CasC is now able to configure submodules

- pom.xml
Bumps [xmlunit-matchers](https://github.com/xmlunit/xmlunit) from 2.6.2 to 2.6.3.
- [Release notes](https://github.com/xmlunit/xmlunit/releases)
- [Changelog](https://github.com/xmlunit/xmlunit/blob/master/RELEASE_NOTES.md)
- [Commits](https://github.com/xmlunit/xmlunit/compare/v2.6.2...v2.6.3)
> Bump xmlunit-matchers from 2.6.2 to 2.6.3

- pom.xml
Use latest parent pom and test with latest configuration as code plugin.
> Use latest parent pom - 3.47

- pom.xml
Simplify updates from stable-3.10 to master by reducing pom differences between the two branches.
> Reduce pom differences to master branch

- src/main/resources/hudson/plugins/git/GitChangeSetList/digest.jelly
- src/main/resources/hudson/plugins/git/GitChangeSetList/digest_it.properties
- src/main/resources/hudson/plugins/git/GitChangeSetList/index.jelly
Because the fix and issue are trivial I did not create an issue on https://issues.jenkins-ci.org/ to avoid generating unnecessary noise.
Build summary page displays the list of changelog entries with commit message and link to the detailed view. The mentioned links are not correct as they points to a page containing all chaneset details but does not scroll to the matching element because of invalid identifier. This patch fixes the issue and now when clicking on the "details" we will be taken exactly to the matching entry.
> Correct links to changeset details

- pom.xml
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitSCMTelescopeTest.java
#708 fixes JENKINS-43802.  This a backport of the that change to the 3.10 line.  It pulls in JENKINS-52964 and requires scm-api v2.6.3. 
@jglick @MarkEWaite
> Backport pr 708

- pom.xml
- src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java
Plugin compatibility tester detected an error in the automated test definition of a Pipeline job.  Unrecognized extra arguments were included in the userRemoteConfig value in the tests.  Fix the tests by removing those unrecognized extra arguments.
> Fix pipeline syntax errors in test

- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java
- src/main/java/jenkins/plugins/git/traits/SparseCheckoutPathsTrait.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTraitsTest.java
This is simply adding the existing Sparse Checkout extension as a Git SCM Trait to make it configurable From Git SCM Source and Navigator implementations.
> [JENKINS-56189] Add Sparse Checkout SCM trait

- pom.xml
- src/test/java/jenkins/plugins/git/ModernScmTest.java
The fix for [JENKINS-43802](https://issues.jenkins-ci.org/browse/JENKINS-43802) made in git plugin 3.11.0 changes the SCM implementation inside the git plugin to use a newer API.  The API is available in older plugin versions but workflow cps global lib 2.14 changes are needed to allow the git plugin to continue to act as a modern SCM implementation instead of regressing to only be a legacy SCM implementation.
This fix allows git plugin 3.11.0 and later to continue to provide a modern SCM implementation in addition to the legacy SCM implementation by requiring that the Jenkins installation must have workflow cps global lib 2.14 or newer.  Users with older versions of workflow cps global lib will be upgraded to at least 2.14 by this dependency change.
This is a stable-3.x version of pull …
> Fix JENKINS-58964 - Lost modern SCM with older workflow cps global lib

- src/test/java/hudson/plugins/git/BranchSpecTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/UserMergeOptionsTest.java
- src/test/java/jenkins/plugins/git/ModernScmTest.java
Some bug specific tests were missing the Issue annotation.  Add them.
> Add Issue annotations to some existing tests

- pom.xml
- src/test/java/jenkins/plugins/git/GitJCasCCompatibilityTest.java
Adjust expected log string to match JCasC 1.27 logging details level.
In JCasC 1.25, logging in the test was set to 'INFO' and the assertion was testing that the 'INFO' level logging in that version of JCasC was reporting that the submodule configuration contained two empty members. The submodule configuration should not have contained two empty members, but there was a bug in submodule configuration setting. That bug was fixed earlier, but the bug fix did not change the INFO level logging of configuration as code plugin 1.25.
In JCasC 1.27, test logging is set to 'FINER' and the logged statements have changed significantly.  This assertion can now check that specific values from the resource jenkins/plugins/git/configuration-as-code.yaml are correctly reported in the JCasC 1.27 log file. …
> Test with JCasC 1.27

- Jenkinsfile
Have not seen a failure on Windows specific to Java 11.  Since Windows tests run slower and I have fewer Windows machines available, reduce the Windows cases from 3 to 1, testing Java 8 with the default Jenkins
(2.138.1).
Have not seen failures on Linux with the default Jenkins that are not also visible on Windows with default Jenkins.  Test Linux with Java 8 and Java 11 using the recent LTS release.
> Reduce test configurations by 50%

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
JGit 5.x deprecates and removes the getRef method on repositories, replacing it with two methods, findRef and exactRef.  No reason to use the JGit 4.5 method even with JGit 4.5, since the new methods are available.
> Replace JGit 4.5 getRef with findRef or exactRef

- pom.xml
Bumps [checkstyle](https://github.com/checkstyle/checkstyle) from 8.23 to 8.24.
- [Release notes](https://github.com/checkstyle/checkstyle/releases)
- [Commits](https://github.com/checkstyle/checkstyle/compare/checkstyle-8.23...checkstyle-8.24)
> Bump checkstyle from 8.23 to 8.24

- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
Issue raised against 7d59ac5743f41aa0f5a39413ef8d246ab2eca3bf of #748  regarding null checks during form validation where the Jenkins object should never be null so simply using `get()` is a valid operation. Functionally it should behave as before.
> Fix un-needed nullchecks

- pom.xml
Disable the maven source cross reference feature, not used and not needed. Allow next generation warnings plugin to confirm there are 0 maven warnings.
> Disable maven source cross references

- pom.xml
When running the tests the following error was shown for every test that used `JenkinsRule`:
> Error injecting constructor, java.lang.IncompatibleClassChangeError:
> jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser and jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser$DescriptorImpl disagree on InnerClasses attribute
> at jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser$DescriptorImpl.<init>(AbstractGitSCMSource.java:416)
The error was introduced in commit db3e063c59f81d1cc78e77c075e8acd92f7b1b83 when _org.jenkins-ci.plugins:git-tag-message_ was added as dependency. It contains _org.jenkins-ci.plugins:git_ as dependency itself. Therefore 2 versions appeared on the classpath causing trouble.
These tests fail locally but also on …
> [JENKINS-57694] Fix IncompatibleClassChangeError when running tests

- pom.xml
- src/test/java/jenkins/plugins/git/GitJCasCCompatibilityTest.java
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1049
Fix a silly space in the name 🤣
as expected)
> fix space in expected log

- README.md
- pom.xml
Accepts that some documentation is better than no documentation and that imperfect descriptions of extensions are better than no descriptions of extensions.
> Read GitHub for plugins.jenkins.io docs

- README.md
Don't mix markdown and asciidoc
Make the documentation readable by using markdown syntax instead of a flawed mix of asciidoc and markdown.
> Fix the markdown

- src/main/java/hudson/plugins/git/util/BuildChooser.java
**old description**
~~All other `BuildChooser`s already have a `Descriptor`. This missing `Descriptor` was causing an exception when `BuildChooser#getDisplayName()` was called within `GitSCM#compareRemoteRevisionWithImpl()` to log its name.~~
~~The `Descriptor` was once already in place but then removed in commit 75e78800 because the `SpecificRevisionBuildChooser` is not meant to be selectable by a user in the UI.~~
~~The better way (because a `Describable` should have a `Descriptor`) to describe this fact is to overwrite `isApplicable()` to always return `false`.~~
**new description**
There may be `BuildChooser`s that don't have a `Descriptor` because they are not meant to be selectable by a user in the UI. Currently `SpecificRevisionBuildChooser` is such a `BuildChooser`.
This missing …
> [JENKINS-57694] Fix SpecificRevisionBuildChooser#getDisplayName()

- CONTRIBUTING.md
> Fix the markdown syntax error in contribution document

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/extensions/GitSCMExtension.java
Seems run is historically missing in fetch because logic was reused for polling. Trying to pass build context into extension. Hopefully `fetchFrom` is private method and only extension method is affected.
Possibly the other variant could be to call old and new method?..
PoC for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/git-plugin/766)
> [JENKINS-59415] run context for GitSCMExtension

- pom.xml
Bumps [equalsverifier](https://github.com/jqno/equalsverifier) from 3.1.9 to 3.1.10.
- [Release notes](https://github.com/jqno/equalsverifier/releases)
- [Changelog](https://github.com/jqno/equalsverifier/blob/master/CHANGELOG.md)
- [Commits](https://github.com/jqno/equalsverifier/compare/equalsverifier-3.1.9...equalsverifier-3.1.10)
> Bump equalsverifier from 3.1.9 to 3.1.10

- pom.xml
Let the BOM manage the version instead of dependabot.
Test dependency, good to update regularly.
> Use JCasC version from BOM

- pom.xml
- src/main/java/hudson/plugins/git/GitRevisionBuildParameters.java
The git plugin can optionally use the promoted builds plugin. Promoted builds plugin 3.4 replaced the Promotions.getTarget() method with Promotions.getTargetBuild(). Adapt to the API change.
> Depend on promoted builds 3.4

- pom.xml
- src/main/java/hudson/plugins/git/browser/casc/GitLabConfigurator.java
- src/test/java/hudson/plugins/git/browser/casc/GitLabConfiguratorTest.java
- src/test/java/jenkins/plugins/git/BrowsersJCasCCompatibilityTest.java
- src/test/java/jenkins/plugins/git/GitSCMJCasCCompatibilityTest.java
- src/test/java/jenkins/plugins/git/GitToolJCasCCompatibilityTest.java
- src/test/java/jenkins/plugins/git/GlobalLibraryWithLegacyJCasCCompatibilityTest.java
- src/test/java/jenkins/plugins/git/GlobalLibraryWithModernJCasCCompatibilityTest.java
- src/test/resources/jenkins/plugins/git/browsers-casc.yaml
- src/test/resources/jenkins/plugins/git/gitscm-casc.yaml
- src/test/resources/jenkins/plugins/git/global-with-legacy-casc.yaml
- src/test/resources/jenkins/plugins/git/global-with-modern-casc.yaml
- src/test/resources/jenkins/plugins/git/tool-casc.yaml
Git Plugin allows a wide number of configuration possibilities. However, there is only a small test to check the configuration using CasC. This PR adds more tests so the rest of configurations can be tested when they are exported/imported using CasC.
Besides, with the test I found out that the Gitlab browser is not compatible with CasC. This fixes that bug.
The reason:
- Databound constructor is expecting the version as String, so the imported yaml file should similar to
```
unclassified:
globalLibraries:
libraries:
- name: "My Git Lib"
retriever:
legacySCM:
scm:
git:
branches:
- name: "*/master"
browser:
gitLab:
repoUrl: "http://gitlab.com"
version: "1.0"
buildChooser: "default"
doGenerateSubmoduleConfigurations: false
userRemoteConfigs:
- url: "https://git.acmecorp/myGitLib.git"
```
- …
> Configure Gitlab browser with JCasC, add JCasC tests

- pom.xml
- src/main/java/hudson/plugins/git/GitRevisionBuildParameters.java
Reverts jenkinsci/git-plugin#774 so that we do not force users to prematurely install the latest promoted builds plugin.  See [comment](https://github.com/jenkinsci/promoted-builds-plugin/commit/cf1128c914f2d84260c202ce58f6e559384761c6#commitcomment-35537086) on promoted builds [PR 140](https://github.com/jenkinsci/promoted-builds-plugin/pull/140)
> Revert "Depend on promoted builds 3.4"

- pom.xml
Oleg Nenashev has detected issues with promoted builds plugin versions 3.3 and 3.4.  He recommends remaining with 3.2 for now.
> Depend on promoted builds 3.2

- src/main/resources/hudson/plugins/git/BranchSpec/config.groovy
- src/main/resources/hudson/plugins/git/GitSCM/buildEnv.groovy
- src/main/resources/hudson/plugins/git/UserRemoteConfig/config.groovy
- src/main/resources/hudson/plugins/git/extensions/GitSCMExtension/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/BuildChooserSetting/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/ChangelogToBranch/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CheckoutOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/LocalBranch/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/MessageExclusion/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/PreBuildMerge/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/RelativeTargetDirectory/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/ScmName/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/UserExclusion/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/UserIdentity/config.groovy
- src/main/resources/hudson/plugins/git/util/AncestryBuildChooser/config.groovy
- src/main/resources/hudson/plugins/git/util/BuildChooser/config.groovy
- src/main/resources/hudson/plugins/git/util/InverseBuildChooser/config.groovy
- consistently don't use optional semicolons
- consistently use a newline at the end of a file
> Cleanup config Groovy files

- src/main/resources/hudson/plugins/git/BranchSpec/help-name.html
- src/main/resources/hudson/plugins/git/BranchSpec/help-name_ja.html
They may have already been rendered somehow properly before this change in most browsers but the usage was not correct.
- use the `</li>` end tag to make the end of big list items more explicit
- contain `<ul>` elements inside `<li>` elements so that they are correctly part of the list item
Also see https://developer.mozilla.org/docs/Web/HTML/Element/li.
> Improve nested lists in HTML

- pom.xml
Bumps [bom-2.138.x](https://github.com/jenkinsci/bom) from 3 to 4.
- [Release notes](https://github.com/jenkinsci/bom/releases)
- [Commits](https://github.com/jenkinsci/bom/commits)
> Bump bom-2.138.x from 3 to 4

- pom.xml
Setting forkCount to `1C` causes the tests to hang completely on systems with a large number of available CPU cores.  Rather than risk being unable to test on a full range of computers, limit the forkCount to 1.
Eventually it would be best to identify the root causes of the hanging tests, but that's far beyond what I can do now.
> Restrict test to fork a single process

- src/main/resources/jenkins/plugins/git/GitStep/help-branch.html
- src/main/resources/jenkins/plugins/git/GitStep/help-changelog.html
- src/main/resources/jenkins/plugins/git/GitStep/help-credentialsId.html
- src/main/resources/jenkins/plugins/git/GitStep/help-poll.html
- src/main/resources/jenkins/plugins/git/GitStep/help-url.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
This git step is a limited functionality shorthand for a portion of the generic SCM step.
The checkout step is the preferred step for SCM checkout.
The checkout step provides significantly more functionality and can be used in many cases where the git step cannot be used.
> [JENKINS-60267] Document limitations of git step

- src/main/java/hudson/plugins/git/extensions/impl/CleanBeforeCheckout.java
- src/main/java/hudson/plugins/git/extensions/impl/CleanCheckout.java
- src/main/java/jenkins/plugins/git/traits/CleanAfterCheckoutTrait.java
- src/main/java/jenkins/plugins/git/traits/CleanBeforeCheckoutTrait.java
- src/main/resources/hudson/plugins/git/extensions/impl/CleanBeforeCheckout/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CleanBeforeCheckout/help-deleteUntrackedNestedRepositories.html
- src/main/resources/hudson/plugins/git/extensions/impl/CleanCheckout/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CleanCheckout/help-deleteUntrackedNestedRepositories.html
- src/test/java/hudson/plugins/git/extensions/impl/CleanBeforeCheckoutTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CleanCheckoutTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTraitsTest.java
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/cleancheckout_v1_extension.xml
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/cleancheckout_v1_trait.xml
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/cleancheckout_v2_extension.xml
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/cleancheckout_v2_trait.xml
- src/test/resources/jenkins/plugins/git/GitSCMSourceTraitsTest/pimpped_out.xml
[JENKINS-26660](https://issues.jenkins-ci.org/browse/JENKINS-26660) - add UI for cleaning of nested repositories/submodules
This PR exposes functionality created in jenkinsci/git-client-plugin#222 to Jenkins UI so it is possible to actually use it.
#449 attempted to do the same thing but was closed for various reasons.
> [JENKINS-26660] Expose 'cleanSubmodules' functionality to Jenkins UI

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
This bug is detected by AbstractGitSCMSourceTest.when_commits_added_during_discovery_we_do_not_crash to if run against newer JTH.
> Fix repository leak in AbstractGitSCMSource.retrieve

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/RemoteConfigConverter.java
- src/main/java/hudson/plugins/git/SubmoduleConfig.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
On modern JVMs using an empty array is faster and even simpler to use:
https://shipilev.net/blog/2016/arrays-wisdom-ancients/
> Don't use pre-sized arrays on array conversion

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java
These values are never used as the variables are always overwritten.
> Remove unused assignments

- src/test/java/hudson/plugins/git/AbstractGitTestCase.java
- src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
GitSCMTest and GitStatusTest both fail intermittently on ci.jenkins.io Windows computers.  The failures are due to a busy log file or a busy job directory.  The failures are **not** due to busy git files or busy git directories.  I assume some component is holding a file open at that point in the test.
Rather than spend significant time trying to find the component of JenkinsRule that is holding the build log open, it is simpler to use a "sleep" variant in one test and to skip the tests on the ci.jenkins.io Windows computers in the other test.
Tests continue to execute when run by developers.  Tests continue to execute in my Windows and Linux and FreeBSD test environment.
> Avoid cleanup failures in GitStatusTest & GitSCMTest 

- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/main/java/jenkins/plugins/git/GitSCMTelescope.java
Make it clear to callers that getUrl may return null.
Adding an annotation for what I suspect was the cause of [JENKINS-50014](https://issues.jenkins-ci.org/browse/JENKINS-50014). Filed jenkinsci/git-parameter-plugin#83 against that plugin but circling back here to ensure that other plugins can catch this issue with the annotation added.
> [JENKINS-59540] Add annotation to getUrl

- README.adoc
Document the fields and the compromises in the Git Publisher for Freestyle jobs.
I should have asked that the original author of the pull request provide the documentation.
@johannespfeiffer I would appreciate your feedback (even after I've merged it).
> Document Git Publisher and rebase before push

- README.adoc
- pom.xml
- src/main/resources/jenkins/plugins/git/GitStep/help.html
This page is displayed at https://jenkins.io/doc/pipeline/steps/git/. That page has received the most negative reviews of any page on https://jenkins.io/ .  The most frequently requested enhancement for the page is to include examples.  This change includes examples.  
This file is displayed as help for the git step when using the pipeline syntax generator.
A high frequency complaint is that the git step is missing functionality.  That will not change.
The checkout step is the replacement for the git step.  The checkout step provides all the functionality of the git step and all the functionality available from the git plugin. It is more maintainable and better prepared for use in realistic pipelines.
This page also includes strong guidance to use the checkout step.
> [JENKINS-60617] Include git step examples

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
The polling log should print the reason why the GitSCM decides to trigger a build. In that particular case, nothing useful is logged and one can spend a lot of time trying to understand what causes a build.
> [JENKINS-59868] Add information about missing working directory to Polling logs

- src/main/java/hudson/plugins/git/GitSCM.java
Pending an actual fix such as https://github.com/jenkinsci/git-client-plugin/pull/219, we can at least warn users.
Tested against the script from [JENKINS-56076](https://issues.jenkins-ci.org/browse/JENKINS-56076), plus some control cases: running on `master`, running on agent without `container`.
> [JENKINS-30600] Warn in log when DecoratedLauncher is in use

- README.adoc
Include link to new git plugin chat channel.
> Add gitter chat badge to docs

- pom.xml
Use JTH 2.60 instead of 2.57 to resolve test failures and test hangs on multi-core machines.
* See [JENKINS-60574](https://issues.jenkins-ci.org/browse/JENKINS-60754)
* See [JENKINS-60694](https://issues.jenkins-ci.org/browse/JENKINS-60694)
> [JENKINS-60574] Fix InjectedTest hang from JTH 2.57

- pom.xml
Now allowed to run parallel tests on multi-core machines without hanging.
> Use parent pom 3.56 to fix JTH test issue

- pom.xml
- src/main/java/hudson/plugins/git/BranchSpec.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java
- src/main/java/hudson/plugins/git/SubmoduleConfig.java
- src/main/java/hudson/plugins/git/UserMergeOptions.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/java/hudson/plugins/git/extensions/impl/LocalBranch.java
- src/main/java/hudson/plugins/git/extensions/impl/PreBuildMerge.java
- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPath.java
- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java
- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
Pipelines are not allowed to reference plugin fields unless those fields are whitelisted.  Allow plugin access to many fields in the git plugin.
Test automation of this change uses an acceptance test rather than a test included inside this repository. There are suggestions from the community that test automation of a whitelisted method should be feasible, but I didn't want to delay the release of git plugin 4.1.0 for that automation inside the plugin when there is already automation outside the plugin.
See the [acceptance test docker image](https://github.com/MarkEWaite/docker-lfs/tree/lts-with-plugins) and the [acceptance test source code](https://github.com/MarkEWaite/jenkins-bugs/blob/JENKINS-42860/Jenkinsfile) for more details of the test.
If this is a relatively large or complex …
> [JENKINS-42860] Whitelist pipeline safe getters

- pom.xml
Don't use the docs file from the master branch, since it usually contains unreleased content. Special thanks to jenkins.io docs for describing how to do this.
> Use docs from tagged release

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
See https://github.com/jenkinsci/git-plugin/pull/820 for the original discussion related to fixing this particular bug.
See https://github.com/jenkinsci/git-plugin/pull/820#issuecomment-576981707 to understand the fix. 
Since UserRemoteConfig URL can't be null for many reasons, we arrived at the conclusion of improving the error message to 
> Git repository URL 1 is an empty string in job definition. Checkout requires a valid repository URL
> [JENKINS-38608] Report clearly if the Repo URL is empty

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/resources/hudson/plugins/git/Messages.properties
- src/test/java/hudson/plugins/git/UserRemoteConfigRefSpecTest.java
While adding a Git source in the **Source Code Management**, adding an invalid refSpec produces a confusing/complex stack trace upon applying/saving the configuration changes.
Upon discussion on this issue, a good way to inform the user about the invalid refSpec is to check the correctness of the values entered by the user on the fly (Done on the server-side). Hence, a `doCheckRefspec` method has been added to create a form validation logic.
Here is a screenshot of the UI result of the new method:
**Note: The message has been changed to "Specification is invalid"**
> [JENKINS-57660] Addition of a doCheck validation method for invalid refSpec

- README.adoc
For unknown reason, the documentation chapter about "Push notification
from repository" has disappeared. Currently we are forced to retrieve it
via the wayback machine:
https://web.archive.org/web/20190905084011/https://wiki.jenkins.io/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository
> Restore Push notification documentation

- README.adoc
Transition from wiki to GitHub docs did not transfer the notifyCommit documentation.  #835 added the documentation from the wiki to the README.  This refines that documentation.
> Refine the web hook and notify commit docs

- README.adoc
A few sections were not transferred from wiki.jenkins.io when the initial documentation transfer happened.  This pull request migrates the remaining documentation from wiki.jenkins.io into this repository.
> Add docs from wiki

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/extensions/GitSCMExtension.java
- src/main/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnly.java
- src/main/resources/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnly/help.html
- src/test/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnlyTest.java
Add an additional behaviour that disables the multi candidate scheduling.
The default behaviour of the git plugin is to check for new changes and trigger a new build for every tip of every branch. When working with big repositories, high build times and many independent branches, this behaviour leads to an unnecessary high resource consumption.
I tried to get this change into the upstream in #509 . That is over two years ago, was pre 4.0.0 and got the label later. So I'll try it again :)
We're patching this feature in every release since 2,5 years. It would be nice to see it in the official plugin.
> Allow disabling of multi candidate scheduling

- README.adoc
The plugin documentation included several errors and omissions corrected in this pull request.  This corrects:
* Use preferred anchor syntax
* Fix incorrectly placed secondary HTML anchors (id's)
* Remove incorrectly placed word `stash`
* Remove an extraneous parenthesis
* List correct version when change truncation was removed
> Fix various documentation errors

- pom.xml
The jsoup jar file is added to the hpi file as a transitive dependency of the configuration as code test harness.  The git plugin does not deliver the configuration as code test harness and so it should not deliver the dependencies of that test harness either.
We've had issues in the past where other plugins mistakenly depended on a jar file that the git plugin bundled (like joda-time). Better to avoid others from depending on a transitive test dependency by not including the transitive test dependency.
The jsoup jar file was included in git plugin 4.1.0 and 4.1.1.  Earlier versions did not include it.
https://github.com/jenkinsci/git-plugin/pull/814/commits/f3c65cb72548d3ab8ed863d5817624119b199455 added the transitive dependency.
> Exclude jsoup from git plugin jpi packaging

- pom.xml
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
Next version includes SCM file system support for tags.  That change justifies incrementing the minor number.
> Set next version to 4.2.0

- pom.xml
- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/main/resources/hudson/plugins/git/Messages.properties
- src/test/java/hudson/plugins/git/browser/AssemblaWebDoCheckURLTest.java
The earlier **doCheckUrl** methods used to open a connection to validate a particular browser URL but that can be avoided (mostly) by adding some initial checks based on URL syntax validity and domain name match of the particular browser.
This change has been implemented for _AssemblaWeb_, _GitBlitRepositoryBrowser_, _Gitiles_ and _ViewGitWeb._ 
**Note**: A test file has been written for AssemblaWeb class, if it is considered okay then will do the same thing for the other 3 browser classes as well.
> [JENKINS-48625] Restore binding of doCheckUrl methods and add some initial checks

- src/test/java/hudson/plugins/git/extensions/impl/WipeWorkspaceTest.java
The unit test was added in relevance to one the project goals of [Git-Plugin Performance Improvements](https://jenkins.io/projects/gsoc/2020/project-ideas/git-plugin-performance/) which is to improve the code coverage.
I ran the coverage report on IntelliJ and most of the report is not relevant to the test, I have just taken out the relevant part.
> [GSoC] Addition of unit test for WipeWorkspace extension behavior in GitSCM

- src/test/java/hudson/plugins/git/extensions/impl/UserIdentityTest.java
The unit test was added in relevance to one the project goals of [Git-Plugin Performance Improvements](https://jenkins.io/projects/gsoc/2020/project-ideas/git-plugin-performance/) which is to improve the code coverage. 
I ran the coverage report on IntelliJ and most of the report is not relevant to the test, I have just taken out the relevant part.
While writing tests for this class, UserIdentity, I came upon an issue with this extension, namely [JENKINS-46052](https://issues.jenkins-ci.org/browse/JENKINS-46052). 
While UserIdentity sets author _name_ and _email_ in the environment variable, wouldn't it be right to set  the new author name and email in the git.config for that particular repository as well? 
`git config user.name "GIT_AUTHOR_NAME"`
`git config user.email …
> [GSoC] Add UserIdentityTest to improve code coverage in git-plugin 

- src/main/java/hudson/plugins/git/extensions/impl/PruneStaleTag.java
- src/main/java/jenkins/plugins/git/traits/PruneStaleTagTrait.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagTest.java
- src/test/java/org/jenkinsci/plugins/gitclient/TestCliGitAPIImpl.java
I our infrastructure we use pipeline to perform releases. Releases are performed in Maven, Lerna (NodeJS) and fastlane (IOS). All tools requires that release tag does not in the current git repo. When a releases fails for some reason we fix and re-run the process that will fail again because the tag exists locally. This force the DevOps teams manually remove tags from workspaces in Jenkins slaves. The trait in this PR always prune tags that do not exists on remote.
> [JENKINS-40529] Prune tags on fetch

- pom.xml
- src/main/java/hudson/plugins/git/GitChangeLogParser.java
- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/BitbucketWeb.java
- src/main/java/hudson/plugins/git/browser/CGit.java
- src/main/java/hudson/plugins/git/browser/FisheyeGitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/main/java/hudson/plugins/git/browser/GitList.java
- src/main/java/hudson/plugins/git/browser/GitWeb.java
- src/main/java/hudson/plugins/git/browser/GithubWeb.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/GitoriousWeb.java
- src/main/java/hudson/plugins/git/browser/GogsGit.java
- src/main/java/hudson/plugins/git/browser/KilnGit.java
- src/main/java/hudson/plugins/git/browser/Phabricator.java
- src/main/java/hudson/plugins/git/browser/RedmineWeb.java
- src/main/java/hudson/plugins/git/browser/RhodeCode.java
- src/main/java/hudson/plugins/git/browser/Stash.java
- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
- src/main/java/hudson/plugins/git/util/BuildChooser.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/java/jenkins/plugins/git/traits/CleanAfterCheckoutTrait.java
- src/main/java/jenkins/plugins/git/traits/CleanBeforeCheckoutTrait.java
- src/main/java/jenkins/plugins/git/traits/GitSCMExtensionTraitDescriptor.java
- src/test/java/hudson/plugins/git/UserRemoteConfigTest.java
The javax annotations from JSR-305 were never finalized and never will be finalized. The spotbugs team has provided replacements that match with spotbugs usage.
Also updates to spotbugs 4.0.1.
In the spirit of https://github.com/jenkinsci/jenkins/pull/4604
> Replace javax annotations with spotbugs annotations

- src/test/java/hudson/plugins/git/GitStatusCrumbExclusionTest.java
With the security release of yesterday, some tests are no longer passing for the git plugin. As it uses a mock for the crumb filter and we added some logic there, it results in NPE.
By disabling the new security correction for tests only, we prevent the test to fail on recent core version. It does not modify the behavior of the plugin that is safe, it's just the way the test is written that make it fail.
The new system property support was added in 2.204.6 but due to its nature, we can inject it in previous version without issue.
> Adapt the test for recent core

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitTagAction.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
- src/main/java/hudson/plugins/git/extensions/impl/PruneStaleTag.java
- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPath.java
- src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java
- src/main/java/hudson/plugins/git/util/BuildData.java
- src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/main/java/jenkins/plugins/git/GitSCMSourceRequest.java
- src/main/java/jenkins/plugins/git/traits/LocalBranchTrait.java
Recent change introduced a javadoc warning about an undocumented parameter.  This documents the parameter.
Recent change introduced a deeper check from spotbugs.  This resolves many of the spotbugs reports from that deeper check.
> Fix javadoc and spotbugs warnings

- pom.xml
- src/main/resources/hudson/plugins/git/GitPublisher/config.jelly
- src/main/resources/hudson/plugins/git/GitRevisionBuildParameters/config.jelly
- src/main/resources/hudson/plugins/git/GitSCM/global.jelly
- src/main/resources/hudson/plugins/git/extensions/impl/CleanBeforeCheckout/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CleanCheckout/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
<details>
<summary>2.227-SNAPSHOT</summary>
</details>
<details>
<summary>2.138.4</summary>
</details>
You can also test via reverting my revert jenkins core version commit
ref: https://github.com/jenkinsci/jenkins/pull/3895, cc @MarkEWaite @jsoref
> JENKINS-55787 Switch labels from entry to checkbox

- Jenkinsfile
- pom.xml
- src/test/java/hudson/plugins/git/GitStatusCrumbExclusionTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnlyTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
This pull request switches from requiring Jenkins 2.138.4 as minimum version to require Jenkins 2.204.1 as minimum version.  Using a modern version like 2.204.1 includes the trilead-api separation from the Jenkins core and simplifies testing.
User based justification for choosing 2.204.1 as the new minimum version:
* Over 48% of the 240 000 installations of git plugin are running git plugin 4.0.0 or newer.  Over 40 000 git plugin installations are using Jenkins 2.204.2
* Almost 10x more installations of git plugin are on Jenkins 2.204.2 than any other single release
Users that are choosing to stay current with the git plugin are also choosing to stay current with Jenkins releases.  That's a very good thing.  Special thanks to the users for choosing to update to recent releases!
The …
> Require Jenkins 2.204.1

- README.adoc
- src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnlyTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CheckoutOptionWorkflowTest.java
- src/test/java/jenkins/plugins/git/GitStepTest.java
- src/test/java/org/jenkinsci/plugins/gittagmessage/GitTagMessageExtensionTest.java
Jesse Glick noted in a [comment](https://github.com/jenkinsci/bom/pull/110#issuecomment-594782396) that some flaky pipeline tests in other plugins could be resolved by switching from assertLogContains to waitForMessage. Since the git plugin has shown a tendency to flaky tests on Windows, let's use Jesse's recommendation as well.
> Use waitForMessage instead of assertLogContains

- src/main/java/hudson/plugins/git/extensions/impl/PruneStaleTag.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagPipelineTest.java
Add missing getter method required by the pipeline syntax generator.
Add symbol on this extension to render it more readable.
@MarkEWaite I have a doubt in PruneStaleTag.DescriptorImpl.newInstance. For latest code review you suggest to add a boolean to enable/disable this extesion. To do that I added in a previous request a boolean field in the constructor but I realize that to make it true by default I adopt a method that I do not like so much.
Maybe there are 3 way to perform the goal
- Actual way edit the JSON formData of request putting pruneTags as true if not present in the original request (this make true as default unless specified and cover future additional settings for this trait)
- other way is instantiate the extension class like `return new PruneStaleTag(true)`
- add a jelly …
> [JENKINS-61869] Prune tags during fetch shown incorrectly in syntax generator

- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/config.groovy
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
<details>
<summary>Before </summary>
</details>
<details>
<summary>Now: collapsed</summary>
</details>
<details>
<summary>Now: expanded</summary>
</details>
I moved the shallow clone down to the bottom as it didn't look great below the other checkboxes
> JENKINS-61870 Shallow clone UI tweaks

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java
- src/main/java/hudson/plugins/git/util/CommitTimeComparator.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMBuilder.java
A recent settings change increased the number of spotbugs warnings by allowing higher effort and a lower threshold.  Resolve several spotbugs warnings that are easy to resolve.
> Reduce spotbugs warnings

- pom.xml
- src/test/java/hudson/plugins/git/GitStatusTest.java
Use plugin BOM 2.190.x 7 with version numbers preferred from it rather than being maintained inside the pom file.
Aligns with git client plugin.
> Use BOM 2.190.x

- src/main/java/hudson/plugins/git/extensions/impl/PruneStaleTag.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagTest.java
New feature that will be released in git plugin 4.3.0.  I'd like to have better test coverage in new features than we have in existing features.  These tests cover the equals contract, the hashCode implementation, and the toString() implementation.  They do not attempt to cover the missed branches from the tests that were created during development.
> Add more prune stale tags tests

- src/main/resources/hudson/plugins/git/BranchSpec/help-name_ja.html
I applied `s/ワルドカード/ワイルドカード/g`.
* `ワルドカード` is incorrect Japanese phrase.
* `ワイルドカード` is correct. (like [help-name_ja.html#L10](https://github.com/jenkinsci/git-plugin/blob/git-4.2.2/src/main/resources/hudson/plugins/git/BranchSpec/help-name_ja.html#L10) , [#L54](https://github.com/jenkinsci/git-plugin/blob/git-4.2.2/src/main/resources/hudson/plugins/git/BranchSpec/help-name_ja.html#L54) and [#L56](https://github.com/jenkinsci/git-plugin/blob/git-4.2.2/src/main/resources/hudson/plugins/git/BranchSpec/help-name_ja.html#L56) )
I have checked no `ワルドカード` under fixed commit. below:
```
$ git rev-parse HEAD
e533614dd10592695da8c0861ef203900fcdf344
$ git grep -n ワルドカード | wc -l
0
```
Only fix typo
> Fix typo on Japanese translation

- pom.xml
Use parent pom 4.0 for easier maintenance and better spotbugs integration.
> Use pom 4.0

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
> [JENKINS-62183] Allow user with Jenkins.MANAGE to access global config

- src/main/resources/hudson/plugins/git/GitSCM/help-showEntireCommitSummaryInChanges.html
Git plugin 4.0.0 intentionally shows the entire first line of the commit message in the "changes" page, even if that first line is very long. A global compatibility option was included to allow users to revert to the git plugin 3 behavior of truncating the first line message in the "changes" page. Unfortunately, no online help was provided for that new global configuration option.
> Added help page for 'Show the entire commit summary in changes'

- Jenkinsfile
Pipeline library for ci.jenkins.io now includes the cleanup step to prevent incrementals failures due to tainted workspaces.  Remove the ugliness from the Jenkinsfile.
> Temporary cleanup no longer needed in Jenkinsfile

- src/main/java/hudson/plugins/git/GitSCM.java
A user with an older Java version reported that the Java Duration object throws an arthimetic exception because a JGit computed duration in nanoseconds related to file system time stamps is larger than a Java long. I can't explain why the file system on that computer would have a time stamp that causes a Java duration greater than 290 years (2^64 nanoseconds).
Since the printCommitMessageToLog method is a convenience for readers of the build log, failures in printCommitMessageToLog should not fail the build.  Ignore ArithmeticException in addition to ignoring GitException.
> [JENKINS-62710] Ignore arithmetic exception in helper message

- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
File system times need a wider range of allowed values on two tests.  One of the tests fails consistently on OpenBSD, likely due to the precise one second data reporting of OpenBSD file system times and the slow hardware where I'm running it.  One of the tests fails less frequently with a small range error.  The second test now allows an additional 20% on its range for slow file systems.
> Allow wider range of file system times

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
When a Pipeline job that is not a multibranch Pipeline job is defined to use '`*`' as its branch name and is configured with lightweight checkout, it reports a null pointer exception and fails the job.  A branch name '`*`' should be disallowed for Pipeline jobs that are not multibranch Pipeline jobs because a wildcard branch name would cause the job to switch between different branches each time it detects a change on one of the branches in the repository.  Switching branches within a job makes the change history and general user experience confusing for the user.
This has the questionable result that by avoiding the null pointer exception it now allows a Pipeline job that is not a multibranch Pipeline to switch from one branch to another inside the same job.
The technique of using a …
> [JENKINS-57587] Prevent GitSCMFileSystem NPE on '*' branch name

- src/test/java/hudson/plugins/git/GitSCMTest.java
The previous implementation of the test failed when the branch name 'master' is used because the Jenkins job directory name includes the branch name.  This now asserts more precisely on the content of the FETCH_HEAD
file.
As part of the exploration to find the problem, additional assertions have been added to confirm that the correct SHA1 is mentioned in the FETCH_HEAD file.
The previous test implementations would create a new CheckoutCommand with git.checkout() but then did nothing with it.  It created the "foo" branch but did not checkout the "foo" branch.  The commit that was described as "Commit in foo" was a commit to the master branch, not a commit to the foo branch.
The new code creates the branch and then uses the branch for new commits.
> Fix testAvoidRedundantFetchWithHonorRefSpec assertions

- README.adoc
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitSCM/global.jelly
- src/test/java/hudson/plugins/git/GitSCMTest.java
In our company we are using git plugin to checkout git repositories with centrally managed credentials.  Pipeline users should not know which credentials are being used to not give them the opportunity to use this credentials in a withCredentials block and bypass certain 4-eyes principles that are in place.  Therefore we would like to introduce the possibility to add a global option to hide the output of credential usage in the job log.
Not applicable
> [JENKINS-62820] Ability to hide credential usage in job output

- .github/pull_request_template.md
- Jenkinsfile
- README.adoc
- src/main/resources/hudson/plugins/git/GitSCM/help-allowSecondFetch.html
- src/main/resources/hudson/plugins/git/GitSCM/help-gitTool.html
- src/main/resources/hudson/plugins/git/GitSCM/help-hideCredentials.html
- src/main/resources/hudson/plugins/git/UserRemoteConfig/help-credentialsId.html
- src/main/resources/hudson/plugins/git/browser/CGit/help-repoUrl.html
- src/main/resources/hudson/plugins/git/browser/GogsGit/help-repoUrl.html
- src/main/resources/hudson/plugins/git/extensions/impl/GitLFSPull/help.html
- src/test/java/jenkins/plugins/git/GitSCMJCasCCompatibilityTest.java
- src/test/resources/jenkins/plugins/git/gitscm-casc.yaml
Online help is missing for several fields.  The online help is extracted into the jenkins.io pipeline help and is shown to users from inside the Jenkins web pages.
Also updates the pull request template to remind submitters to update documentaiton and online help.
> [JENKINS-62223] Add online help for several fields

- src/main/resources/hudson/plugins/git/GitBranchTokenMacro/help.jelly
- src/main/resources/hudson/plugins/git/GitRevisionTokenMacro/help.jelly
Git plugin token macro help formatting was using an unnecessary heading to prefix the description of token macro parameters.  Other plugins use a definition list to describe the token macro parameters without the unnecessary heading.  Do the same for the git plugin.
> [JENKINS-9346] - Fix token macro help formatting

- Jenkinsfile
Currently there is an unidentifiable issue with using subsetConfiguration as a configurations parameter for the buildPlugin step. 
Simply removing it would ensure incremental builds for the git plugin.
> Remove subsetConfiguration parameter to enable incremental build

- README.adoc
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitSCM/help-globalConfigEmail.html
- src/main/resources/hudson/plugins/git/GitSCM/help-globalConfigName.html
- src/main/resources/hudson/plugins/git/extensions/impl/UserIdentity/help-email.html
- src/main/resources/hudson/plugins/git/extensions/impl/UserIdentity/help-name.html
It took me a while to realize that this plugin, in constrast to its documentation, does *not* alter `user.name` and `user.email`. So I took the additional time to adjust the documentation accordingly.
> Clarify the consequences of setting user.name and user.email

- README.adoc
The documentation doesn't clearly state what the behavior is if you:
1. check out a given revision from a Git repo and
2. set `Checkout to specific local branch` to `**` or blank to get an automatic local branch name
```
16:09:31 Selected Git installation does not exist. Using Default
16:09:31 using credential gh-cred
16:09:31 Cloning the remote Git repository
16:09:32 Cloning repository https://github.com/user/repo.git
16:09:32  > git init /home/build-stage/jenkins/workspace/repo # timeout=10
16:09:32 Fetching upstream changes from https://github.com/user/repo.git
16:09:32  > git --version # timeout=10
16:09:32 using GIT_ASKPASS to set credentials gh-cred
16:09:32  > git fetch --tags --force --progress -- https://github.com/user/repo.git +refs/heads/*:refs/remotes/origin/* # timeout=10 …
```
> JENKINS-63487 Clarifying local branch name for detached checkouts

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitToolChooser.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
The git plugin previously created an empty directory in the $JENKINS_HOME/caches directory for any repository URL that it checked for size. Those empty directories are not likely to use too much disc space, but a large installation that clones many different repositories will have many empty directories in the caches directory.
Provides a new getCacheDir API that returns null if the directory does not already exist.
> [JENKINS-63541] Don't create empty dirs in chooser

- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/GitTagActionTest.java
- src/test/java/hudson/plugins/git/extensions/impl/PathRestrictionTest.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitBranchSCMHeadTest.java
- src/test/java/jenkins/plugins/git/GitSCMBuilderTest.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
The maven surefire plugin reports skipped tests as a WARNING.  That WARNING causes the warnings plugin on ci.jenkins.io to count the skipped test as a warning and display the warning in the job results.
The tests are intentionally skipped so they should not be counted as warnings.  This converts the assertion from a warning to no warning.  The same code is executed as previously, without the maven surefire warning.
The change also converts a few locations to consistently use the same isWindows() function as is used elsewhere in the code.
Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.  If it fixes a bug or resolves a feature request, include a link to the issue.
> Reduce test warning count by not using Assume

- src/test/java/hudson/plugins/git/GitSCMTest.java
Not valuable enough to have it distract from other development.
The test was ignored for the longest time.  That generated a warning in the logs but was not investigated for the root cause of the erratic behavior.  Other fixes are more valuable than being distracted by this.
> Remove the flaky testCustomSCMName

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/GitToolChooser.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
Change the current way to suggest a git implementation, the modifications can be broadly described as:
- Earlier, if the system wants to recommend `jgit` and `jgit` is not available in the system, it used to go for `cli git`. We've realised that that is unnecessary. Now the GitToolChooser would recommend nothing ("NONE") if it wants to recommend `jgit` or `jgitapache` but it is not enabled by the user.
- For a repository size > 5 MiB: if the user enables a node-specific git tool (let's say git-for-windows), earlier the GitToolChooser used to recommend `git` whatever that may be perceived by the system, which is wrong.
Now, it will return the same node-specific git tool, `git-for-windows`.
- For a repository size > 5 MiB: if the user enables `jgit` as a git tool, now the GitToolChooser has …
> [JENKINS-63519] Create a better mechanism to detect node-specific git implementations

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
If a pipeline job defines the checkout scm step without including a remote repository, the job will usually fail in other ways.
A null pointer exception is not a friendly way to show a configuration error to a user.
> [JENKINS-63572] Avoid NPE if remote config is empty

- src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java
- src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java
If a branch that contains a slash is configured as branch to build and local branch behaviour is configured, then two candidate revisions will be found in case remote branch is ahead of local: configured local branch name and branch name with prefix 'refs/remotes/<remote>/'. The first result will be taken, which can be a local or remote branch depending on sha1 of the revisions. This causes a problem that sometimes remote changes are ignored on checkout from SCM. See [JENKINS-37263](https://issues.jenkins-ci.org/browse/JENKINS-37263) for more details.
> [JENKINS-37263] Prefer remote references for checkout

- src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java
- src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java
Use hamcrest assertions for clarity
Spelling fixes for method names
Use consistent white space
> Hamcrest asseertions, more tests, consistent formatting

- src/main/java/hudson/plugins/git/GitSCM.java
It is possible that node running git operation is having memory issues and frequently fail
with a stack trace similar to below. Since printCommitMessageToLog is considered informational
avoid such issues.
09:28:57 java.lang.OutOfMemoryError: Java heap space
09:28:57 Caused: java.io.IOException: Remote call on XXXX failed
09:28:57        at hudson.remoting.Channel.call(Channel.java:1007)
09:28:57        at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInv=
ocationHandler.java:286)
09:28:57        at com.sun.proxy.$Proxy82.withRepository(Unknown Source)
09:28:57        at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withReposi=
tory(RemoteGitImpl.java:237)
09:28:57        at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM=
.java:1347)
09:28:57        at …
> Catch IOException by printCommitMessageToLog

- src/main/java/jenkins/plugins/git/GitToolChooser.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
Extend the cache lookup process to better use the cached copies.
- An in-memory cache that uses a canonical repository URL as its key and stores the repo size
- A lookup method which takes the repository URL, converts it into the canonical form and then finds it in the internal cache
- A cache assignment method which takes the repository URL, converts it to normalized repository URL format, then stores the size of the repository if the size is larger than the size (optionally) stored in that cache entry already
- Look at the internal cache before looking for stored cache in Jenkins.
**Note:** To avoid potential confusion between the GitToolChooser in-memory cache and the Jenkins cache directory, I have used the term `internal-cache` for the in-memory GitToolChooser cache. We could also …
> [JENKINS-63539] Expand repo cache lookup for better size estimates

- src/test/java/hudson/plugins/git/GitSCMTest.java
Git for Windows does not like working with long paths
> Early exit testHideCredentials if Windows long path

- src/main/resources/hudson/plugins/git/GitChangeSetList/index.jelly
- src/main/resources/hudson/plugins/git/GitSCM/project-changes.jelly
Recent change in Jenkins core is now returning the login id for author.toString().  Previously it returned author.getFullName().  Trust that displayName is probably more useful to a person in the user interface.
An automated test to check the content of the changes page for this string was much more work than I was willing to do for this fix.  I confirmed interactively that I could see the problem before this change.  I confirmed interactively that after this change, the problem was no longer visible.
I confirmed that the changes in Jenkins core to [show display names in change list](https://github.com/jenkinsci/jenkins/pull/4943) did not resolve this issue.  The issue is visible in Jenkins 2.258 and is still visible in the pre-release build containing …
> [JENKINS-63744] Show changeset author with displayName, not toString

- .mvn/extensions.xml
- pom.xml
- src/main/java/hudson/plugins/git/ObjectIdConverter.java
Prevents a linkage error against upstream XStream as in https://github.com/jenkinsci/jenkins/pull/4944.
> Use ExtendedHierarchicalStreamReader

- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
- src/test/java/hudson/plugins/git/browser/AssemblaWebDoCheckURLTest.java
The URL validation in the the repository browser settings was too strict and it treats e.g *.corp domains as invalid. To fix this, we have introduced the [DomainValidator](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html) with custom domain names (.corp, .local etc) to allow the possibility of validating urls with such custom local urls as well.
This is a continuation on the great work done in https://github.com/jenkinsci/git-plugin/pull/890 by @sratz and @MarkEWaite .
> [JENKINS-62261] Allow URL validation to accept custom TLDs

- pom.xml
- src/main/java/hudson/plugins/git/GitPublisher.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
The current implementation of the GitToolChooser is not aware of the fact that JGit is not compatible with GitPublisher. To do so:
- Added a new UnsupportedCommand feature which would convey if JGit should be used in
the scenario where Git Publisher is being used
- Instantiated that command within the GitPublisher to pass down that info of compatibility
- Changed the CreateClient API to add UnsupportedCommand as a new parameter
This PR is dependent upon: https://github.com/jenkinsci/git-client-plugin/pull/615
> [JENKINS-63727] GitToolChooser should not recommend JGit if Git Publisher is present

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/GitToolChooser.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
Assert contents of build log in GitPublisherTest
Unclear why the JGit test case is using JGit correctly, logging that the tag has been pushed, yet not detecting the tag in the destination repository and not reporting any exception.
> Add GitPublisher freestyle test

- pom.xml
Needs latest UnsupportedCommand class from git client plugin
> Require git client plugin 3.5.1

- src/main/resources/hudson/plugins/git/GitPublisher/config.jelly
The plugin contains tabular markup on some form elements and that could be a potential conflict with the new tables-to-div changes in the Jenkins core (https://issues.jenkins-ci.org/browse/JENKINS-62437)
> [JENKINS-62905] Git Publisher may be impacted by tables-to-div changes

- src/main/java/hudson/plugins/git/GitRevisionBuildParameters.java
Spotbugs report from the newest version of the promoted builds plugin correctly warns that the target of a promoted build might be null and needs to be checked.  See the output in #975.
> Check target of promoted build is not null

- README.adoc
- src/main/resources/hudson/plugins/git/extensions/impl/UserExclusion/help-excludedUsers.html
Clarify online help that was written in 2010.
> [JENKINS-64149] User exclusion compares strings, not wildcards

- src/main/java/hudson/plugins/git/GitTagAction.java
- src/test/java/hudson/plugins/git/GitTagActionTest.java
Fix a null pointer exception detected during checkout when the branches property is null.
> Avoid NPE in git tag action

- src/main/resources/jenkins/plugins/git/GitStep/help-branch.html
The plugin uses a `checkout` operation rather than `clone`.  The checkout operation is not smart enough to use the default remote branch.  Since the `git` step is not receiving further investment, correct the documentation to accurately describe the implmenentation.
> [JENKINS-64320] Fix git step default branch docs

- pom.xml
- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
The most recent release of commons validator requires commons-beanutils 1.9.4.  When commons-beanutils 1.9.4 is included in Jenkins 2.222.1 and later, it causes JavaScript errors in the round trip configuration tests.
The round trip configuration tests are much more valuable than the little bit of code that was avoided by not implementing the URL convenience validation checks directly.
See https://groups.google.com/g/jenkinsci-dev/c/0WHC_RJ4n7U/m/E0-fxSLnAQAJ
- Use plugin pom for spotbugs maven plugin version
- Use bom for workflow multibranch plugin version
- Avoid NPE in URI format check
@rishabhBudhouliya if you're available, I'd love to have your review of the changes and the summary email linked above.
> Replace commons validator

- pom.xml
Require Jenkins 2.222.4 so that the plugin continues to use the Jenkins plugin bom.  Would have chosen 2.222.1 except that the credentials plugin requires 2.222.4.
See the Jenkins developer mailing list at
https://groups.google.com/g/jenkinsci-dev/c/hVS6MtLduJ8/m/ATu7uOsiAQAJ
The git plugin currently requires Jenkins 2.204.1 and uses the plugin bom to simplify dependency management.  I like the results of that simplification very much.
A dependabot pull request has proposed to update the git plugin use of bom-2.204.x from 17 to 18.  However, the build of that proposed update fails because one of the dependent plugins requires Jenkins 2.204.6 rather than 2.204.1.
I believe my options are:
* Update the  minimum Jenkins version required by the git plugin from 2.204.1 to 2.222.4 to retain the …
> Require Jenkins 2.222.4 as minimum version

- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionHonorRefSpecTest.java
RefSpecs passed down from build parameters or environments are not being respected on initial checkout, but are on the subsequent ones. This pull request uses the same process used in those subsequent checkouts to resolve the refspecs on the initial checkout.
Test derived from https://github.com/jenkinsci/git-plugin/pull/830
> [JENKINS-56063] Fix refSpec with expanded variables on first clone

- src/main/java/hudson/plugins/git/extensions/impl/CloneOption.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionHonorRefSpecTest.java
﻿- Use local isWindows for consistency in tests
- Remove dead code randomizing honor refSpec test
- Add override annotation
- Remove unused import
- Silence Netbeans warning about unboxing possible null
> Refine the honor refspec test

- src/main/java/hudson/plugins/git/GitPublisher.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
Stemming from IRC discussion with @timja, it seems that for codebase running on Jenkins core after xstream changes (2.266+) the inherited private `readResolve()` methods that are a problem solved by making them protected: https://github.com/jenkinsci/jep/blob/f52f17b085293543a515f8c62fe458491f8e45c9/jep/228/README.adoc#inherited-private-serialization-methods
I do not know if this change really solves any issues, at least it did not fix one I was hunting for (legacy freestyle jobs no longer see my Git SCM that is present in config.xml and state None instead).
Suggested by work and discussion on https://github.com/jenkinsci/envinject-plugin/pull/154
> Adapt to xstream changes: change readResolve() from private to protected

- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
- src/test/java/hudson/plugins/git/extensions/impl/SubmoduleOptionTest.java
The git tool chooser incorrectly selected the JGit implementation for jobs with the submodule option enabled with no other options.  It also incorrectly selected the JGit implementation for jobs with the submodule option enabled and recursive submodules checked.
Fix the issue by always rejecting JGit as a tool if the submodule extension is enabled.
Wrote the test to show the problem.  Initial commit does not include the fix so that the first run of this pull request will show that 2 new tests are failing.
Could have fixed it by making a change to the git client plugin and git plugin both.  It seemed easier to only change the git plugin.
> [JENKINS-64382] Exclude JGit if submodule extension added

- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionHonorRefSpecTest.java
Fixes an array out of bounds exception when the environment variable being tested is an empty string.  The test is checking that the variable is correctly expanded in the refspec but is not designed to test the case where the expanded string is empty.  Testing for an empty string expansion does not add enough value to the already existing tests.
It is possible to create a refspec that would work with the empty string value of the environment variable, but it is more complicated and does not add value to the scenarios evaluated by the test.
The plugin bom tests of the most recent git plugin release are failing because the plugin bom test environment has the value of the environment variable `USER` as the empty string.
See https://github.com/jenkinsci/git-plugin/pull/1013#discussion_r5513552 …
> Skip honor refspec test if env is an empty value

- src/main/resources/jenkins/plugins/git/GitStep/help-branch.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
The documentation previously stated that tag checkout is not supported in one list but then suggested a tag name was a valid branch name elsewhere in the same help text.  In the arguments help text it suggested a tag name was a valid branch name and did not state that tag names are not supported as a branch name in the `git` Pipeline step.  Fix those two documentation mistakes.
The git Pipeline step is a simplified shorthand for a subset of the more powerful checkout step.
The checkout step is the **preferred SCM checkout method**. It provides significantly more functionality than the git step.
> [JENKINS-64720] Fix docs to not reference tag checkout by git step

- pom.xml
- Optional parameterized trigger plugin at least 2.39
- Remove unused slf4jVersion pom property
The parmeterized trigger plugin was updated in 2.38 for compatibility with the change from acegi to spring security framework.  The change to spring security has been in weekly releases since 2.266 and will be in the March 2021 LTS release.
The [parameterized trigger plugin installation statistics](https://stats.jenkins.io/pluginversions/parameterized-trigger.html) shows that users are upgrading parameterized trigger plugin when they upgrade their Jenkins version.  39% of 2.36 installations are running at least Jenkins 2.222.4 (the minimum version supported by the git plugin) and that over 90% of 2.39 installations are running on 2.235.3 or newer.  When users upgrade Jenkins, they seem to also …
> Update optional parameterized trigger plugin to 2.39

- src/main/resources/hudson/plugins/git/GitSCM/help-doGenerateSubmoduleConfigurations.html
- src/main/resources/hudson/plugins/git/GitSCM/help-submoduleCfg.html
- src/main/resources/hudson/plugins/git/SubmoduleConfig/help-branches.html
- src/main/resources/hudson/plugins/git/SubmoduleConfig/help-submoduleName.html
The `doGenerateSubmoduleConfigurations` and `submoduleCfg` arguments are not available from Freestyle projects, matrix projects, or other legacy projects.  They are available from the Pipeline Syntax Editor, the configuration as code plugin, and the JobDSL plugin.  They are intentionally undocumented and will remain undocumented except to declare that they will be removed in a future release.
The settings are not tested in anything other than their default values (`doGenerateSubmoduleConfigurations: false` and `submoduleCfg: []`).
Set expectations that user provided values will be ignored in a future release.
> Add help for deprecated submodule config generator

- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/help-threads.html
The online help was missing for the submodule threads option.
> Provide online help for submodule threads arg

- README.adoc
- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/SubmoduleCombinator.java
- src/main/java/hudson/plugins/git/SubmoduleConfig.java
- src/main/java/hudson/plugins/git/extensions/impl/SubmoduleOption.java
- src/main/java/jenkins/plugins/git/GitSCMBuilder.java
- src/main/java/jenkins/plugins/git/GitStep.java
- src/main/resources/hudson/plugins/git/GitSCM/help-doGenerateSubmoduleConfigurations.html
- src/main/resources/hudson/plugins/git/GitSCM/help-submoduleCfg.html
- src/main/resources/hudson/plugins/git/SubmoduleConfig/help-branches.html
- src/main/resources/hudson/plugins/git/SubmoduleConfig/help-submoduleName.html
- src/main/resources/hudson/plugins/git/extensions/impl/SubmoduleOption/config.groovy
- src/test/java/hudson/plugins/git/AbstractGitProject.java
- src/test/java/hudson/plugins/git/AbstractGitTestCase.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitSCMUnitTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/GitTagActionTest.java
- src/test/java/hudson/plugins/git/SubmoduleCombinatorTest.java
- src/test/java/hudson/plugins/git/SubmoduleConfigTest.java
- src/test/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowserTest.java
- src/test/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowserXSSTest.java
- src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java
- src/test/java/jenkins/plugins/git/GitJCasCCompatibilityTest.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
- src/test/java/jenkins/plugins/git/GitSCMTelescopeTest.java
- src/test/java/org/jenkinsci/plugins/gittagmessage/GitTagMessageExtensionTest.java
Remove `doGenerateSubmoduleConfigurations` and `submoduleCfg` from pipeline syntax.
An experiment was added many years ago to allow git submodule combinations to be computed by the git plugin.  It is unavailable for Freestyle and other classic job types because no user interface was available to access it.
The experiment was made visible to Pipeline users through the Pipeline Syntax snippet generator.  The snippet generator detected the globally visible symbols and their use in a data bound constructor and presented them to the user as required arguments with default values.
No user interface or online help was available to guide the user on the allowed values for `doGenerateSubmoduleConfigurations`  or `submoduleCfg`.  No bug reports have been received on any use of either of those …
> [JENKINS-62052] Remove submodule configurator to improve pipeline snippets

- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagPipelineTest.java
- src/test/java/jenkins/plugins/git/GitSCMTelescopeTest.java
The tests do not need the submodule config settings and are not attempting to verify anything related to submodule config behavior.  Remove the "noise" from those unused settings.
> Remove submodule config debris from two tests

- README.adoc
- src/main/resources/hudson/plugins/git/GitSCM/help-branches.html
- src/main/resources/hudson/plugins/git/GitSCM/help-browser.html
- src/main/resources/hudson/plugins/git/GitSCM/help-extensions.html
- src/main/resources/hudson/plugins/git/GitSCM/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
- src/test/java/hudson/plugins/git/browser/AssemblaWebDoCheckURLTest.java
Improve the pipeline help with intro text for the `checkout scm` step and for other segments of the `checkout scm` step.
- Use snippet-generator redirect
- Provide intro text for scm step
- Add heading text to tagging docs
- Add browser intro help
- Add intro help for extensions
> Add more pipeline help

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
Basically it's reverting the order of the build data that every build has to be sure we return the latest one. When a pipeline runs two or more `checkouts` against the same repo the return values are from the first checkout, not the current=latest? one.
Not sure whether it's the right approach or not as it's my first contribution to the git plugin. All tests are passing in my machine but two of them, but I don't see any relation with the changes and the tests are playing with timeouts so they may be flackies. I want to see what the CI tells us.
> [JENKINS-53346] Return correct map from additional checkout scm calls

- pom.xml
Jenkins 2.249.1 is a recommended version and will soon be two major LTS versions behind the current 2.277.1.
- Require Jenkins 2.249.1 minimum version
- Rely on the spotbugs annotation version from parent
> Require Jenkins 2.249.1

- src/main/resources/hudson/plugins/git/GitSCM/global.jelly
The nesting of one checkbox beneath another checkbox appears to be purely a presentation convenience to only show the `useExistingAccountWithSameEmail` if the `useExistingAccountWithSameEmail` checkbox was enabled.  Since the GitTool data model has the `useExistingAccountWithSameEmail` and the `useExistingAccountWithSameEmail` fields at the same level, this simplifies the user experience by displaying them both at the time.
Tested interactively with Jenkins 2.263.4, Jenkins 2.277.1-rc, and Jenkins 2.281.  Behaves as expected in all cases.
Existing values are loaded as expected on startup.
Values are persisted to the GitTool.xml configuration file when the configuration is applied or saved.
Hints in other communities suggest that the unexpected scrolling is caused by specific CSS markup, …
> [JENKINS-64712] Fix unexpected scrolling of config UI

- pom.xml
over 90% of users on last 4 releases are 2.263.1 or newer
> Use Jenkins 2.263.1 as minimum Jenkins version

- src/test/java/hudson/plugins/git/GitSCMTest.java
Long path failures seem to also happen with git 2.30.0.
> Safeguard against long path on Windows test

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
See https://issues.jenkins-ci.org/browse/JENKINS-65123
> [JENKINS-65123] Always sets GIT_URL

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/main/java/jenkins/plugins/git/GitToolChooser.java
Do not allow command line git operations to extend beyond the workspace.
The CliGit implementation of hasGitRepo() has the strange and surprising behavior that if a workspace contains a directory named ".git" and that directory is not a git repository (for example, an empty directory), then command line git will search upwards in the file system tree to find a git repository and will perform its operations on the repository it finds.  That is the right behavior for a user running command line git.  It allows them to change to different directories and have the same experience with command line git.  JGit has a different behavior.  It does not search upwards for a repository.
It is a dangerous behavior when deciding to run `git clean` or other destructive operations in a Jenkins agent …
> [JENKINS-38699] Only check for git repo in current workspace dir

- README.adoc
- src/main/resources/hudson/plugins/git/GitSCM/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
Use consistently in all locations.
> Correct capitalization of Snippet Generator

- src/main/resources/hudson/plugins/git/util/BuildData/index.jelly
- src/main/resources/hudson/plugins/git/util/BuildData/summary.jelly
More and more jobs are including multiple repositories for things like Pipeline shared libraries and multiple repository builds.  Display the repository immediately below the revision as part of the git build data summary and the git build data details.  If the repository starts with 'http', then it will be displayed as a hyperlink.  There is a risk that the hyperlink cannot be resolved by a web browser, but that risk seems reasonable.
> [JENKINS-38676] Add repository to git build data summary

- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/hudson/plugins/git/util/BuildChooser.java
- src/main/java/hudson/plugins/git/util/BuildChooserContext.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- src/main/resources/hudson/plugins/git/extensions/impl/CheckoutOption/help-timeout.html
- src/main/resources/hudson/plugins/git/extensions/impl/CloneOption/help-reference.html
The changes introduce terminology updates to replace `master` by `controller` and remaining `slave` by `agent`.
This is lead by [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398).
> [JENKINS-65398] Terminology update

- .github/dependabot.yml
The caffeine 3.0.0 library requires JDK 11. Can't require JDK 11.
See #1081 for the dependabot request that generated this change.
> Exclude dep checks on caffeine 3.0.0+

- src/main/java/hudson/plugins/git/extensions/impl/PathRestriction.java
Adapts to jenkinsci/jenkins#5467.
> Stop using deprecated `Util#join`

- src/test/java/jenkins/plugins/git/ModernScmTest.java
See jenkinsci/bom#550. `ModernScmTest` currently expects that Git plugin is the only modern SCM, which interferes with running PCT against Git plugin when Subversion plugin (another modern SCM) is also on the test classpath.
> Loosening `ModernScmTest`.

- src/main/java/jenkins/plugins/git/GitSCMFile.java
Forward the stream provided by jgit when using GitSCMFile::content instead of creating a byte[]. Base class SCMFile::contentAsBytes already provides this if really required.
> JENKINS-65798 use stream provided by jgit directly

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/util/GitUtils.java
- Remove permissions code for Jenkins core before 2.222
- Document release version for two API's
- Remove unused exclusions from pom file
> Remove outdated calls

- pom.xml
Improve dependencies by removing an unnused dependency on caffeine.  It was added pending a release of the script-security plugin.  That release is now available and its version is included in the plugin BOM.
Add jakarata activation api dependency to resolve a Java 11 upper bound dependency error.  Error does not appear on Java 8, only Java 11.
> Remove caffeine dependency

- README.adoc
A user noted in [another bug report](https://issues.jenkins.io/browse/JENKINS-52926?focusedCommentId=411214&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-411214) that the git plugin documentation description of the workaround for [JENKINS-19022](https://issues.jenkins.io/browse/JENKINS-19022) was lacking important context to describe where it would be used, why it would be used, and how it would be used.  This attempts to improve the description of that workaround so that readers better understand when it applies and how to use it.
Also fixes a few spelling errors
> Better describe git build data deletion script

- src/main/java/hudson/plugins/git/GitSCM.java
The earlier submoduleCfg modification changes job XML files unnecessarily.  Does not help users, so let's not make that change.
> Don't modify submoduleCfg definition

- src/main/resources/hudson/plugins/git/extensions/impl/RelativeTargetDirectory/help-relativeTargetDir.html
Include text from the documentation in the online help so that Pipeline users may see that they should not use the 'checkout to subdirectory' extension with Pipeline.
> [JENKINS-66149] Warn against checkout to subdir extension in Pipeline

- src/test/java/jenkins/plugins/git/GitUsernamePasswordBindingTest.java
Fixes test execution on Linux computers with command line git versions older than 2.3.  One example is CentOS 7 with its installation of command line git 1.8.3.
> Simplify Linux test result search

- README.adoc
- src/main/java/jenkins/plugins/git/GitUsernamePasswordBinding.java
- src/main/resources/jenkins/plugins/git/GitUsernamePasswordBinding/help-credentialsId.html
- src/test/java/jenkins/plugins/git/GitUsernamePasswordBindingTest.java
Git plugin 4.8.0 added git credentials binding so that sh, bat, and powershell steps could perform authenticated git operations with git repositories.  Unfortunately, the keyword used GitUsernamePassword instead of following the Pipeline DSL convention of gitUsernamePassword.  This change allows both forms and prefers the gitUsernamePassword form.
> [JENKINS-66214] Fix gitUsernamePassword capitalization

- src/main/java/hudson/plugins/git/util/BuildData.java
- src/test/java/hudson/plugins/git/util/BuildDataTest.java
Provide diagnostic logging to identify which of the previous expected conditions are no longer valid.
> [JENKINS-66212] Fix getLastBuild null pointer exception

- pom.xml
No need to specify the credentials binding plugin version explicity.  We can rely on the plugin bom evaluation to provide the minimum version.
> Use plugin bom for credentials binding plugin

- README.adoc
A small fix to correct `HTTPS` bold formatting under Git Binding section
> Fix bold formatting typo

- README.adoc
- src/main/resources/jenkins/plugins/git/GitUsernamePasswordBinding/help-credentialsId.html
https://www.jenkins.io/doc/pipeline/steps/credentials-binding/#withcredentials-bind-credentials-to-variables will be easier to read without a horizontal scroll bar in the example text.
> Narrow the withCredentials example

- src/main/java/jenkins/plugins/git/GitUsernamePasswordBinding.java
Only used for Jenkins forms, should always be POST.  The call is not especially expensive, but there is no reason to allow a GET request in this context.
> Require POST for tool name API call

- src/main/java/hudson/plugins/git/GitSCM.java
The removal of the package protected method getJenkinsManageOrAdmin seems to have caused JENKINS-66296, an unmarshalling error in the upgrade from git plugin 4.7.2 to git plugin 4.8.0.
Restoring the package protected method seems to avoid the unmarshalling and thus avoids a problem elsewhere in the code.
> [JENKINS-66296] Restore a package protected method

- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
More breakage from jenkinsci/jenkins#5425. This gets the test to pass against both old and new cores.
> Adapting `GitSCMSourceTest` and `GitToolChooserTest` to jenkinsci/jenkins#5425

- src/test/java/jenkins/plugins/git/GitUsernamePasswordBindingTest.java
This PR removes redundant code in `Git Username Password Binding` test class, making the it more understandable. New unit tests are also added.
> Git credentials binding unit test improvements

- src/test/java/hudson/plugins/git/browser/AssemblaWebDoCheckURLTest.java
Tests now fail due to changes in the https://www.assembla.com web site.  Not enough value in those tests to retain them.  Will reduce code coverage but also will reduce maintainence overhead and provide a small reduction in test time.
> Remove two Assembla tests

- pom.xml
- src/main/resources/hudson/plugins/git/GitSCM/help-userRemoteConfigs.html
- src/main/resources/hudson/plugins/git/GitSCM/help-userRemoteConfigs_ja.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/util/BuildDataTest.java
- src/test/java/hudson/plugins/git/util/GitUtilsTest.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
- src/test/resources/hudson/plugins/git/GitSCMTest/old1.xml
GitHub is dropping support for git protocol, but other sites are not necessarily dropping that support.  Update the tests and the documentation to not reference git:// protocol support from github.com.
* Use https repo URL in the pom, not git://
* Remove git://github.com from examples
* Replace git protocol example with https
* Use https instead of git protocol in GitSCM compatibility test
* Use example.com, not github.com in URL tests
* Use valid GitHub URLs in BuildDataTest
> Replace GitHub references to git:// protocol

- pom.xml
Dependency is no longer needed.
> Remove test dep on xmlunit-matchers

- pom.xml
Parent pom 4.27 disabled coverage reporting.
> Fix coverage reporting by using parent pom 4.28

- src/main/java/hudson/plugins/git/GitRevisionBuildParameters.java
This essentially re-introduces the method change that was done in #774 then reverted in #775. Nowadays, the promoted-builds dependency is way more recent.
> [JENKINS-67045] Migrate deprecated call to `Promotion#getTarget`

- pom.xml
It shows up in the help provided by this plugin and others don't seem to do that:
> Remove Jenkins from plugin name

- src/main/resources/hudson/plugins/git/BranchSpec/config.groovy
- src/main/resources/hudson/plugins/git/GitSCM/config.jelly
- src/main/resources/hudson/plugins/git/UserRemoteConfig/config.groovy
This plugin wasn't using the standard controls from core, Kohsuke changed this many years ago to make the UI 'more compact', but generally better to be consistent.
The other source of non standard control is adding the CSS which prevents deleting the last instance in a repeatable block, I've added support for this in core and added a TODO to address it once the baseline is updated:
https://github.com/jenkinsci/jenkins/pull/5897/commits/dacf1aef8cb0a1af90f5fe8baf12485d7a5ad518
See https://github.com/jenkinsci/jenkins/pull/5897
cc @MarkEWaite
> Use standard Jenkins buttons for better compatibility

- src/main/resources/hudson/plugins/git/GitPublisher/config.jelly
- src/main/resources/hudson/plugins/git/GitTagAction/tagForm.jelly
No longer required since minimum version always includes div based forms.
> Remove divBasedFormLayout conditionals

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
[JENKINS-55813](https://issues.jenkins.io/browse/JENKINS-55813) intentionally throws an exception when a user account is reported by Spring security as disabled, locked, or expired.  User lookup for the git changeset display is not critical enough to allow that exception to fail the build.
Changes include:
- Add more GitChangeSet tests
- Check for null user before dereferencing
- [JENKINS-67491](https://issues.jenkins.io/browse/JENKINS-67491)  Do not fail on users disabled by auth provider
Does not fix the one or two other locations in the method where `User.get()` is called.  I want to understand if this resolves the issue for the user before applying the same change more widely.
@basil I'd appreciate a review of the proposed change if you're willing to do it.
> [JENKINS-67491] Do not fail build on auth exception

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Similar to #1151 by default git comes without any hooks, but when creating a new sample git repo with the code it would copy the system default hooks, meaning this sample repo can behave differently on different platforms.
by not using the hooks here we can avoid littering test code with "--no-verify" on commits, and can avoit hooks in other cases as well, which consume test time and / or even fail the operation due to a failing hook requirement (e.g. no JIRA reference)
when consuming this in pipeline-model-definition's ValidatorTest test locally go from failing due to timeout exception (10 minutes) to completing in 2 minutes
@MarkEWaite
> initialize the test repos without a default template

- .github/dependabot.yml
No need to check every day.  Once a week is enough.
> Only check for new action versions weekly

- pom.xml
Do not want equalsverifier 3.9 until its pom files are available.
- Revert "Exclude byte-buddy from mockito-core"
- Revert "Bump equalsverifier from 3.8.3 to 3.9"
> Revert equalsverifier 3.9

- src/test/java/hudson/plugins/git/GitSCMTest.java
The test should wait for the build to complete before actually checking
its status.
```
java.lang.AssertionError:
unexpected build status; build log was:
------
Started by upstream project "test0" build number 1
originally caused by:
Legacy code started this job.  No cause information is available
Running as SYSTEM
Building in workspace /jenkins/workspace/builder/output-git/work/git/target/tmp/j h69583182000798596/workspace/test1
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository /jenkins/workspace/builder/output-git/work/git/target/tmp/junit3569465322501079491/junit1849114342070567213
> git init /jenkins/workspace/builder/output-git/work/git/target/tmp/j h69583182000798596/workspace/test1 # timeout=10
------
Expected: is …
```
> Fix flaky `GitSCMTest#testSubmoduleFixup`

- src/main/java/hudson/plugins/git/GitSCM.java
Required for https://github.com/jenkinsci/github-branch-source-plugin/pull/527 to take advantage of https://github.com/jenkinsci/credentials-plugin/pull/293. Otherwise `withCredentials` works but `checkout scm` does not.
> Use `CredentialsProvider.findCredentialById` whenever possible

- CONTRIBUTING.adoc
Tests can fail if the default branch name is not the traditional "master". This PR warns of this problem in the CONTRIBUTING.md and explains how to temporarily disable the setting.
- Documentation
> Add warning about unexpected default branch name.

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/git/extensions/GitSCMExtension.java
Use Java 17 in the Jenkinsfile to compile and test.
Tests are failing with a serialization error.  I need more guidance on the changes needed to fix the failing tests.
> Test with Java 17 in addition to Java 11 and Java 8

- src/test/java/jenkins/plugins/git/GlobalLibraryWithModernJCasCCompatibilityTest.java
Discovered when doing manual compatibility testing last December, but also appears when testing early iterations of JENKINS-45047 (which essentially automates that manual procedure). I suspect the only reason this does not show up in current versions of PCT is that PCT has a flawed methodology for dependency updating. Anyway, the problem appears to be in the code under test rather than in the test, so pending a fix for the underlying bug let us relax this test to avoid spurious errors from compatibility testing tools. This PR does so by relaxing the check to the simple class name rather than the exact class. Of course it is not expected that we would be matching a class from a different plugin, but that is the point of JENKINS-67309.
> Work around JENKINS-67309

- README.adoc
Fixes a small typo in documentation, by changing "expoand" to "expand".
This is a really minor typo fix. Just noticed it when reading the docs and hope this is helpful and not annoying!
> Fix minor typo in documentation.

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/Security2478Test.java
- src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagPipelineTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
- src/test/java/org/jenkinsci/plugins/gittagmessage/AbstractGitTagMessageExtensionTest.java
https://www.jenkins.io/security/advisory/2022-05-17/#SECURITY-2478
I recommend merging this PR using merge commit, so that the release commits of 4.11.2 are on the history of the default branch.
> Merge back SECURITY-2478 fix into default branch

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMUnitTest.java
The security fix in https://github.com/jenkinsci/git-plugin/commit/b295606e0b865c298fde27bea14f9b7535a976e6 broke all Git checkouts that use remotes with an explicit protocol on Jenkins controllers running on Windows. This PR fixes that issue by catching `InvalidPathException` in the relevant location.
I have not tested the PR (I do not have access to a Windows machine right now). I am not sure if we easily can create automated tests with non-`file` remotes that would exercise this behavior. We should be able to test it at surface level using mocks or maybe via a complex `WireMock` harness for a more thorough test.
Just filing a draft PR for now since I have not tested anything.
CC @Pldi23
> [JENKINS-68562] Fix Git checkouts for controllers running on Windows

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Tests fail on systems with a non-master default branch: https://github.com/jenkinsci/remote-file-plugin/issues/111
Recent Git versions support passing a default branch to `init` but would require git 2.28+.
Tests of this plugin are affected too, but need more investigation. 
N/A
> Explicit default branch

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
When processing the changelog, if a looked user is disabled in LDAP the git plugin would throw an `UncheckedExecutionException` with the cause being `DisabledException`. The unhandled exception would cause a build
failure whenever processing a commit that is determinated to be from a disabled user.
Jenkins `UserDetailsCache.loadUserByUsername()` receives an `ExecutionException` which wraps the `AuthenticationException`. The method inspects the cause, handles instances of `UsernameNotFoundException` which it throws but ignores any other `AuthenticationException`.
This introduces a `User` getter to handle any `AuthenticationException` and throws it instead of the `ExecutionException`. Callers can thus:
```java
try {
user = getUser("someOne");
} catch (AuthenticationException e) {
return …
```
> [JENKINS-67981] handle any AuthenticationException

- src/test/java/hudson/plugins/git/GitHooksTest.java
Fix test on Unix platforms that do not include bash by default.
On FreeBSD and OpenBSD (where `/bin/bash` is not available), I run
```
$ git checkout master
$ mvn clean -Dtest=GitHooksTest test
HEAD is now at e98fea9 Jenkinsfile
fatal: cannot run .git/hooks/post-checkout: No such file or directory
```
Using this pull request, the failing test is resolved:
```
$ git checkout -b use-posix-shell -t origin/use-posix-shell
$ mvn clean -Dtest=GitHooksTest test
Test passes
```
> Use /bin/sh rather than /bin/bash in test

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
The `git branch -m master` fails on a repository created with command line git versions 2.25, 2.20, 2.17, and 1.8.  It works with git versions 2.30 and later.
Setting was added in July 2022 as part  of #1295 for systems that have their default branch name configured as something other than `master`.
> Fix tests on older CLI git versions

- src/test/java/hudson/plugins/git/GitHooksTest.java
Hook message is displayed when I run git interactively but does not appear in the console log when the test is run.  Not worth the time to research why command line 1.8 is different from all the other git versions that are being tested.
Unclear why that old git version behaves differently than all the other versions that are being tested.  Not worth the time to investigate the root cause.  Accept that command line git 1.8 is a very old version that has several exceptions already included in the plugin.
> Skip hook assertion on git 1.8

- src/main/java/hudson/plugins/git/GitStatus.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
Require a non-default logging level to see messages related to polling and indexing, including the "polling not triggered", "polling triggered", and "indexing triggered" messages.
Only changes the logging level, not the availability of those log messages.
- ~~I have added tests that verify my changes~~
- ~~I have interactively tested my changes~~
> [JENKINS-69613] Reduce log output at INFO level

- src/main/resources/hudson/plugins/git/GitPublisher/config.jelly
Hello there :wave:
Hacktoberfest PR here solving [JENKINS-69862](https://issues.jenkins.io/browse/JENKINS-69862).
That PR removes the [legacy form validation](https://www.jenkins.io/doc/developer/security/csp/#legacy-javascript-checkurl-validation) using `checkUrl` and now uses the recommended approach including `checkDependsOn`, ensuring there are no CSP warnings with this part of the source code anymore.
I manually tested the source code before and after introducing the changes to ensure everything still works as expected (and it does).
Please let me know if anything is missing.
Thanks a lot for the review :heart:
> [JENKINS-69862] remove inline JS for URL validation

- pom.xml
Not enough added value to keep a separate declaration of spotbugs.  Use spotbugs as defined for others and used by others.
- ~~I have interactively tested my changes~~
> Rely on spotbugs from parent pom

- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/config.jelly
- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.js
Hello there :wave:
Here's another Hacktoberfest PR, this time solving [JENKINS-69861](https://issues.jenkins.io/browse/JENKINS-69861).
That PR removes the [inline event handlers](https://www.jenkins.io/doc/developer/security/csp/#inline-event-handlers) using inline `onclick` and now creates those `onclick` handlers from a separate javascript file (which was already included in the page). This is made to ensure there are no CSP warnings with this part of the source code anymore.
I manually tested the source code before and after introducing the changes to ensure everything still works as expected (and it does).
Here is a small clip of me testing the feature after performing the changes (which is the same behavior as before):
Please let me know if anything is missing.
Thanks a lot for the …
> [JENKINS-69861] remove inline onclick handlers

- src/main/resources/hudson/plugins/git/GitTagAction/tagForm.jelly
- src/main/resources/hudson/plugins/git/GitTagAction/update-row.js
I've removed the JavaScript from the `tagForm.jelly` file and moved it to a new file called `update-row.js`.
> [JENKINS-69911] - GitTagAction/tagForm.jelly javascript un-inlined.

- src/main/resources/hudson/plugins/git/BranchSpec/config.groovy
- src/main/resources/hudson/plugins/git/UserRemoteConfig/config.groovy
Having the repeatableDelete button wrapped in the entry component causes unnecessary padding.
**Before**
**After**
---
> Remove wasted space from branch spec and repository URL data entry

- src/test/java/hudson/plugins/git/GitHooksTest.java
Also intentionally avoids all calls to Functions.isWindows because that mthod is not used in any other location in the tests or in the production code.  It is not used because there was a time when a remote class loader issue was detected due to loading the Hudson.Functions class just to decide if a class was running on Windows.  The inline test is simple and is easy to read.
Confirmed that the GitHooksTest works in my dev env.
> Fix NPE in GitHooksTest on Windows

- Jenkinsfile
- pom.xml
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
- Remove unused imports
- Use pipeline groovy lib version from BOM
- Do not set forkCount in pom
- Require Jenkins 2.346.3 or newer
80% or more of the last several plugin releases are using Jenkins 2.346.1 or newer.  Safe to require 2.346.3.
> Require Jenkins 2.346.3 or newer

- pom.xml
- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
When I attempted to switch from one testing thread per core (stop using `forkCount=1C` in pom), the tests did not complete in the 60 minute allowed for plugin jobs on ci.jenkins.io, especially on Windows.  This pull request sets the forkCount to `1C` to use a process for each core available on the testing machine.  It also moves a few long running tests from GitSCMTest into a new class in hopes that will allow parallelism in more cases.  It also reduces test execution on Windows by skipping at least one low value, platform independent test on Windows.
- Test with all available cores
- Improve test parallelism by moving some slow tests
> Split GitSCMTest for parallel execution on multiple cores

- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/test/java/jenkins/plugins/git/GitSCMFileSystemTest.java
- Duplicate null pointer exception in a test (12fca98a911931410d70d395e5a218afb2b32d4b)
- Fix null pointer exception in GitSCMFileSystem (18463b8b8b318000f8081aa3b0ed47f8065d9180)
When rev was not null and env was null, a null pointer exception was thrown as the code tried to use the null env to expand environment variables in the rev argument.
First commit duplicates the null pointer exception in a test.  Second commit resolves the null pointer exception.
@MartinKosicky sorry that we missed the null pointer exception in the code review and in the test automation.  Thanks very much for your pull request and for the automated tests that you added.  Those tests made it very simple to add one more test for the null pointer exception.  That failing test then made it easy to fix the issue in …
> [JENKINS-70158] Fix null pointer exception in GitSCMFileSystem

- src/test/java/hudson/plugins/git/browser/GitRepositoryBrowserTest.java
One test class uses the history of the git plugin to test various conditions in the GitRepositoryBrowser class.  Accept that those cases are not tested when the tests are running from a shallow clone.
Allow the plugin compatibility tests and other automated test environments to use a shallow clone of the repository for tests.  The test conditions that are skipped as a result of this change are much less important than keeping test environments simple and consistent.
> Allow tests with shallow clone of source repository

- pom.xml
In https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-1367/1/consoleFull I noticed that the SCM tag had fallen out of sync with the expected value leading to the lack of an incremental deployment:
```
18:59:54  Invalid archive retrieved from Jenkins, perhaps the plugin is not properly incrementalized?
18:59:54  Error: ZIP error: Error: Wrong commit hash in /project/scm/tag, expected 8301c44440e82281ca7cb0321e004df00d6926f8, got git-4.14.0 from https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-1367/1/artifact/**/*8301c44440e8*/*8301c44440e8*/*zip*/archive.zip
18:59:54  Success: Status code 400 is in the accepted range: 100:599
```
> Reincrementalify

- pom.xml
Notes from Basil Crow are in https://github.com/jenkinsci/bom/pull/1623#issuecomment-1339989438
Attempting first pass as a test dependency and as optional.  If that passes the BOM tests, then that's lowest impact on the plugin, since it does not add an optional runtime dependency.
If the test dependency is not enough, then conditional build step plugin will be added as an optional dependency until the next release of parameterized trigger plugin.
> Add conditional build step plugin to fix BOM tests

- CONTRIBUTING.adoc
- Jenkinsfile
- src/test/java/hudson/plugins/git/GitChangeSetPluginHistoryTest.java
- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitStepTest.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
- src/test/java/jenkins/plugins/git/GitUsernamePasswordBindingTest.java
- src/test/java/jenkins/plugins/git/RandomOrder.java
Limit test duration of the longest running tests.
Use JUnit assume to skip tests after time exceeded.  JUnit assume will flag the test skip as a warning in the Jenkins job.  That's a good thing in this case, since we want to know when tests are skipped due to excessive elapsed test time.
Run tests in random order so that parallel tests on ci.jenkins.io have a better chance of executing every test in at least one configuration.
Run all tests when not in CI so that developers see all results.  Developers are not limited by the 60 minute limit applied by `buildPlugin` and they usually have computers that are fast enough that the time limits are never reached on any of the tests.
Report duration limit in skip message.
- Do not stop parallel tests on first failure
- Remove low value …
> Limit duration of longest tests

- CONTRIBUTING.adoc
- Jenkinsfile
- pom.xml
- src/main/resources/hudson/plugins/git/extensions/impl/MessageExclusion/help-excludedMessage.html
- src/main/resources/hudson/plugins/git/extensions/impl/MessageExclusion/help-excludedMessage_ja.html
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-excludedRegions.html
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-excludedRegions_ja.html
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-includedRegions.html
- src/main/resources/hudson/plugins/git/extensions/impl/PathRestriction/help-includedRegions_ja.html
- Link to Java 11 javadoc, not Java 8
- CI test with Java 11 and Java 17
- Use the simpler documentation URL
- Remove unused properties, document required properties
- Require Jenkins 2.361.4 or newer
- Remove unused import
- Use git client plugin 4.0 incremental
Prepare for git plugin 5.0.0 release with requirement for Java 11 and with additional changes for the addition of Pipeline symbols to make Pipelines easier to express.
Needs additional testing in:
Once this pull request is merged, then the [add-symbols branch](https://github.com/MarkEWaite/git-plugin/tree/add-symbols) needs to be merged (probably after a squash or a rebase to make the history less filled with debris).  The "add symbols" change is the reason for the increment of the major version from 4.x to 5.x.  
I hope that …
> Require Java 11 and Jenkins 2.361.4 or newer

- src/test/java/hudson/plugins/git/GitSCMTest.java
Test has been ignored for a very long time.  It is unreliable and already well tested in other ways.
> Delete unreliable notifyCommit test

- src/main/java/hudson/plugins/git/GitSCM.java
A missing commit message is not sufficient to justify the distraction of a stack trace in the log.  State that the commit message cannot be displayed because the commit cannot be found.
> Do not show stack trace when printing a missing commit

- src/main/java/hudson/plugins/git/ApiTokenPropertyConfiguration.java
- src/main/java/hudson/plugins/git/BranchSpec.java
- src/main/java/hudson/plugins/git/GitBranchSpecifierColumn.java
- src/main/java/hudson/plugins/git/GitChangeLogParser.java
- src/main/java/hudson/plugins/git/GitPublisher.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java
- src/main/java/hudson/plugins/git/GitStatus.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/hudson/plugins/git/browser/GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/extensions/impl/PathRestriction.java
- src/main/java/hudson/plugins/git/util/AncestryBuildChooser.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitHooksConfiguration.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/java/jenkins/plugins/git/MergeWithGitSCMExtension.java
- src/main/java/jenkins/plugins/git/traits/DiscoverOtherRefsTrait.java
- src/main/java/jenkins/plugins/git/traits/RefSpecsSCMSourceTrait.java
- src/main/java/jenkins/plugins/git/traits/RemoteNameSCMSourceTrait.java
This PR reduces usage of third-party libraries as much as possible in favor of Java Platform equivalents. While there is nothing wrong with third-party libraries like Apache Commons Lang, most of its functionality is available in the Java Platform now, like `String#strip`, `String#isBlank`, `String#join`, etc.
Unlike Apache Commons Lang, the Java Platform forces you to think about null, which I personally think is a good thing. Some people might find the constant null checks tedious, but I think it is a good thing to be confronted with them. Many of them are actually unnecessary, which will be more obvious if they aren't buried in a library.
I realize that this change is quite subjective, so if the maintainer's preferences are different than my own, please close this PR. I won't be …
> Reduce usage of third-party libraries

- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/CliGitCommand.java
Command line git won't throw expected exception if it is pruning deleted references during the fetch operation.
Also extends the CliGitCommand class in the tests for easier use.
> Skip 2 tests if prune on fetch is enabled globally

- pom.xml
- src/main/java/hudson/plugins/git/BranchSpec.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitSCMBackwardCompatibility.java
- src/main/java/hudson/plugins/git/GitStatus.java
- Use parent pom 4.57
- Add @Deprecated annotation to match javadoc
> Use parent pom 4.57

- pom.xml
https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.60 notes that mockito-inline was removed in mockito/mockito#2945, replaced with mockito-core.
> Remove mockito-inline from tests

- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
As discussed in https://github.com/jenkinsci/acceptance-test-harness/pull/1108
> Check the browser in a configRoundtrip

- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.js
- src/main/resources/hudson/plugins/git/GitTagAction/update-row.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), went to the Security page and generated a Git plugin …
> Replace Prototype.js with native JavaScript

- src/test/java/hudson/plugins/git/SCMTriggerTest.java
The tests were disabled because they caused releases in 2016 to require an hour or more.  Newer hardware runs faster and time limiting options in tests may allow more of them to run without affecting the time to release the plugin.
- Remove test that was disabled in 2016
- Time limit SCMTriggerTest on Linux
- Allow up to 2 minutes for SCMTriggerTest
> Enable SCMTriggerTests

- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.js
Noticed this trivial mistake while doing some additional interactive testing.
> Fixup to #1448

- pom.xml
Attempt this revert in order to fix broken tests.  Need to understand which commit causes tests to fail for Java 17 on Windows and solve the underlying problem.  Reverting the upgrade to parent pom 4.64 is the simplest short term solution, then the real fixes will need to be applied to the tests on Windows.
This reverts commit 6df18ba4d479dfaf4ba5a79acdad8406a2c11dc8.
> Fix broken tests

- src/test/java/hudson/plugins/git/AbstractGitProject.java
- src/test/java/hudson/plugins/git/AbstractGitTestCase.java
- src/test/java/hudson/plugins/git/GitChangeSetBadArgsTest.java
- src/test/java/hudson/plugins/git/GitChangeSetTest.java
- src/test/java/hudson/plugins/git/GitHooksTest.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/GitStatusTheoriesTest.java
- src/test/java/hudson/plugins/git/Security2478Test.java
- src/test/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowserXSSTest.java
- src/test/java/hudson/plugins/git/extensions/GitSCMExtensionTest.java
- src/test/java/hudson/plugins/git/extensions/impl/BuildSingleRevisionOnlyTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionDepthTest.java
- src/test/java/hudson/plugins/git/extensions/impl/CloneOptionHonorRefSpecTest.java
- src/test/java/hudson/plugins/git/security/ApiTokenPropertyConfigurationTest.java
- src/test/java/hudson/plugins/git/util/GitUtilsJenkinsRuleTest.java
- src/test/java/jenkins/plugins/git/GitBranchSCMHeadTest.java
- src/test/java/jenkins/plugins/git/GitHooksConfigurationTest.java
- src/test/java/jenkins/plugins/git/GitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitToolChooserTest.java
- src/test/java/jenkins/plugins/git/ModernScmTest.java
- src/test/java/jenkins/plugins/git/traits/GitSCMExtensionTraitTest.java
- src/test/java/org/jenkinsci/plugins/gittagmessage/AbstractGitTagMessageExtensionTest.java
- src/test/java/org/jenkinsci/plugins/gittagmessage/GitTagMessageExtensionTest.java
Several different names are used inconsistently throughout the tests. Those naming differences make it more difficult to read the tests and more difficult to maintain.
Many
> Use consistent JenkinsRule variable name

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitToolChooser.java
- src/spotbugs/excludesFilter.xml
Increases spotbugs checks by reducing the threshold to "Low".  Also resolves a few spotbugs warnings by code corrections.
- Remove uncalled static method
- Remove redundant null checks in AbstractGitSCMSource
- Fix spotbugs warning on repo cache size updates
- Increase spotbugs checks
Inspired by a NonNull annotation in #1468 that should have reported a spotbugs warning and did not.
> Increase spotbugs checks

- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/GitStatus.java
- src/test/java/hudson/plugins/git/GitStatusSimpleTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
Test already had code that waits for jobs to complete on Windows.  The improved job leak detection that was implemented in the Jenkins test harness will sometimes show the same conditions on Unix builds.  Wait for jobs to complete on Windows and on Unix.
> Fix erratic GitStatusTest

- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.js
See https://github.com/jenkinsci/jenkins/pull/8279. There is no user-visible bug here, nor is there any security problem. But the code did not conform to best practices. This PR is a code cleanup PR to make the code conform to best practices. There is no urgent need to merge and release it.
To test this PR, I set breakpoints on the modified lines and exercised the code successfully by generating and subsequently revoking an API token.
> Pass POST parameters in body rather than query string

- pom.xml
parameterized-trigger now managed by bom
conditional-buildstep not needed as a dependency
maven plugin now mannaged by bom
Needs to be verified in the plugin bill of materials before it is merged.  Previous attempts to remove the conditional-buildstep dependency passed tests in the git plugin but failed in the bill of materials when the maven plugin was being loaded.
> Use plugin bom more widely

- src/main/resources/hudson/plugins/git/GitSCM/help.html
The [Sep 2021 GitHub blog post](https://github.blog/2021-09-01-improving-git-protocol-security-github/) announced the removal of the git:// protocol from GitHub.
Change the documentation to use a provider that still supports unauthenticated git:// protocol.
> Use a working git:// protocol example

- pom.xml
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMTelescope.java
> Use Spring security API instead of Acegi security

- README.adoc
Highlight that `GIT_PREVIOUS_SUCCESSFUL_COMMIT` and `GIT_PREVIOUS_COMMIT` are not being set during the first build for a given git branch. Might save someone else a few headscratches.
Also, this appears to be part of [the previous, now-deprecated documentation](https://wiki.jenkins.io/JENKINS/Git-Plugin.html).
> Documentation - clarify when certain env variables are being set

- src/main/java/hudson/plugins/git/extensions/impl/CheckoutOption.java
Did not need to override this method as it left the value at the default of `false`: https://github.com/jenkinsci/git-plugin/blob/daa95b6d0957492a2fcee458097bd99a04e06a31/src/main/java/hudson/plugins/git/extensions/GitSCMExtension.java#L43-L45
> Remove `CheckoutOption.requiresWorkspaceForPolling` override

- README.adoc
Configuration as code examples are available in most plugin documentation but were not included in the git plugin documentation.
> Add global configuration as code example

- pom.xml
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/java/hudson/plugins/git/RemoteConfigConverter.java
- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/BitbucketServer.java
- src/main/java/hudson/plugins/git/browser/BitbucketWeb.java
- src/main/java/hudson/plugins/git/browser/CGit.java
- src/main/java/hudson/plugins/git/browser/FisheyeGitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitLab.java
- src/main/java/hudson/plugins/git/browser/GitList.java
- src/main/java/hudson/plugins/git/browser/GitWeb.java
- src/main/java/hudson/plugins/git/browser/GithubWeb.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/GitoriousWeb.java
- src/main/java/hudson/plugins/git/browser/GogsGit.java
- src/main/java/hudson/plugins/git/browser/KilnGit.java
- src/main/java/hudson/plugins/git/browser/Phabricator.java
- src/main/java/hudson/plugins/git/browser/RedmineWeb.java
- src/main/java/hudson/plugins/git/browser/RhodeCode.java
- src/main/java/hudson/plugins/git/browser/Stash.java
- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
- src/main/java/hudson/plugins/git/opt/PreBuildMergeOptions.java
- src/main/java/hudson/plugins/git/util/Build.java
- src/main/java/hudson/plugins/git/util/BuildData.java
Suppress the CT_CONSTRUCTUR_THROWS warning because it is not helpful in a Jenkins context.  More details are available in https://github.com/jenkinsci/plugin-pom/pull/869#issuecomment-1860918407
Suppress public primitive spotbugs warning for existing APIs.  Preserve compatibility without allowing new additions to include public primitives.
Suppress null argument check for descriptor's newInstance.  Javadoc of the parent object states that the req argument will always be non-null, but cannot be annotated as non-null due to compatibility needs.
Suppress unused field warning in GitSCM descriptor.  Do not risk compatibility by removing the private field.
Changes to pom.xml will be removed once plugin pom includes the new settings.
> Use spotbugs plugin 4.8.2.0

- .github/dependabot.yml
- pom.xml
Fails tests in plugin bill of materials with report that promoted builds
needs to be upgraded to a newer version.
One error message is:
Caused by: java.io.IOException: Failed to load: Git plugin (git 5.2.2-rc5199.9999da_372d5a_)
- Update required: Jenkins promoted builds plugin (promoted-builds 3.11) to be updated to 945.v597f5c6a_d3fd or higher
Second error message is:
Caused by: java.io.IOException: Failed to load: Git plugin (git 5.2.2-rc5199.9999da_372d5a_)
- Update required: Jenkins promoted builds plugin (promoted-builds 892.vd6219fc0a_efb) to be updated to 945.v597f5c6a_d3fd or higher
Also adds a dependabot exclusion for that release of promoted builds
plugin.
This reverts commit 4f5ecfeafaf16d1d44b699561509279d4b2cdb8a.
> Revert "Bump org.jenkins-ci.plugins:promoted-builds (#1542)"

- pom.xml
- src/main/java/hudson/plugins/git/GitPublisher.java
- src/main/java/hudson/plugins/git/GitTagAction.java
- src/test/java/hudson/plugins/git/AbstractGitRepository.java
- src/test/java/hudson/plugins/git/GitChangeSetTruncateTest.java
- src/test/java/hudson/plugins/git/GitPublisherTest.java
- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitTagActionTest.java
- src/test/java/hudson/plugins/git/TestGitRepo.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagPipelineTest.java
- src/test/java/hudson/plugins/git/extensions/impl/PruneStaleTagTest.java
- src/test/java/hudson/plugins/git/util/GitUtilsTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
- src/test/java/jenkins/plugins/git/GitStepTest.java
Some test cases related to `tag` git command can fail in case of the following `~/.gitconfig` configuration
```
[tag]
gpgSign = true
```
> disable tag.gpgsign as it could be active for some systems

- src/test/java/hudson/plugins/git/GitSCMSlowTest.java
Skip testMergeWithMatrixBuild if gpgsign enabled
The testMergeWithMatrixBuild test fails randomly on several machines when commit.gpgsign and tag.gpgsign are not enabled if the TestPreBuildMerge implementation is used. It passes consistently when PreBuildMerge is used.
Rather than spend the time trying to diagnose the intermittent failures, this configuration allows the test to be skipped if either of those configuration settings are enabled.
Other tests in this class are able to use TestPreBuildMerge without issue.  
Would like a review from @olamy, if possible.
Tested by enabling commit.gpgsign in ~/.gitconfig and by enabling commit.gpgsign in a $XDG_CONFIG_HOME/.gitconfig file.  Test was skipped when gpgsign was enabled in either of those files.
> Skip testMergeWithMatrixBuild if gpgsign enabled

- src/main/java/jenkins/plugins/git/GitUsernamePasswordBinding.java
cmd.exe doesn't work with '/' as path separator.
With #1443 the `GIT_ASKPASS` script was changed. Unfortunately the `.bat` script contains `/` instead of `\` on Windows. While `/` generally works as path separator on Windows, it does not work with `cmd.exe`.
This is a small change that fixes a bug introduced in `5.2.0` making the `gitUsernamePassword` binding unuseable on windows agents.
> [JENKINS-72044] Fix withCredentials directory separators on Windows

- src/main/java/hudson/plugins/git/GitSCM.java
(skipping the template because the change is so trivial)
> Fix JavaDoc Typo

- src/main/java/hudson/plugins/git/GitStatus.java
It is right now, but it won't be in the future when a second compatibility method is added to it for EE 9.
Passed in EE 8 and EE 9.
> Do not assume `HttpResponse` is a functional interface

- src/test/java/hudson/plugins/git/browser/AssemblaWebDoCheckURLTest.java
Returned HTTP 524 is a recent test
Test is not valuable enough to waste time diagnosing it
> Remove two tests that depend on assembla.com

- src/test/java/hudson/plugins/git/GitHooksTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Git plugin is no longer tested or supported on operating systems with a command line git version older than 2.20 (Debian 10).  This removes outdated tests.  It does not prevent the plugin from running with older versions, but removes test clutter from older versions.
> Remove outdated test conditionals

- src/main/resources/jenkins/plugins/git/GitStep/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help_ja.html
The "$class: 'GitSCM'" syntax has not been needed for many releases.
Found while reviewing the online help for the [`git` step](https://www.jenkins.io/doc/pipeline/steps/git/) in the Pipeline steps reference.
> Use modern syntax in git step online help

- src/main/java/hudson/plugins/git/GitPublisher.java
This PR corrects the getters used on the NoteToPush internal class of the GitPublisher class.
n/a
> Use correct getters for note fields

- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/config.jelly
- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.css
- src/main/resources/hudson/plugins/git/ApiTokenPropertyConfiguration/resources.js
small UI update for the access tokens
replace yui-button with jenkins-button to be in sync with the overall jenkins styling
Use a dialog to confirm revocation of access tokens
Before:
After:
If this is a relatively large or complex change, start the discussion by explaining why you chose …
> Generate and revoke access tokens with standard UI components

- Jenkinsfile
Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.
If this is a relatively large or complex change, start the discussion by explaining why you …
> Allow tests with containers

- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/resources/jenkins/plugins/git/Messages.properties
- src/test/java/jenkins/plugins/git/FIPSModeSCMSourceTest.java
This is a follow-up of https://github.com/jenkinsci/git-plugin/pull/1611
That PR left a case without covering: SCMSources could be configured with invalid values and, when fetched (e.g. multibranch pipelines) credentials could be leaked.
`IllegalArgumentException` throwing has no effect here (other than the logs), as MBPs handle that, so failures would be transparent to the user, also credentials could come from other sources (e.g. `GIT_PASSWORD`). Form validation is still in place and wasn't modified.
Therefore, in this case we are interrupting fetch operation, so we can be sure credentials are not leaked. 
When trying to fetch a remote with credentials and an insecure URL we will 
* Log as SEVERE
* Interrupt the fetch operation
* Add the same log message to the `TaskListener` so it's …
> [JENKINS-73506] Reject fetch requests that use credentials with HTTP in FIPS mode

- src/main/java/hudson/plugins/git/browser/AssemblaWeb.java
- src/main/java/hudson/plugins/git/browser/FisheyeGitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/GitBlitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/Gitiles.java
- src/main/java/hudson/plugins/git/browser/TFS2013GitRepositoryBrowser.java
- src/main/java/hudson/plugins/git/browser/ViewGitWeb.java
No need to throw ServletException when checking for URL validity.  IOException is sufficient and avoids including Jakarta EE in the method signature.
* Confirmed that AssemblaWeb still reports the expected message when an invalid URL is provided and that it reports no message when a valid URL is provided.  Confirmed that Assembla has changed URLs and broken the browsing links that previously worked. Separate bug report
* Confirmed that GitBlit browsing works as expected by installing a GitBlit server. https://hub.docker.com/r/gitblit/gitblit
* Confirmed that ViewGit browser provides change links as expected.  Confirmed that the ViewGit URL check logic no longer works on the site used as an example.  Now reports that https://repo.or.cz/ does not look like a ViewGit site. Separate bug …
> Adapt git browsers for Jetty 12 EE 9 transition

- src/test/java/hudson/plugins/git/GitSCMTest.java
- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
- src/test/java/jenkins/plugins/git/GitStepTest.java
The GitStepTest already includes logic that uses notifyCommit to start jobs and perform other tests of notifyCommit.  Use that logic to replace the mocked testDoNotifyCommitWithInvalidApiToken with a test that uses web requests to a JenkinsRule based test.
Prepare for Jetty 12 EE 9 transition.
* https://github.com/jenkinsci/git-plugin/pull/1589
Also removes unused GitSCMTest methods that were detected while reading the code.
Confirmed that tests pass on my Linux computer with Java 21.
> Move testDoNotifyCommitWithInvalidApiToken and use JenkinsRule

- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/GitStepTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
- src/test/java/jenkins/plugins/git/GitStepTest.java
Adjust package of the GitStepTest so thit can be used to test package protected items from the old location
- **Allow null arg to notifyCommit**
- **Move testDoNotifyCommitWithAllowModeRandomValue to JenkinsRule**
- **Move 3 more mocked tests to JenkinsRule**
- **Document the sha1 parameter**
Automated tests pass.
> Move 3 more mocked tests to JenkinsRule

- src/test/java/hudson/plugins/git/GitStatusTest.java
- src/test/java/hudson/plugins/git/GitStepTest.java
* Remove mocked test replaced in earlier commit
* Match assertions to test names
When transforming the tests from mock objects to JenkinsRule, I mistakenly placed the notifyCommit calls and the assertions in the wrong methods.  Switch them so that the assertion being performed matches the name of the test.
Confirmed that automated tests pass.  Compared assertions from original code with assertions in replacement tests.
> Remove mock object test replaced in earlier commit

- Jenkinsfile
- src/test/java/hudson/plugins/git/FIPSModeUrlCheckTest.java
- src/test/java/jenkins/plugins/git/FIPSModeSCMSourceTest.java
The FIPS tests fail on my Linux computer when run with Jenkins 2.461 or newer.  Run that version on ci.jenkins.io to confirm the tests fail consistently.
`mvn clean -Dtest=FIPS* -Djenkins.version=2.462 verify` fails for me locally with Java 21 on Linux.
> Test with Jenkins 2.462

- src/test/java/hudson/plugins/git/GitStepTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
I forgot that there are other consumers of the Git plugin test suite.
Plugin BOM automated tests detected the problem.
`mvn clean verify` passes and the previous implementation is restored.
> Restore compatibility for GitSampleRepoRule

- pom.xml
An attempt to pass PCT with the pre-release of git plugin 5.3.0
The plugin BOM run to assess the master branch of the git plugin fails two BOM tests, one on the 2.440.x line and one on the 2.452.x line.  The failure can be duplicated locally with the command:
```
$ LINE=2.440.x PLUGINS=pipeline-model-definition  TEST=InjectedTest bash local-test.sh
[ERROR] org.jenkinsci.plugins.pipeline_model_definition.InjectedTest.testPluginActive -- Time elapsed: 0.001 s <<< FAILURE!
java.lang.AssertionError: While testing pipeline-model-definition, git failed to start
at org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive(PluginAutomaticTestBuilder.java:102)
Caused by: java.io.IOException: Failed to load: Git plugin (git 5.3.0-rc5283.29a_5456289b_2)
- Update required: Matrix …
```
> Downgrade matrix-project optional dependency for PCT

- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
- src/test/java/jenkins/plugins/git/GitUsernamePasswordBindingTest.java
Operating systems that provided versions of command line git older than 2.30 are no longer supported by their upstream providers and are thus no longer supported by the Jenkins project.  Remove the special cases in the tests for those unsupported operating systems.
Confirmed that automated tests pass with Java 21 on Linux.  Rely on ci.jenkins.io to test Windows and Java 17.
> Remove test conditionals for unsupported git versions

- src/test/java/jenkins/plugins/git/GitSampleRepoRule.java
Ubuntu 20.04 is supported by Canonical until Apr 2025.  The plugin automated tests should continue to pass on Ubuntu 20.04 while it is still supported.
Fixes mistake made in 59f2bee4917eb6f7300c40d4cf1acb9322582596:
* #1629
Operating systems that provide versions of command line git older than 2.25 are no longer supported by their upstream providers and are thus no longer supported by the Jenkins project.  Restore a conditional for command line git 2.25 until at least May 2025 when Ubuntu 20.04 support will end.
Confirmed with git bisect on Ubuntu 20.04 that this change is what broke 189 tests.
> Restore test support for Ubuntu 20.04 with git 2.25

- README.adoc
- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java
- src/test/java/hudson/plugins/git/CredentialsUserRemoteConfigTest.java
Add the `sparseCheckout` symbol for Pipeline so that users do not need to use the old `$class` syntax.
Includes a test that confirms the sparseCheckout syntax works as expected.
Tested interactively to confirm that the new symbol behaves the same as the old syntax behaved.  Does not include detailed functional testing that the sparseCheckout symbol works as expected, since there are already tests of sparse checkout in other tests.
> Add sparseCheckout symbol for Pipeline

- src/main/java/jenkins/plugins/git/GitSCMSource.java
Changes for FIPS mistakenly placed the requirement for administrator on the field when it previously allowed users with Job/CONFIGURE permission to modify the field.
Duplicated [JENKINS-73676](https://issues.jenkins.io/browse/JENKINS-73676) by installing Jenkins 2.473 with the role strategy plugin.  Configured three users:
* mwaite - Administrator
* a-developer - User with modify permission on jobs and credentials
* a-reader - User with only read permissions
Created a fine-grained personal access token for one of my private GitHub repositories and confirmed that the repository could be read with that credential and could not be read without that credential.
Created the 'Developer-role' and assigned 'a-developer' to the role.  Created the 'Reader-role' and assigned 'a-reader' to the role. …
> [JENKINS-73676] Allow users with Job/CONFIGURE permission to edit remote URL

- src/main/java/hudson/plugins/git/extensions/impl/SparseCheckoutPaths.java
The Jenkins acceptance test harness uses the display name to locate UI components and test them.  It locates those components by display name.
The tests in the acceptance test harness are especially valuable now while we are preparing for the Spring Security 6.x upgrade.  It is better to retain the previous capitalization and preserve Jenkins acceptance test harness results rather than need to spread the capitalization change into the acceptance test harness and related components.
Added TODO item to fix the capitalization in both the git plugin and the acceptance test harness in a future release.
Confirmed that automated tests pass on Java 21 Linux.  Confirmed by review of the acceptance test harness stack trace that the capitalization change is the source of the problem.
> Fix acceptance tests by reverting capitalization change

- src/test/java/hudson/plugins/git/FIPSModeUrlCheckTest.java
There are cases where a longer password is better in the test.  Example:
* https://github.com/jenkinsci/credentials-plugin/pull/558
Confirmed the test passes
> Use a longer password in the automated test

- src/main/java/hudson/plugins/git/GitSCM.java
- src/test/java/hudson/plugins/git/GitSCMTest.java
[JENKINS-73677](https://issues.jenkins.io/browse/JENKINS-73677): Credentials are added to GitClient **after** the client is decorated by extensions.. A plugin cannot for example override the credentials passed in via a GitSCMExtension (Noticed as part of https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/867)
Tested simple scenario: configured Pipeline from SCM with GitSCM with provided Credentials.
> [JENKINS-73677] Decorate GitClient after adding credentials

- pom.xml
[Mina SSHD API plugin 2.14.0-133.vcc091215a_358](https://github.com/jenkinsci/mina-sshd-api-plugin/releases/tag/2.14.0-133.vcc091215a_358) includes a bug fix to move fips-bundle-test to test scope and to not include commons-io in the dependencies of the plugin.  That release is not yet available in plugin BOM.  Once it is available in plugin BOM, this workaround can be removed.
The pull request that resolved the issue in mina sshd api plugin is 
* https://github.com/jenkinsci/mina-sshd-api-plugin/pull/119
Confirmed automated tests pass.
> Temporarily depend on latest mina sshd plugin

- pom.xml
Git client plugin 6.1.0 uses Jakarta EE 9 and requires Java 17.  Better to assure that users of git plugin 5.6.0 also have the matching version of git client plugin for Jakarta EE 9.  Reduces the version testing complications and lets me focus on single versions of each plugin in the 2.479 testing.
Rely on ci.jenkins.io test automation.  Interacive testing will follow before release.
> Depend on git client plugin 6.1.0

- README.adoc
- src/main/java/hudson/plugins/git/GitSCM.java
- src/main/resources/hudson/plugins/git/GitSCM/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
The previous fragment identifiers in the documentation links no longer exist in the plugins.jenkins.io page content.  Readers that click those hyperlinks are taken to the top of the page instead of being taken to the specific content within the page.
Use fragment identifiers that exist so that a click of the link takes the reader to the correct location in the page content.
Partial fix of [JENKINS-75162](https://issues.jenkins.io/browse/JENKINS-75162).
Confirmed that each of the new hyperlinks opens to the correct location.  Checked all other https://plugins.jenkins.io references in the repository to confirm that they resolve to the expected locations.
> [JENKINS-75162] Fix links to plugins.jenkins.io content

- pom.xml
The 2.452.x plugin bill of materials has reached end of life so this workaround can be upgraded to a newer version of matrix-project plugin.
Retain the workaround because the pipeline model definition plugin fails to start on the 2.479.x and 2.492.x lines if the workaround is removed.
Also remove some unnecessary exclusions and low value comments from the pom file.
Reverts and modifies pull request:
* #1710
Confirmed that the plugin BOM tests pass with a pre-release
```
export PLUGINS=pipeline-model-definition
export TEST=InjectedTest
LINE=2.462.x bash local-test.sh
LINE=2.479.x bash local-test.sh
LINE=2.492.x bash local-test.sh
LINE=weekly  bash local-test.sh
```
> Upgrade matrix-project test dependency based on plugin BOM results

- src/main/resources/jenkins/plugins/git/GitStep/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help_ja.html
[[JENKINS-75311]](https://issues.jenkins.io/browse/JENKINS-75311) Fix missing closing quote in checkout scmGit branches argument
Fixed the incorrect checkout scmGit syntax, changing `branches: [[name: 'main]]` to `branches: [[name: 'main']]`.
> [JENKINS-75311] Add closing quote in checkout scmGit branches example

- src/main/java/hudson/plugins/git/GitSCM.java
Jesse Glick notes in [JENKINS-75288](https://issues.jenkins.io/browse/JENKINS-75288):
> adding `@Whitelisted` to a method already marked `@Override` is clearly a mistake—this would never have any effect.
I didn't realize that was a mistake when I added the annotation.  Let's remove the annotation so that the code does not mislead someone to think that this can be used from a Pipeline without changes to hudson.scm.SCM.getBrowser().
In a multibranch Pipeline, the default checkout assigns current values to the scm object, including scm.browser.  That value can't be read unless the hudson.scm.SCM.getBrowser() method is approved through script security.
None.  Already confirmed that the annotation has no effect, as noted in [JENKINS-75288](https://issues.jenkins.io/browse/JENKINS-75288). …
> Remove incorrect annotation on GitSCM.getBrowser()

- pom.xml
Not reviewing checkstyle in this plugin
Confirmed that the ci.jenkins.io job reports no checkstyle warnings before this change.  Confirmed that a local build reports no checkstyle warningsd with `mvn clean verify`.  Will confirm that the ci.jenkins.io job still reports no checkstyle warnings after this change.
> Remove checkstyle build task

- src/main/java/hudson/plugins/git/util/GitUtils.java
#695 effectively removed the bridge method from the generated bytecode by removing `bridge-method-injector` from the build, but it did not remove the `@WithBridgeMethod` annotation, turning it into dead code. Since the intervening 6 years have clearly demonstrated that the bridge method is not actually needed, remove the useless annotation rather than adding `bridge-method-injector` back to the build.
Dumped the bytecode of the class with `javap` before and after this change and verified it was the same (i.e., no bridge method both before and after, as expected).
> Remove useless bridge method injector annotation

- README.adoc
- src/main/resources/hudson/plugins/git/GitSCM/help-extensions.html
- src/main/resources/hudson/plugins/git/GitSCM/help.html
- src/main/resources/hudson/plugins/git/extensions/impl/GitLFSPull/help.html
- src/main/resources/jenkins/plugins/git/GitStep/help-branch.html
- src/main/resources/jenkins/plugins/git/GitStep/help.html
The documentation for the `scmGit` parameter to the `checkout` step is not as immediately accessible from the checkout page as I would like.  Readers have difficulty finding that documentation in the many other documentation links within the `checkout` step.
Add more links to the `scmGit` parameter documentation in hopes that readers will be more likely to find it.
Change also includes other minor documentation improvements like:
- Link from extensions help to plugins help page
- Use most recent Git LFS project link
- Place id on the strong tag instead of a separate a tag
- Fix syntax error in checkout example
- More consistent spacing in examples
Reviewed the formatting and content of the modified documentation pages from within a running Jenkins 2.511.
Confirmed that the newly added …
> Clarify scmGit parameter for checkout Pipeline step

- pom.xml
- src/main/java/hudson/plugins/git/GitChangeSet.java
- src/main/java/hudson/plugins/git/GitStatus.java
- src/main/java/hudson/plugins/git/UserRemoteConfig.java
- src/main/java/hudson/plugins/git/browser/casc/GitLabConfigurator.java
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMBuilder.java
- src/main/java/jenkins/plugins/git/GitSCMFileSystem.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSourceContext.java
- src/main/java/jenkins/plugins/git/traits/DiscoverOtherRefsTrait.java
- src/main/java/jenkins/plugins/git/traits/LocalBranchTrait.java
- src/main/java/jenkins/plugins/git/traits/RemoteNameSCMSourceTrait.java
- src/test/java/hudson/plugins/git/FIPSModeUrlCheckTest.java
Commons Lang 2 has been superseded by Commons Lang 3.  Jenkins core will eventually remove Commons Lang 2.  Use the Commons Lang 3 API plugin so that the dependency on Commons Lang 3 is explicit.
Confirmed that automated tests pass.
> Replace Commons Lang 2 with Commons Lang 3

- pom.xml
- src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
- src/main/java/jenkins/plugins/git/GitSCMSource.java
- src/test/java/jenkins/plugins/git/AbstractGitSCMSourceTest.java
See [JENKINS-75854](https://issues.jenkins.io/browse/JENKINS-75854)
If the "Discover Tags" trait is not set, there is no need to fetch tags on branch indexing.
* Create a multibranch job using the Git branch source
* Make sure the "Discover Tags" trait is not added
* Check that the git command that runs on branch indexing does **not includes** the `--tags` modifier
* Now add the "Discover Tags" trait and trigger branch indexing
* Check that the git command that runs on branch indexing **includes** the `--tags` modifier
> [JENKINS-75854] Do not fetch tags in multibranch Pipeline if "Discover tags" is not enabled
